### ISSUE TITLE
Error with dataloader

### ISSUE THREAD

**Issue by colincqian** [Arthur151/ROMP#102]
Dear Arthur151, I came across this error after running the **V1_train.sh** to reproduce result of your paper.

> Epoch: [1][4528/9722] Time 0.75 RUN 1.26 Lr 2.5e-05 Loss 250.60 | Losses {'reg': 223.19, 'det': 27.41, 'CenterMap': 27.41, 'P_KP2D': 33.48, 'MPJPE': 106.91, 'PAMPJPE': 33.09, 'Pose': 46.39, 'Shape': $
> Epoch: [1][4578/9722] Time 0.65 RUN 1.26 Lr 2.5e-05 Loss 241.55 | Losses {'reg': 218.88, 'det': 22.67, 'CenterMap': 22.67, 'P_KP2D': 32.87, 'MPJPE': 102.17, 'PAMPJPE': 33.1, 'Pose': 47.4, 'Shape': 0.$
> Traceback (most recent call last):
>   File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/cluster/apps/nss/gcc-6.3.0/python/3.7.4/x86_64/lib64/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/cluster/home/chqian/src/ROMP/ROMP/romp/train.py", line 148, in <module>
>     main()
>   File "/cluster/home/chqian/src/ROMP/ROMP/romp/train.py", line 145, in main
>     trainer.train()
>   File "/cluster/home/chqian/src/ROMP/ROMP/romp/train.py", line 33, in train
>     self.train_epoch(epoch)
>   File "/cluster/home/chqian/src/ROMP/ROMP/romp/train.py", line 80, in train_epoch
>     for iter_index, meta_data in enumerate(self.loader):
>   File "/cluster/home/chqian/src/ROMP/ROMP/venv/lib64/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/cluster/home/chqian/src/ROMP/ROMP/venv/lib64/python3.7/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
>     return self._process_data(data)
>   File "/cluster/home/chqian/src/ROMP/ROMP/venv/lib64/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
>     data.reraise()
>   File "/cluster/home/chqian/src/ROMP/ROMP/venv/lib64/python3.7/site-packages/torch/_utils.py", line 425, in reraise
>     raise self.exc_type(msg)
> cv2.error: Caught error in DataLoader worker process 1.
> Original Traceback (most recent call last):
>   File "/cluster/home/chqian/src/ROMP/ROMP/venv/lib64/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/cluster/home/chqian/src/ROMP/ROMP/venv/lib64/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/cluster/home/chqian/src/ROMP/ROMP/venv/lib64/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/cluster/home/chqian/src/ROMP/ROMP/romp/lib/models/../utils/../dataset/mixed_dataset.py", line 71, in __getitem__
>     annots = self.datasets[inds][index_sample]
>   File "/cluster/home/chqian/src/ROMP/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 342, in __getitem__
>     return self.get_item_single_frame(index)
>   File "/cluster/home/chqian/src/ROMP/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 98, in get_item_single_frame
>     image, dst_image, org_image = self.prepare_image(image, image_wbg, augments=(color_jitter, syn_occlusion))
>   File "/cluster/home/chqian/src/ROMP/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 230, in prepare_image
>     dst_image = cv2.resize(image, tuple(self.input_shape), interpolation = cv2.INTER_CUBIC)
> cv2.error: OpenCV(4.5.4-dev) /tmp/pip-req-build-5mtujfce/opencv/modules/core/src/matrix.cpp:466: error: (-215:Assertion failed) _step >= minstep in function 'Mat'
>

I tried to load the dataset and check the images loaded without finding any errors. I am not sure where this error comes from. I hope anyone can give me some advice on solving this. Thank you in advance for your help.

My config is below:

> 2) gcc/4.8.5  
>  3) cudnn/7.5  
>  4) openblas/0.2.20   
> 5) python/3.7.4  
>  6) cuda/10.1.243

My pacakge version:

> absl-py==1.0.0
> addict==2.4.0
> aiohttp==3.8.1
> aiosignal==1.2.0
> anyio==3.3.4
> argcomplete==1.12.3
> argon2-cffi==21.1.0
> async-timeout==4.0.1
> asynctest==0.13.0
> attrs==21.2.0
> autobahn==21.3.1
> Automat==20.2.0
> Babel==2.9.1
> backcall==0.2.0
> bleach==4.1.0
> bvhtoolbox==0.1.3
> cached-property==1.5.2
> cachetools==4.2.4
> certifi==2021.10.8
> cffi==1.15.0
> charset-normalizer==2.0.7
> chumpy==0.70
> colorama==0.4.4
> commonmark==0.9.1
> constantly==15.1.0
> cryptography==35.0.0
> cycler==0.11.0
> Cython==0.29.24
> debugpy==1.5.1
> decorator==5.1.0
> defusedxml==0.7.1
> Deprecated==1.2.13
> deprecation==2.1.0
> entrypoints==0.3
> filterpy==1.4.5
> fonttools==4.28.1
> frozenlist==1.2.0
> fvcore==0.1.5.post20211023
> google-auth==2.3.3
> google-auth-oauthlib==0.4.6
> grpcio==1.41.1
> h5py==3.5.0
> hyperlink==21.0.0
> idna==3.3
> imageio==2.10.4
> imgaug==0.4.0
> importlib-metadata==4.8.2
> importlib-resources==5.4.0
> incremental==21.3.0
> iopath==0.1.9
> ipykernel==6.5.0
> ipython==7.29.0
> ipython-genutils==0.2.0
> ipywidgets==7.6.5
> jedi==0.18.0
> Jinja2==3.0.3
> joblib==1.1.0
> json5==0.9.6
> jsonschema==4.2.1
> jupyter-client==7.0.6
> jupyter-core==4.9.1
> jupyter-packaging==0.11.1
> jupyter-server==1.11.2
> jupyterlab==3.2.3
> jupyterlab-pygments==0.1.2
> jupyterlab-server==2.8.2
> jupyterlab-widgets==1.0.2
> keyboard==0.13.5
> kiwisolver==1.3.2
> lap==0.4.0
> llvmlite==0.37.0
> loguru==0.5.3
> Markdown==3.3.5
> MarkupSafe==2.0.1
> matplotlib==3.5.0
> matplotlib-inline==0.1.3
> mistune==0.8.4
> multidict==5.2.0
> munkres==1.1.4
> nbclassic==0.3.4
> nbclient==0.5.8
> nbconvert==6.3.0
> nbformat==5.1.3
> nest-asyncio==1.5.1
> networkx==2.6.3
> norfair==0.3.1
> notebook==6.4.5
> numba==0.54.1
> numpy==1.20.3
> numpy-quaternion==2021.11.4.15.26.3
> oauthlib==3.1.1
> open3d==0.13.0
> opencv-contrib-python==4.5.4.58
> opencv-python==4.5.4.58
> packaging==21.2
> pandas==1.3.4
> pandocfilters==1.5.0
> parso==0.8.2
> pexpect==4.8.0
> pickleshare==0.7.5
> Pillow==8.4.0
> plotly==5.4.0
> plyfile==0.7.4
> portalocker==2.3.2
> prettytable==2.4.0
> prometheus-client==0.12.0
> prompt-toolkit==3.0.22
> protobuf==3.19.1
> ptyprocess==0.7.0
> pyasn1==0.4.8
> pyasn1-modules==0.2.8
> pycocotools==2.0.2
> pycparser==2.21
> pygame==2.1.0
> Pygments==2.10.0
> pyparsing==2.4.7
> pyrsistent==0.18.0
> python-dateutil==2.8.2
> pytorch3d==0.6.0
> pytz==2021.3
> PyWavelets==1.2.0
> PyYAML==6.0
> pyzmq==22.3.0
> requests==2.26.0
> requests-oauthlib==1.3.0
> rich==9.13.0
> rsa==4.7.2
> scikit-image==0.18.3
> scikit-learn==1.0.1
> scipy==1.7.2
> Send2Trash==1.8.0
> setuptools-scm==6.3.2
> Shapely==1.8.0
> shyaml==0.6.2
> six==1.16.0
> smplx==0.1.28
> sniffio==1.2.0
> tabulate==0.8.9
> tenacity==8.0.1
> tensorboard==2.7.0
> tensorboard-data-server==0.6.1
> tensorboard-plugin-wit==1.8.0
> termcolor==1.1.0
> terminado==0.12.1
> testpath==0.5.0
> threadpoolctl==3.0.0
> tifffile==2021.11.2
> tomli==1.2.2
> tomlkit==0.7.2
> torch==1.9.0
> torchaudio==0.9.0
> torchfile==0.1.0
> torchvision==0.10.0
> tornado==6.1
> tqdm==4.62.3
> traitlets==5.1.1
> transforms3d==0.3.1
> trimesh==3.9.35
> Twisted==21.7.0
> txaio==21.2.1
> typing-extensions==3.10.0.2
> urllib3==1.26.7
> vedo==2021.0.7
> vtk==9.0.3
> wcwidth==0.2.5
> webencodings==0.5.1
> websocket-client==1.2.1
> Werkzeug==2.0.2
> widgetsnbextension==3.5.2
> wrapt==1.13.3
> wslink==1.1.0
> yacs==0.1.8
> yarl==1.7.2
> zipp==3.6.0
> zope.interface==5.4.0
>

**Comment by Arthur151** [comment]
Hi, from the log, ROMP converges fine.
This seems to be the bug of opencv 4.5.4-dev, please see [here](https://github.com/opencv/opencv/issues/20968).
To solve this, I think there are two ways, 
1) use ``try except`` to debug, convert this line:
``File "/cluster/home/chqian/src/ROMP/ROMP/romp/lib/models/../utils/../dataset/image_base.py", line 230, in prepare_image
dst_image = cv2.resize(image, tuple(self.input_shape), interpolation = cv2.INTER_CUBIC)``
to :
``
try:
    dst_image = cv2.resize(image, tuple(self.input_shape), interpolation = cv2.INTER_CUBIC)
except:
    print(image.shape, image)
    dst_image = np.zeros((512,512,3),dtype=np.uint8)
``
Because I think that this is caused by loading the gray image, with 2-dim size, like (512,512).

2) install other version of OpenCV.
Best,
Thanks for your interests.

**Comment by colincqian** [comment]
Dear Arthur151,
Thanks for your reply. I can solve the problem with your provided code. However, I found the printed image shape is (1,1,3), which seems abnormal. Is that what we expect in the training process? Or it is just a reason of incompatible cv2 version.

**Comment by Arthur151** [comment]
I didn't meet this bug during training. I guess this is caused by "incompatible cv2 version".
Thanks for your report. 
Best,
Yu
