### ISSUE TITLE
win10  install pytorch3d  succeed，but this error occurs

### ISSUE THREAD

**Issue by zhanghongyong123456** [Arthur151/ROMP#103]
![image](https://user-images.githubusercontent.com/48466610/142964712-2fc57f42-9b0a-4ba8-b6ea-dfc601d350f5.png)

**Comment by zhanghongyong123456** [comment]
> ![image](https://user-images.githubusercontent.com/48466610/142964712-2fc57f42-9b0a-4ba8-b6ea-dfc601d350f5.png)

![image](https://user-images.githubusercontent.com/48466610/142964784-7cb2e28e-6e9c-4b6e-856f-6a7c2b064f51.png)

**Comment by Arthur151** [comment]
Please install Pytorch3D follow [this instruction](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md).
I don't think it can be installed via pip on Windows.

**Comment by zhanghongyong123456** [comment]
> Please install Pytorch3D follow [this instruction](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md). I don't think it can be installed via pip on Windows.

ok,i try it ,thank you very much
