### ISSUE TITLE
Question about the released Resnet-50 trained models

### ISSUE THREAD

**Issue by neilzhang-strong** [Arthur151/ROMP#106]
Hi, thank you very much for sharing the code. I've tried the code and find a question, when I use the Resnet50 trained model (ROMP_ResNet50_V1.pkl)，there's problem with the results by observing the "save_visulization_on_image" images. The question is that **all the predicted person's positions are higher than the ground-truth in vertical direction**, however, when I use the trained HRNet32 models, it seems everything all right. So I wonder if there's problem with the released Resnet50 trained model?

**Comment by neilzhang-strong** [comment]
![3dpw_sit_on_street](https://user-images.githubusercontent.com/76926657/143550781-845e9b63-bb69-4477-a563-a57a9c3669fd.jpg)
![Cristiano_Ronaldo](https://user-images.githubusercontent.com/76926657/143550798-64f28df3-8a1d-4632-810b-d0a3dea4c742.jpg)
![Leo_Messi](https://user-images.githubusercontent.com/76926657/143550810-794efbfd-a7ea-471a-8e51-3a79b2319181.jpg)

above are the result images

**Comment by Arthur151** [comment]
Please set 'smpl_mesh_root_align': True.

**Comment by neilzhang-strong** [comment]
> 

Great, the results are right now. Thanks very much!

**Comment by Arthur151** [comment]
Thanks for your report! 
Best,
Yu
