### ISSUE TITLE
Question about pretrain

### ISSUE THREAD

**Issue by colincqian** [Arthur151/ROMP#107]
Dear Arthur151,

I wonder whether u are going to provide any instruction on the pretraining process in the future, for I found the pretraining part have large influence on 3D reconstrution performance, especially in the case of multi-person. Right now, I did not find the pretrain.yml in configs folder. Is it possible to provide the config file for pretrain? 

Thank you in advance for your help.

**Comment by Arthur151** [comment]
Sorry, the pretraining process contains some tricks on training backbone from 2D poses, which have very different training pipeline and take long training time / large GPU cost to achieve it. It is important but this is not the key part of ROMP. So I didn't plan to provide relative instruction. Afterall, ROMP has been / would be more and more complicated to support more 3D features. I think that adding this part would be too redundant.
