### ISSUE TITLE
骨盆点的位移

### ISSUE THREAD

**Issue by JACKYLUO1991** [Arthur151/ROMP#108]
您好，请教个问题，当前算法在unity中骨盆点是原地旋转的，有什么方法或者如何调整使得算法可以实现骨盆点跟随移动呢？

**Comment by Arthur151** [comment]
这就是将人体在空间中的位移施加到骨架点上。
只需要将ROMP估计的人体的空间位置施加到模型上即可以，在[这行](https://github.com/Arthur151/ROMP/blob/04ffbb9a2501bcb92e1fe761bb159c2e1c90b1ce/romp/exports/convert_fbx.py#L171)。估计的位移信息是在[这里](https://github.com/Arthur151/ROMP/blob/04ffbb9a2501bcb92e1fe761bb159c2e1c90b1ce/romp/exports/convert_fbx.py#L239)或者[这里](https://github.com/Arthur151/ROMP/blob/04ffbb9a2501bcb92e1fe761bb159c2e1c90b1ce/romp/exports/convert_fbx.py#L246)读取的。
您可以先确认一下有没有成功估计、读取、施加位移信息，我在blender里测试是有唯一的。您看demo也是有位移的。您可以先确认一下以上信息，然后再看看unity方面有没有问题。

**Comment by JACKYLUO1991** [comment]
我之前是用frankmocap，该方法貌似不能如此计算出。另外，不用pytorch3d渲染的时候会出现bug，作者应该没有上传renderer_pyrd文件...

**Comment by Arthur151** [comment]
非常非常抱歉，忘了在master分支更新这个新文件了，只在release包里加上了。现在已经上传了，在[这里](https://github.com/Arthur151/ROMP/blob/master/romp/lib/visualization/renderer_pyrd.py),记得安装pyrender，
通过 
‘pip install pyrender’
即可。
@JACKYLUO1991 非常感谢bug report。
