### ISSUE TITLE
error pose from custom video

### ISSUE THREAD

**Issue by HYLee1008** [Arthur151/ROMP#110]
Thanks for your great work!!

I got some error pose when I run ROMP on my custom video. If there is no person in the video, ROMP produce error pose at every first image of the batch. For example, when I run video inference code with batch size 8 and the beginning of the input video is just nothing just black, ROMP produces error pose in 000000.jpg, 000008.jpg, ...
If I run this single no person image to ROMP with your image inference code, ROMP detects nothing. Is it just me got such error results?

This image is the sample of error.com/44392318/144944743-fe1089bd-bb9e-4e71-88dc-262c6a439bba.jpg)
.

**Comment by Arthur151** [comment]
Thanks for the bug report! I have fixed this bug in the last commit.
Feel free to let me know if there are anything weird.

**Comment by HYLee1008** [comment]
Thanks for your fast response!!
