### ISSUE TITLE
pytorch3d

### ISSUE THREAD

**Issue by Wyethjjj** [Arthur151/ROMP#111]
作者你好，我想请教一下您使用的pytorch3d是什么版本。最近安装过0.2.0版本，可是会缺失很多东西，尝试了0.3.0版本，但有很多文件会报错：# pyre-fixme[21]: Could not find name `_C` in `pytorch3d`.
可能是我安装的途径有问题，但在pytorch3d的Issues里按照作者以及提问人的方法尝试过后都没有成功。
请您指点。

**Comment by Arthur151** [comment]
建议可以尝试ROMP[文档](https://github.com/Arthur151/ROMP/blob/master/docs/installation.md)里介绍的conda环境安装方式，我安装很丝滑，没啥问题。
```
conda create -n ROMP python==3.8.8  
conda activate ROMP  
conda install -n ROMP pytorch==1.9.0 torchvision cudatoolkit=10.2 -c pytorch  
pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu102_pyt190/download.html  
```

**Comment by Wyethjjj** [comment]
感谢！我的情况稍微有点特殊，我的服务器无法使用conda，只能pip，那我试一下使用pip install吧，实在不行只能再尝试手动安装了。再次感谢您，我尝试过后会给您回复。

**Comment by Arthur151** [comment]
我自己电脑就是pip安装的，只注意版本问题。这个pip只能配pytorch==1.9.0，python==3.8，CUDA==10.2，你看这个地方它说的还是听清楚的，py38_cu102_pyt190。

**Comment by NathanWaaang** [comment]
> 我自己电脑就是pip安装的，只注意版本问题。这个pip只能配pytorch==1.9.0，python==3.8，CUDA==10.2，你看这个地方它说的还是听清楚的，py38_cu102_pyt190。 哦对了，它也可以python==3.7 pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py37_cu102_pyt190/download.html

请问 Windows 安装有什么简便方法吗？

**Comment by Wyethjjj** [comment]
作者你好，最近考了三门试，所以答复慢了，根据您的指导，我在服务器新搭建了一个python3.7环境，在解决装各种包的问题后，使用您提供的pip下载链接依旧默认下载0.3.0版本pytorch3d，于是我将命令中的链接拷贝下来用浏览器下载，默认版本为0.6.0，手动安装后成功了，目前代码还在调试中，如果还会出现之前的错误的话，我再向您反馈，谢谢您！

**Comment by littlejiumi** [comment]
你好 我按照您的方法安装的，但是用那个链接导致torch版本自动升级到1.10了，最后运行程序报错
<img width="972" alt="image" src="https://user-images.githubusercontent.com/36367749/146560545-70eead24-6e80-423d-943c-0e7d33c19d12.png">
您知道是什么原因吗
