### ISSUE TITLE
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

### ISSUE THREAD

**Issue by Koushik0901** [Arthur151/ROMP#113]
Hi there, I was just checking out the colab demo, and when I tried running it for the demo video provided it throws this error..... 
I tried setting 
set DISPLAY=:0
export DISPLAY=:0

and it didn't work

**Comment by Arthur151** [comment]
Sorry about that. I have fixed the bug. 
It turns out that colab server doesn't support the newly added pyrender for rendering. I have switch the renderer back to pytorch3D for server. 
It works fine now.

**Comment by Koushik0901** [comment]
Thanks a lot!

**Comment by Andyen512** [comment]
请问服务器上没有图形化界面  程序到这里报错了该怎么办

**Comment by Arthur151** [comment]
@Andyen512 
configs里设置
renderer: 'pytorch3d' 
或者不想要可视化直接设置：
save_visualization_on_img: False
 show_mesh_stand_on_image: False

**Comment by Andyen512** [comment]
> 

thanks
