### ISSUE TITLE
Question: Which one of the pretrained models should I use for 'in the wild' images

### ISSUE THREAD

**Issue by hfassold** [Arthur151/ROMP#114]
Which one of the pretrained models should I use - which model is the 'best' one for 'in the wild' images ?
Are the HRNet models better than the respective ResNet models ?
Should I use the 'V1' variant or the 'V1_ft_3DPW' variant ?
For me, it seems that 'V1_ft_3DPW' is slightly better.

**Comment by Arthur151** [comment]
It is totally up to you. I think that HRNet models are better than ResNet models.

**Comment by hfassold** [comment]
Thanks for the information. And thanks for your implementation, the algorithm works great !
