### ISSUE TITLE
How much time will be needed to train romp with resnet50?

### ISSUE THREAD

**Issue by YongtaoGe** [Arthur151/ROMP#115]

**Comment by YongtaoGe** [comment]
Hi, thank you for your great work. If I want to train romp with 8 gpu, typically how much time does it cost to get a well-trained  model? Thanks.

**Comment by Arthur151** [comment]
It would be quick if you start with provided pre-trained backbone. It requires about a half day on 4 V100 GPU.

**Comment by YongtaoGe** [comment]
Thanks. @Arthur151 If I train from scratch with imagenet pretrained backbone, then typically how much time it will cost.

**Comment by Arthur151** [comment]
I take about 3 weeks to train from scratch.

**Comment by YongtaoGe** [comment]
Thank you. @Arthur151

**Comment by liangwx** [comment]
> 请问你的ImageNet pretrained backbone是从哪里下载的？



> 

请问这里的train from scratch是否使用了ImageNet pretrained backbone？

**Comment by liangwx** [comment]
> I take about 3 weeks to train from scratch.

请问这里的train from scratch是否使用了ImageNet pretrained backbone？

**Comment by liangwx** [comment]
> @Arthur151 Thanks. I don't have any experience in this field. If I train from scratch with ImageNet pretrained backbone, then typically how much time it will cost.

请问你的ImageNet pretrained backbone是从哪里下载的？

**Comment by Arthur151** [comment]
这里他问的是基于resnet50作为backbone来训的，resnet50的imagenet预训练是pytorch自带的。
