### ISSUE TITLE
实时的配置文件用的哪一个？

### ISSUE THREAD

**Issue by shaoguowen** [Arthur151/ROMP#117]
你好，请问一下，实时预测的配置文件用的哪一个？我这边在3090上用webcam.yml测试了一下，好像达不到实时预测。模型预测部分得～50ms/frame

**Comment by Arthur151** [comment]
我这里用一样的配置文件，在1070Ti上都能跑到24FPS，你看demo就可以看出来。
请check几件事情，可能限制了速度：
1. 你的摄像头是不是支持在你的运行环境中采集超过20帧每秒，因为大多数一般的摄像头都不支持高帧率采集的。
2. 你的软硬件配置，包括一些用于深度学习计算加速的库有没有安装，例如MKL等。
3. 可能在不同的硬件系统下三维渲染速度会有差异，你可以去掉可视化的部分看一下模型出结果的部分的速度。因为比较FPS的时候是不包括可视化的，因为确实不同设备对可视化的支持程度不一样，而且这部分对速度影响挺大的。

**Comment by shaoguowen** [comment]
好的，谢谢～

**Comment by liangwx** [comment]
@shaoguowen 请问您的测试速度有没有提升？

**Comment by liangwx** [comment]
我测试的FPS只有13左右。（使用的hrnet32）在RTX8000和3090上基本一样的速度。使用vscode远程调试服务器上的代码FPS更低，只有5左右。

**Comment by Arthur151** [comment]
@liangwx 如果不是硬件的限制的话，可能是缺少必要的模型运行加速库，比如Cudnn，mkl等？

**Comment by Arthur151** [comment]
这个很奇怪，1070Ti电脑上跑的就能到20-24FPS，就是没遇到您的这个问题。我也不清楚到底是什么问题拖累您电脑上的运行速度。只是排除说不是硬件就可能是软件加速的问题了。建议您试试新的simple-romp（代码简化了）的速度，去掉可视化的速度。
