### ISSUE TITLE
Google colab

### ISSUE THREAD

**Issue by FatherPrime** [Arthur151/ROMP#120]
您好，您的google colab似乎出了一些问题。我周一还可以成功运行，但是现在开始报错，您能帮忙检查一下吗？
![image](https://user-images.githubusercontent.com/46631162/146669834-8e2529ae-1bd3-43c9-aff2-affb9d2529a1.png)

**Comment by FatherPrime** [comment]
![image](https://user-images.githubusercontent.com/46631162/146670196-8e04df16-0e89-4186-9f8e-87d5418191d0.png)

**Comment by Arthur151** [comment]
非常感谢您的bug report！
解决了，可以正常使用了。
同时也升级了pytorch 1.10和Pytorch3D

以下为吐槽bug原因，可不看：
我可真是被Pytorch3D搞无语了，它为了让人使用它刚更新的最新版本，它把上一个版本的下载失效了。
为了不被他继续这么搞，我下了个whl安装文件存在了ROMP的release部分，以后版本固定了就。

**Comment by FatherPrime** [comment]
感谢您的修复！
所有的渲染器都挺令人头痛的。

**Comment by Arthur151** [comment]
同意！
