### ISSUE TITLE
pretrain configs

### ISSUE THREAD

**Issue by electron1c** [Arthur151/ROMP#122]
非常棒的工作！
请问您能提供利用您预训练好的resnet/hrnet基础上训练ROMP的configs文件吗？例如scripts/pretrain.sh使用的pretrain.yml

**Comment by Arthur151** [comment]
Sorry, the pretraining process contains some tricks on training backbone from 2D poses, which have very different training pipeline and take long training time / large GPU cost to achieve it. 
使用的训练方法、网络结构都有很大差别，不只是一个config文件的问题。更像是训练2D pose的训练模式，单独一个head branch做这类的任务用于预训练。
It is important but this is not the key part of ROMP. So I didn't plan to provide relative instruction. Afterall, ROMP has been / would be more and more complicated to support more 3D features. I think that adding this part would be too redundant.

**Comment by littlejiumi** [comment]
作者您好，想用trained_models/pretrain_hrnet.pkl模型参数，需要在v1.yml哪处进行更改呢？
期待您的回复，感激不尽

**Comment by Arthur151** [comment]
请将model_path设置为trained_models/pretrain_hrnet.pkl的绝对路径即可。

**Comment by Wyethjjj** [comment]
作者您好，请问成功调用.pkl文件之后训练过程会有什么标志吗？比如loss更小或性能指标起始更好等。

**Comment by Arthur151** [comment]
代码会在[这行](https://github.com/Arthur151/ROMP/blob/02b9d1d8fe6a9797ea0c25ce75c83c975133dee8/romp/base.py#L45)加载预训练参数，使用的函数是[这个](https://github.com/Arthur151/ROMP/blob/02b9d1d8fe6a9797ea0c25ce75c83c975133dee8/romp/lib/utils/train_utils.py#L50)，您可以考虑自己加些print的东西来判断是不是成功加载了。
