### ISSUE TITLE
About Camera Pose

### ISSUE THREAD

**Issue by panshaohua** [Arthur151/ROMP#124]
https://github.com/Arthur151/ROMP/blob/b8d3ac8889c5cd3736182864b43779ee70be8741/romp/lib/dataset/h36m.py#L91

Hi, How did you get "cam" info ? I want to use my own data to training. Look forward to your response. Thx.

**Comment by Arthur151** [comment]
Hi, this is not the typical camera paramters as you think. 'info['cam']' is just the body orientation in camera space. 
To help with developers to use their own data to train. I will write a training guidance and commit it to github before the end of today. I will @panshaohua you in this issue when I release the guidance. Thanks for your interest in ROMP.

**Comment by Arthur151** [comment]
@panshaohua . I have added the [Training guidance](https://github.com/Arthur151/ROMP/blob/master/docs/train.md#training-guidance) in last commit.
Don't hesitate to ask me if there are anything ambiguous.

**Comment by panshaohua** [comment]
Nice. I will consult you if any question. thx

**Comment by panshaohua** [comment]
https://github.com/Arthur151/ROMP/blob/ead489a3a252552e016f5d8088527b1762d34875/romp/lib/dataset/mpi_inf_3dhp.py#L131
why deal with it ? And How I align my own dataset's 3d points to show with "test_dataset()" ?

**Comment by panshaohua** [comment]
Actually, I already extend my dataset as your guidance.

**Comment by Arthur151** [comment]
Glad to hear that~
```
 kp3d = annots_3d[frame_id].reshape(-1,3)/1000 
```
This operation is just to convert the 3D keypoints to Kx3 with mm.
