### ISSUE TITLE
About dataset preprocessing: how to extract frames from original mpi_inf_3dhp dataset

### ISSUE THREAD

**Issue by Tina-Husky** [Arthur151/ROMP#126]
ROMP is an impressive work indeed! Thanks for sharing the code. Besides, it's admirable of you to deal with all the issues in time.
I have a little question about preprocessing of MPI_INF_3DHP dataset.
I examined the `img_names` field in `dataset/mpi-inf-3dhp/cluster_results_noumap_mpiinf_kmeans.npz` and found out that there exists `video_[9,10]` in every `S[1-8]_Seq[1-2]`. It confuses me as the original MPI_INF_3DHP only contains `video_[1-8]` in `S[1-8]_Seq[1-2]`, as illustrated below.
![企业微信截图_1640355146748](https://user-images.githubusercontent.com/27990189/147359362-11b6ecf7-e248-4ad9-bebd-05e9e3989ebd.png)

I wondered how to match the original videos with `annots.npz` or `cluster_results_noumap_mpiinf_kmeans.npz` that is officially provided. To put it another way, to which original videos that the frames with filenames containing `video_[9,10]` correspond?
It'd be appreciated if you could give me some advice. Thank you for your time.

**Comment by Arthur151** [comment]
Thanks for your kind words!
The code about extracting frames from video is placed at [here](https://github.com/Arthur151/ROMP/blob/f4f6bfeb32f06b9f4ba6e4791757db0a501e5c6e/romp/lib/dataset/mpi_inf_3dhp.py#L140). 
About the MPI_INF_3DHP datasets, you may miss some videos. It contains 14 videos (0-13) in each Seq. I drop the unusual view of 11-13 and leave 0-10 for training.

**Comment by Arthur151** [comment]
No feedback

**Comment by Tina-Husky** [comment]
Thank you for your notes and I apologize for the late reply.
I looked at the officially provided MPI-INF-3DHP [download link](http://gvv.mpi-inf.mpg.de/3dhp-dataset/mpi_inf_3dhp.zip) on the [project page](https://vcai.mpi-inf.mpg.de/3dhp-dataset/) and re-checked the `config.ig`.
![image](https://user-images.githubusercontent.com/27990189/147547619-6d964303-0779-4146-a0a5-97ee90983ee6.png)
Line 10 shows the available subjects which range from 1 to 8 instead of from 0 to 13. Besides, I commented out Line 10 and added Line 11 to give it a try by running `bash get_dataset.sh`, but it failed to find the corresponding files.
![image](https://user-images.githubusercontent.com/27990189/147547545-1013b322-9ded-405c-afd0-afbfe4e4c913.png)
I wondered whether this is caused by the version difference. I'd appreciate it if you could share your point of view. Thanks for your time.

**Comment by Tina-Husky** [comment]
Thank you for your notes and I apologize for the late reply.
I looked at the officially provided MPI-INF-3DHP [download link](http://gvv.mpi-inf.mpg.de/3dhp-dataset/mpi_inf_3dhp.zip) on the [project page](https://vcai.mpi-inf.mpg.de/3dhp-dataset/) and re-checked the `config.ig`.
It turns out that `download_extra_wall_cameras` and `download_extra_ceiling_cameras` (Line 13-14) need to be set to `1`. Then we can get the additional `video_[9-13]` in `every S[1-8]_Seq[1-2]`.
![image](https://user-images.githubusercontent.com/27990189/147552297-16fafda9-5c61-4cbf-91f0-ff34fbf10c89.png)
Thanks again for your time. The question has been solved!

**Comment by Arthur151** [comment]
Thanks for sharing this with other developers.

**Comment by liangwx** [comment]
请问cluster_results_noumap_h36m_kmeans.npz和cluster_results_noumap_mpiinf_kmeans.npz是如何生成的，没有找到生成代码

**Comment by Arthur151** [comment]
这个涉及到我们[另一篇论文](https://arxiv.org/abs/2104.11536)使用的姿态聚类方法，相关代码会在论文接收后开源。

**Comment by liangwx** [comment]
请问还有annots_train2014.npz和annots_val2014.npz的生成过程和代码呢？

**Comment by Arthur151** [comment]
在[这里](https://github.com/Arthur151/ROMP/blob/87e80901acbe8dd40bf975a5da010a0cd3357b35/romp/lib/dataset/coco14.py#L105)。每个数据集的annots.npz的生成函数就是各自的pack_data

**Comment by xjchao7** [comment]
I encountered missing data when I used the script to download the MPI_INF_3DHP dataset training. I would like to ask whether there is any encounter and how to solve it?

Thank you very much.

![1](https://user-images.githubusercontent.com/105781839/171536633-b4e2832f-8c3b-4bb1-82da-3325798492bf.png)
