### ISSUE TITLE
aa2rotmat(axis_angle) returns rotation matrix(3*3) not euler angle(3*1)

### ISSUE THREAD

**Issue by youngstu** [Arthur151/ROMP#127]
https://github.com/Arthur151/ROMP/blob/ee5e2f21f35a1072327a11ecd4a36c0c64d805e1/romp/exports/convert_to_bvh.py#L156
     

aa2rotmat(axis_angle) returns rotation matrix(3x3) not euler angle(3x1)，maybe it is a bug.

**Comment by Arthur151** [comment]
Sorry, this function (directly convert to bvh) hasn't been finished. 
I have been moved on to another function. 
You can convert the outputs to .fbx first and then export bvh in Blender.
