### ISSUE TITLE
Gaussian kernel size

### ISSUE THREAD

**Issue by ZhengdiYu** [Arthur151/ROMP#132]
Why did you set k_range=7 (in the paper it's 5) ? Did you just empirically select the value or is there any reference?

**Comment by Arthur151** [comment]
Good question. 
I think you refer to the `k_range` at [this line](https://github.com/Arthur151/ROMP/blob/d2cb47c71a9a599d6e79f6e1db96d8f5568ea4a1/romp/lib/maps_utils/centermap.py#L163). 
`k_range` is set to be the largest size of Gaussian kernel could be. 
In the paper, we set the k_l=2, k_r=5. In code, we set the k_l=1, k_r=7 which is adjusted for your new method, [BEV](https://arxiv.org/abs/2112.08274). Sorry that I forget to change it back when preparing the code release of ROMP. 
This adjustment is to enlarge the difference between subjects of different scales, which benefits the representation learning of BEV from a little experiments. 
You can change it back if you like. My apologies.

**Comment by ZhengdiYu** [comment]
> Good question. I think you refer to the `k_range` at [this line](https://github.com/Arthur151/ROMP/blob/d2cb47c71a9a599d6e79f6e1db96d8f5568ea4a1/romp/lib/maps_utils/centermap.py#L163). `k_range` is set to be the largest size of Gaussian kernel could be. In the paper, we set the k_l=2, k_r=5. In code, we set the k_l=1, k_r=7 which is adjusted for our new method, [BEV](https://arxiv.org/abs/2112.08274). Sorry that I forget to change it back when preparing the code release of ROMP. This adjustment is to enlarge the difference between subjects of different scales, which benefits the representation learning of BEV from a little experiments. You can change it back if you like. My apologies.

@Arthur151  Thank you for your quick reply. Actually I was gonna ask about the principle of you choosing this values, rather than why you change 5 to 7.
![image](https://user-images.githubusercontent.com/63605407/147627220-2a452f2a-a56e-41e2-b64d-5b40b6f664d1.png)

Specifically, how do you get Eq. 1? (e.g. why kl=2 and kr=5, why (d_bb / √ 2W)²) Could you why is it written in this form? I'm new to this area, thank you!

From what I see from the paper, I know it's used in the repulsion field as radius to push apart two body centers when they distance is within the radius. But I just haven't figure out why do you choose 2 and 5. Is this value empirically selected or is there a referenced previous work similar to this? I have checked up Corner-net, objects as points, HRNet(which you mentioned in your first version of CenterHMR), HigherHRNet, but I didn't find an ideal answer to my question. It would be great if you could explain a bit more to me in terms of how you formulate Eq. 1! Thank you!

**Comment by Arthur151** [comment]
Q1. It is designed to automatically adjust the kernel size for subjects of different scales. The size of bounding box can reflect the scale of people. We assign small kernal size for small subjects, which would avoid the center collision for the remote crowds. In this way, our representation is more discriminative for people of different scale.
This idea comes from the dicsussion in a issue (maybe from the rep. of CenterNet/CornetNet). I don't remember which issue contains this discussion. But it has some experiments to prove the effectiveness of this design.

**Comment by Arthur151** [comment]
Q2. The [center_locs ](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/maps_utils/centermap.py#L56) is calculated from 2D keypoints. The keypoints is in a normalized [-1~1] format, please refer to [this function](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L129).
Therefore, we convert the [least_dist](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/maps_utils/centermap.py#L57) to the same normalized format via /self.size*2

**Comment by ZhengdiYu** [comment]
> Q2. The [center_locs ](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/maps_utils/centermap.py#L56) is calculated from 2D keypoints. The keypoints is in a normalized [-1~1] format, please refer to [this function](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L129). Therefore, we convert the [least_dist](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/maps_utils/centermap.py#L57) to the same normalized format via /self.size*2

Q1. Do you mean this one? :https://github.com/princeton-vl/CornerNet/issues/110

Q2. Thank you! I get it now.

**Comment by Arthur151** [comment]
Yes, happy to see it again~

**Comment by ZhengdiYu** [comment]
> Yes, happy to see it again~

Thank you for the maintenance all the time! Could I ask how you generate annots.npz (preprocessing) ? It seems that there is no related code

**Comment by Arthur151** [comment]
Thanks for you kind words. We really appreciate it. 
Q1. This is the pack_data function in each dataset, for example in [3DPW](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/pw3d.py#L235). 

Q2. The change in rate of loading cropped image is designed to facilitate easier learning in the early stage of training from scrach. This operation could be regarded as an augmentation strategy to help ROMP to adapt to single-/multi-person cases well. It would not be necessary if you start training from the provided pre-train model.

**Comment by ZhengdiYu** [comment]
Thanks!

Q1. Can I train from scratch without loading your pre-trained model and without pre-training at all?
       you mentioned that it might take a month to fully train it from scratch.

Q2. As I understand, during pre-training, you only enable the center-map's loss and 2D pose loss on the 2D pose datasets for 120 epochs and then formal training for another 100~120 epochs. And the change in rate of loading cropped image is only crucial for training, so it can be a fixed value if I load from your pre-trained model. Is that correct? 

Q3. CrowdHuman dataset is only used for pre-training, and the 2d annotation is in bbox format, so the collision-aware center-map mechanism will not be activated. Is that correct?

**Comment by Arthur151** [comment]
Q1/Q2. Yes, of course, you may refer to [this issue](https://github.com/Arthur151/ROMP/issues/125) Directly one-time training for long enough time would achieve similar performance. Subtle training configs are designed to make this process faster. Better pre-training would bring better generalization in crowd.

Q3. Please note that the [released code](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L170) support to learn from bounding box annotations. It converts bbox to person centers. So we can still use CAR to better learn discriminater features from Crowdhuman.

Q4. `full_kp2ds` contains kp2ds of all people in the image. `kp2d` is just the kp2ds of one of them. We use this function to determine the subjects that are close to each other for activating CAR to push them apart.

**Comment by ZhengdiYu** [comment]
> Q1/Q2. Yes, of course, you may refer to [this issue](https://github.com/Arthur151/ROMP/issues/125). Directly one-time training for long enough time would achieve similar performance. Subtle training configs are designed to make this process faster. Better pre-training would bring better generalization in the crowd scene.
> 
> Q3. Please note that the [released code](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L170) support to learn from bounding box annotations. It converts bbox to person centers. So we can still use CAR to better learn discriminater features from Crowdhuman.
> 
> Q4. `full_kp2ds` contains kp2ds of all people in the image. `kp2d` is just the kp2ds of one of them. We use this function to determine the subjects that are close to each other for activating CAR to push them apart.
> 
> B.T.W.,郑同学，新年快乐~

谢谢, 新年快乐~

Reply to your answer:

Q1/2. How long will it take to train from scatch? You once said approximately a month? If so, the pre-training is quite important I think.  But I was wondering why would it take so long. Because pre-training and formal training are both around 120 epochs

Q3. I know it converts bbox to person centers. But the 'occluded_by_who' will be None. Because for CrowdHuman (the only one with bbox), the variable 'occluded_by_who' will not be computed:

https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L196-L214

which means that in https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/maps_utils/centermap.py#L52

the center will not be pushed apart.


Q4. I know full_kp2ds contains all people in the image. But my question is that 'full_kp2ds[inds]' should be equal to 'kp2d'

               `for inds, (person_center, kp2d) in enumerate(zip(person_centers, full_kp2ds)):`

So it seems weird for me, because obviously there is kp2d == full_kp2ds[inds] in the for loop. Am I missing something?

**Comment by Arthur151** [comment]
Q1/2. With pre-trained model, you don't have to train 120 epochs to achieve the best performance. 

Q3. Thanks for the remind of this. Sorry, I forget it. 

Q4. Of course, `kp2d == full_kp2ds[inds]`. But why is that influence the computation of `occluded_by_who`. Please note that [this line](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L409) is where we get the `closet_idx`. And we use the **`dist[dist>0]`** which would exclude the `full_kp2ds[inds]` because its `dist` with `kp2d` is equal to 0. Does this explanation make things clear?

**Comment by ZhengdiYu** [comment]
> Q1/2. With pre-trained model, you don't have to train 120 epochs to achieve the best performance.
> 
> Q3. Thanks for the remind of this. Sorry, I forget it.
> 
> Q4. Of course, `kp2d == full_kp2ds[inds]`. But I still don't get why you think that would influence the computation of `occluded_by_who`. Please note that [this line](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L409) is where we get the `closet_idx`. And we use the **`dist[dist>0]`** which would exclude the `full_kp2ds[inds]` because its `dist` with `kp2d` is equal to 0. Does this explanation make things clear?

Q3 and Q4 are NOT related to each other, let me put these clearer:

Q3. For bbox annotation, `L204~L214 in image_based.py` will be executed, but there is no value assigned to `occluded_by_who` in this case. Only if where is_pose2d >0, 'occluded_by_who' would be computed (`L198`). Thus, I think for the data with bbox annotation the `occluded_by_who` will be `None`, which means that in `centermap.py`:https://github.com/Arthur151/ROMP/blob/d2cb47c71a9a599d6e79f6e1db96d8f5568ea4a1/romp/lib/maps_utils/centermap.py#L52

The CAR will not be activated if `occluded_by_who` is None.

Q4. How do you judge whether the person is occluded or not with `kp2d == full_kp2ds[inds]` ? the following code will be executed anyway as it's always True.

**Comment by Arthur151** [comment]
Q3. Yes, I agree with you. Currently released code won't use CAR for bounding box only annotations.

Q4. I judge whether the person is occluded by [this line](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L406). It reflects that the distance between person centers is less than pre-defined threshold, which would trigger CAR.

**Comment by ZhengdiYu** [comment]
> Q3. Yes, I agree with you. Currently released code won't use CAR for bounding box only annotations.
> 
> Q4. I judge whether the person is occluded by [this line](https://github.com/Arthur151/ROMP/blob/35e8de60531dc57989f5e35be19505b450e3f679/romp/lib/dataset/image_base.py#L406). It reflects that the distance between person centers is less than pre-defined threshold, which would trigger CAR.

Thank you! So `if (full_kp2ds[inds,:,0]>0).sum() >= (kp2d[:,0]>0).sum():` this line of code could be deleted, is this correct?

**Comment by Arthur151** [comment]
Sure. Thanks for your review.

**Comment by ZhengdiYu** [comment]
> Sure. Thanks for your review.

Thanks again. You are literally one of those who are most responsible to their work I've ever seen. I will keep on checking up with updates maybe.

**Comment by Arthur151** [comment]
Thank you very much for your recognition, which is very encouraging. I'll keep trying to do a better job. Check our latest work,Putting people in their place: monocular regression of 3D people in depth, if you are interested.
Get Outlook for Android

**Comment by ZhengdiYu** [comment]
> Thank you very much for your recognition, which is very encouraging. I'll keep trying to do a better job. Check our latest work,Putting people in their place: monocular regression of 3D people in depth, if you are interested. Get Outlook for Android

Hi,

I have started to train your model using python -u -m romp.train --configs_yml='configs/v1.yml'. However it gave me an OOM on a 11GB NVIDIA TITAN Xp:
Mon Jan 24 03:09:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN Xp     On   | 00000000:DB:00.0 Off |                  N/A |
| 23%   21C    P8     8W / 250W |      1MiB / 12196MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
root1: /home2/rctv12/projects/ROMP/ project_dir /home2/rctv12/projects/ROMP/multi-person
yaml_timestamp  /home2/rctv12/projects/ROMP/multi-person/active_configs/active_context_2022-01-24_03_10_03.yaml
INFO:root:{'tab': 'hrnet_cm64_V1_hrnet', 'configs_yml': 'configs/v1.yml', 'inputs': None, 'output_dir': None, 'interactive_vis': False, 'show_largest_person_only': False, 'show_mesh_stand_on_image': False, 'soi_camera': 'far', 'make_tracking': False, 'temporal_optimization': False, 'save_dict_results': False, 'save_visualization_on_img': False, 'fps_save': 24, 'character': 'smpl', 'renderer': 'pytorch3d', 'f': None, 'model_return_loss': False, 'model_version': 1, 'multi_person': True, 'new_training': False, 'perspective_proj': False, 'FOV': 60, 'focal_length': 443.4, 'lr': 5e-05, 'adjust_lr_factor': 0.1, 'weight_decay': 1e-06, 'epoch': 120, 'fine_tune': False, 'GPUS': '0,1,2,3', 'batch_size': 64, 'input_size': 512, 'master_batch_size': -1, 'nw': 4, 'optimizer_type': 'Adam', 'pretrain': 'imagenet', 'fix_backbone_training_scratch': False, 'backbone': 'hrnet', 'model_precision': 'fp16', 'deconv_num': 0, 'head_block_num': 2, 'merge_smpl_camera_head': False, 'use_coordmaps': True, 'hrnet_pretrain': '/home2/rctv12/projects/ROMP/multi-person/trained_models/pretrain_hrnet.pkl', 'resnet_pretrain': '/home2/rctv12/projects/ROMP/multi-person/trained_models/pretrain_resnet.pkl', 'loss_thresh': 1000, 'max_supervise_num': -1, 'supervise_cam_params': False, 'match_preds_to_gts_for_supervision': True, 'matching_mode': 'all', 'supervise_global_rot': False, 'HMloss_type': 'MSE', 'eval': False, 'eval_datasets': 'pw3d', 'val_batch_size': 16, 'test_interval': 2000, 'fast_eval_iter': -1, 'top_n_error_vis': 6, 'eval_2dpose': False, 'calc_pck': False, 'PCK_thresh': 150, 'calc_PVE_error': False, 'centermap_size': 64, 'centermap_conf_thresh': 0.2, 'collision_aware_centermap': True, 'collision_factor': 0.2, 'center_def_kp': True, 'local_rank': 0, 'distributed_training': False, 'distillation_learning': False, 'teacher_model_path': '/export/home/suny/CenterMesh/trained_models/3dpw_88_57.8.pkl', 'print_freq': 50, 'model_path': 'None', 'log_path': '/home2/rctv12/projects/ROMP/log/', 'learn_2dpose': False, 'learn_AE': False, 'learn_kp2doffset': False, 'shuffle_crop_mode': True, 'shuffle_crop_ratio_3d': 0.4, 'shuffle_crop_ratio_2d': 0.1, 'Synthetic_occlusion_ratio': 0, 'color_jittering_ratio': 0.2, 'rotate_prob': 0.2, 'dataset_rootdir': '/home2/rctv12/projects/ROMP/dataset/', 'dataset': 'h36m,mpiinf,coco,mpii,lsp,muco,crowdpose', 'voc_dir': '/home2/rctv12/projects/ROMP/dataset/VOCdevkit/VOC2012/', 'max_person': 64, 'homogenize_pose_space': True, 'use_eft': True, 'smpl_mesh_root_align': True, 'Rot_type': '6D', 'rot_dim': 6, 'cam_dim': 3, 'beta_dim': 10, 'smpl_joint_num': 22, 'smpl_model_path': '/home2/rctv12/projects/ROMP/multi-person/model_data/parameters', 'smpl_J_reg_h37m_path': '/home2/rctv12/projects/ROMP/multi-person/model_data/parameters/J_regressor_h36m.npy', 'smpl_J_reg_extra_path': '/home2/rctv12/projects/ROMP/multi-person/model_data/parameters/J_regressor_extra.npy', 'smpl_uvmap': '/home2/rctv12/projects/ROMP/multi-person/model_data/parameters/smpl_vt_ft.npz', 'wardrobe': '/home2/rctv12/projects/ROMP/multi-person/model_data/wardrobe', 'mesh_cloth': '031', 'nvxia_model_path': '/home2/rctv12/projects/ROMP/multi-person/model_data/characters/nvxia', 'track_memory_usage': False, 'adjust_lr_epoch': [], 'kernel_sizes': [5], 'nw_eval': 2, 'MPJPE_weight': 200.0, 'PAMPJPE_weight': 360.0, 'P_KP2D_weight': 400.0, 'Pose_weight': 80.0, 'Shape_weight': 6.0, 'Prior_weight': 1.6, 'CenterMap_weight': 160.0, 'sample_prob_dict': {'h36m': 0.2, 'mpiinf': 0.16, 'coco': 0.2, 'lsp': 0.06, 'mpii': 0.1, 'muco': 0.14, 'crowdpose': 0.14}}
INFO:root:------------------------------------------------------------------
visualize in gpu mode
INFO:root:start building model.
Using ROMP v1
model path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters smpl path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters/SMPL_NEUTRAL.pkl
Confidence: 0.2
INFO:root:missing parameters of layers:[]
INFO:root:finished build model.
INFO:root:gathering datasets
Confidence: 0.2
INFO:root:Start loading 3DPW data.
INFO:root:Loading 3DPW in VIBE mode, split val
INFO:root:3DPW dataset val split total 1661 samples, loading mode vibe
INFO:root:gathering datasets
Confidence: 0.2
INFO:root:Start loading 3DPW data.
INFO:root:Loading 3DPW in VIBE mode, split test
INFO:root:3DPW dataset test split total 24423 samples, loading mode vibe
INFO:root:dataset_val_list:['pw3d']
INFO:root:evaluation_results_dict:['pw3d']
INFO:root:gathering datasets
Confidence: 0.2
model path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters smpl path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters/SMPL_FEMALE.pkl
model path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters smpl path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters/SMPL_MALE.pkl
INFO:root:Loaded Human3.6M data,total 62224 samples
Confidence: 0.2
annots_file_path /home2/rctv12/projects/ROMP/dataset/mpi_inf_3dhp/annots.npz self.data_folder /home2/rctv12/projects/ROMP/dataset/mpi_inf_3dhp/
From file_paths with 133363 samples, removing subjects: ['S8'], with 121071 samples left
INFO:root:Loaded MPI-INF-3DHP train set,total 40357 samples
Confidence: 0.2
model path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters smpl path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters/SMPL_NEUTRAL.pkl
INFO:root:COCO 2D keypoint data has been loaded, total 26455 samples
Confidence: 0.2
remove the same 14679/14679
model path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters smpl path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters/SMPL_NEUTRAL.pkl
INFO:root:Loaded MPII data total 9831 samples
Confidence: 0.2
model path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters smpl path /home2/rctv12/projects/ROMP/multi-person/model_data/parameters/SMPL_NEUTRAL.pkl
INFO:root:LSP dataset total 6829 samples
Confidence: 0.2
INFO:root:MuCo dataset total 20000 samples, loading mode augmented
Confidence: 0.2
INFO:root:Crowdpose 2D keypoint data has been loaded, total 9963 samples
+-----------------+----------------+----------------+---------------+------------+---------------+---------------+-----------+
|                 |      h36m      |     mpiinf     |      coco     |    mpii    |      lsp      |      muco     | crowdpose |
+-----------------+----------------+----------------+---------------+------------+---------------+---------------+-----------+
|      Length     |     62224      |     40357      |     26455     |    9831    |      6829     |     20000     |    9963   |
|   Sample Prob.  |      0.2       |      0.16      |      0.2      |    0.1     |      0.06     |      0.14     |    0.14   |
| Expected length |     311120     |     252231     |     132275    |   98310    |     113816    |     142857    |   71164   |
|   Accum. Prob.  | 0.199951171875 | 0.360107421875 | 0.56005859375 | 0.66015625 | 0.72021484375 | 0.85986328125 |    1.0    |
|    Accum. ID.   |       0        |       0        |       0       |     0      |       0       |       0       |     0     |
+-----------------+----------------+----------------+---------------+------------+---------------+---------------+-----------+
INFO:root:All dataset length: 311120
/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
INFO:root:Initialization of Trainer finished!
INFO:root:start training
INFO:root:Train all layers, except: ['module._result_parser.params_map_parser.smpl_model.betas']
Traceback (most recent call last):
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 148, in <module>
    main()
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 145, in main
    trainer.train()
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 33, in train
    self.train_epoch(epoch)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 90, in train_epoch
    outputs, loss = self.train_step(meta_data)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/train.py", line 38, in train_step
    outputs = self.network_forward(self.model, meta_data, self.train_cfg)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/base.py", line 115, in network_forward
    outputs = model(meta_data, **cfg_dict)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/base.py", line 28, in forward
    return self.matching_forward(meta_data, **cfg)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/base.py", line 39, in matching_forward
    outputs = self.feed_forward(meta_data)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/base.py", line 66, in feed_forward
    x = self.backbone(meta_data['image'].contiguous().cuda())
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/hrnet_32.py", line 189, in forward
    y_list = self.stage3(x_list)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/basic_modules.py", line 297, in forward
    x[i] = self.branches[i](x[i])
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/projects/ROMP/multi-person/romp/lib/models/basic_modules.py", line 47, in forward
    out = self.conv1(x)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home2/rctv12/miniconda3/envs/ROMP/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 11.91 GiB total capacity; 11.08 GiB already allocated; 19.00 MiB free; 11.13 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Arthur151** [comment]
Thanks for your interest in ROMP!
1. To be honest, I haven't tried to train ROMP with batch size 16. But some developers successfully trained ROMP with batch size 32. 
2. We jointly use multiple datasets for training with pre-defined sampling ratio. `expected length` is used to obtain a proper length of the mixed dataset. For H36M, we only use the training set (include S1,S5,S6,S7,S8, exclude S9 and S11, which are usually regarded as test set).
3. `v1.yml` is fine to achieve the fast converge. With pre-trained weights, the top performance could be reached in several epochs.

**Comment by ZhengdiYu** [comment]
> Thanks for your interest in ROMP!
> 
> 1. To be honest, I haven't tried to train ROMP with batch size 16. But some developers successfully trained ROMP with batch size 32.
> 2. We jointly use multiple datasets for training with pre-defined sampling ratio. `expected length` is used to obtain a proper length of the mixed dataset. For H36M, we only use the training set (include S1,S5,S6,S7,S8, exclude S9 and S11, which are usually regarded as test set).
> 3. `v1.yml` is fine to achieve the fast converge. With pre-trained weights, the top performance could be reached in several epochs.

Thanks, but there is no pre-trained weights specified 'v1.yml'. Do you mean that I can alter the setting of 'v1.yml' to '`fine-tune`' and `model path` to a pre-trained weights like trained_models/ROMP_HRNet32_V1.pkl?

**Comment by Arthur151** [comment]
If you want to fine-tune ROMP on other datasets, then `ROMP_HRNet32_V1.pkl` could be a good start. If you want to train with pre-trained weights of backbone, please consider to use the `pretrain_hrnet.pkl` in this [zip](https://github.com/Arthur151/ROMP/releases/download/v1.1/trained_models.zip).

**Comment by Arthur151** [comment]
@ZhengdiYu  My apologize for missing this issue!
I have fixed your suggestions about smpl path and consistent calling. 
About Q3, yes, I need to load the `single image that some person have locations while others only have bboxes`, which would be used in BEV. The released code is prepared when I was developing the next version of ROMP, BEV. Some functions may not be necessary for current version, while they are essential for training BEV. Anyway, these `seemed redundent` functions facilitate ROMP to support more training datasets.

About `valid_mask_2d`, I couldn't find it. But `valid_mask_kp2ds` is an attribute of person, which indicates the status of each person.
