### ISSUE TITLE
Human36M annotations

### ISSUE THREAD

**Issue by Secondgrade** [Arthur151/ROMP#137]
Hello, 
Thanks for your efforts on this excellent repository. I have tried your pretrained model and got nice results. And I have a small question here. How did you generate the parsed data from Human36M? Do you mind share your method of collecting the pose and shape parameters from the Human36M dataset?

**Comment by Arthur151** [comment]
Glad to hear that! Thanks for your kind word.
I didn't collect the pose and shape parameters from the Human36M dataset by myself. I use the parsed parameters from [the work from this group](https://github.com/nghorbani/moshpp). They may meet your need.

**Comment by Secondgrade** [comment]
> Glad to hear that! Thanks for your kind word. I didn't collect the pose and shape parameters from the Human36M dataset by myself. I use the parsed parameters from the work of this group, ([Mosh++](https://github.com/nghorbani/moshpp) and [soma](https://github.com/nghorbani/soma)). They may meet your need.

Ok, thanks for the reply.

**Comment by QiAnBozZ** [comment]
你好，请问其他数据集CoCo的smpl参数标注也是这样获得的吗？

**Comment by Arthur151** [comment]
coco的smpl标注来自于EFT
https://github.com/facebookresearch/eft
