### ISSUE TITLE
关于romp/lib/dataset/image_base.py中detect_occluded_person函数的问题

### ISSUE THREAD

**Issue by zw452** [Arthur151/ROMP#143]
![1641807288(1)](https://user-images.githubusercontent.com/72677585/148744378-e7c184f6-4cdd-4dbb-b776-50cca5ef4ae0.png)

作者你好，非常感谢您提供的算法。关于detect_occluded_person函数我有些疑问，希望您能解答。
红框部分的实现是为了计算两个人是哪个被遮挡了吧，但是看这部分实现并不能实现这个功能吧。感觉full_kp2ds[inds,:,0]和kp2d[:,0]是一样的啊。

**Comment by Arthur151** [comment]
前两天，刚回答了这个问题，请参见[这个](https://github.com/Arthur151/ROMP/issues/132#issuecomment-1004473884)

**Comment by zw452** [comment]
这样的话，两人中心点比较近，不就会被解释成互相遮挡了吗

**Comment by zw452** [comment]
这样遮挡关系是不是就跟输入的顺序有关了。比如输入两个人，其中1号人被0号人遮挡，但是输出会是0号人被1号遮挡

**Comment by Arthur151** [comment]
这个没关系啊，反正推远的斥力会起作用，最后能让两个碰撞的点分开，让表征更有区分性就好。

**Comment by zw452** [comment]
明白了，谢谢您的解答
