### ISSUE TITLE
My own dataset visualization

### ISSUE THREAD

**Issue by MayuOshima** [Arthur151/ROMP#146]
Hello, thanks for your great work!

Actually, I have used your code to train my own dataset and saved the dict.
Now I want to render the predicted meshes. 
How can I get the renderings using the saved 'verts', 'pose', 'betas', 'cam', 'trans'?
I've got the SMPL model and read your code visualization.py. However, it seems you don't use the 'cam' as cam_param.
If I do what visualization.py does, I can't get a correct rendered image.

So could you please tell me how to get the correct rendered images using saved dict information?

**Comment by Arthur151** [comment]
To visualize the mesh on image, you just need to run [visualize_renderer_verts_list](https://github.com/Arthur151/ROMP/blob/af4047356352516b34b767b5e012a85a93a3ffe4/romp/lib/visualization/visualization.py#L102) with right inputs.

The [vertex](https://github.com/Arthur151/ROMP/blob/ec4b8677b9ed2012f2be75a9a75ac099725b8f03/romp/lib/visualization/visualization.py#L100) are just `verts` in npz.

The [estimated translation of meshes](https://github.com/Arthur151/ROMP/blob/ec4b8677b9ed2012f2be75a9a75ac099725b8f03/romp/lib/visualization/visualization.py#L101) are [cam_trans](https://github.com/Arthur151/ROMP/blob/af4047356352516b34b767b5e012a85a93a3ffe4/romp/lib/utils/projection.py#L31). 
I just submit a commit to master to save `cam_trans` into npz via [this line](https://github.com/Arthur151/ROMP/blob/ec4b8677b9ed2012f2be75a9a75ac099725b8f03/romp/predict/base_predictor.py#L55) and [this line](https://github.com/Arthur151/ROMP/blob/ec4b8677b9ed2012f2be75a9a75ac099725b8f03/romp/predict/base_predictor.py#L74).

You just need to collect the npz results into tow lists and put them into `visualize_renderer_verts_list`. For instance, the code might like
```
import numpy as np
import torch
import cv2

results = np.load('path/to/npz',allow_pickle=True)['results'][()]
for img_path in results:
    image_results = results[img_path]
    org_imgs = [cv2.imread(img_path)]
    per_img_verts_list = [torch.from_numpy(image_results[person_id]['verts']).float() for person_id in image_results]
    mesh_trans = [torch.from_numpy(image_results[person_id]['cam_trans']).float() for person_id in image_results]
    rendered_imgs = self.visualize_renderer_verts_list(per_img_verts_list, images=org_imgs, trans=mesh_trans)
```
Just like that~ 
Enjoy your day with ROMP~

**Comment by MayuOshima** [comment]
Thanks for your quic reply!
I have tried your code and it works!
