### ISSUE TITLE
希望将blender中的演示效果放到ue4上，有什么思路吗？

### ISSUE THREAD

**Issue by ykk648** [Arthur151/ROMP#147]
对这方面是零基础，感谢指导

**Comment by Arthur151** [comment]
巧了，我也不懂ue4，完全没用过。

**Comment by jjandnn** [comment]
？FBX啊！动作文件啊。直接导入啊。

**Comment by ykk648** [comment]
@jjandnn 
BVH导入还是一个离线的，如果要做real-time呢，还是回到了ue4的livelink和插件上，目前没找到即开即用的。
感谢，issue close.

**Comment by hsauod** [comment]
hi @ykk648 , have you got some nice ideas?
I am facing the same situation -- want to use UE4

Best,

**Comment by Altai01** [comment]
> 对这方面是零基础，感谢指导

你好，你在blender上驱动成功了吗？

**Comment by ykk648** [comment]
@Altai01 @hsauod  绑定骨骼，传递四元数即可

**Comment by Yuanhong200727** [comment]
@ykk648 您好，我也尝试在unity中使用ROMP去驱动骨骼。请问对于要驱动的初始骨骼有什么要求吗，需要每个骨骼的初始坐标系都与3d引擎使用的坐标系对齐吗？

**Comment by Yuanhong200727** [comment]
> > @ykk648 您好，我也尝试在unity中使用ROMP去驱动骨骼。请问对于要驱动的初始骨骼有什么要求吗，需要每个骨骼的初始坐标系都与3d引擎使用的坐标系对齐吗？我的模型骨骼在导入后，尽管是T-pose，但子节点的坐标系与父节点并不是对齐的
> 
> 四元数是相对旋转，保证全局左右手坐标系一致即可，先用SMPL skeleton调试，尽量用模型去适配骨骼

Hey,我感觉.npz文件中的smpl_thetas里的值都好小呀，计算模得到的旋转角度也是很小，几乎没有旋转。
![2](https://user-images.githubusercontent.com/117512740/216754070-659bc3fe-65be-443a-bf4d-4e67d22845cd.png)
