### ISSUE TITLE
俯拍视角的相机参数变换？

### ISSUE THREAD

**Issue by littlejiumi** [Arthur151/ROMP#148]
![WechatIMG22](https://user-images.githubusercontent.com/36367749/150736439-6b806676-75cb-4ed7-a412-cb3b6bfcd2cb.jpeg)
对于这种视角相机参数应该怎么调整呢？

**Comment by Arthur151** [comment]
ROMP会自己估计人在图像中的位置和人相对于相机的三维旋转角。这一切都是假设相机是正对着向前拍摄的，然后人在相机前变换姿态和角度。ROMP 目前开源的V1版本，采用的是弱透视投影相机，并没有需要调整的什么参数。
请问您是指的是调整预定义的focal length么，还未开源的ROMP的升级版才有这个功能？不知道我理解的对不对？

**Comment by littlejiumi** [comment]
谢谢您的回复！ 请问人对于相机的三位旋转角，是指预测的姿态参数（24维=1+23）中的第一维（root）吗？

**Comment by Arthur151** [comment]
是的，没错！
