### ISSUE TITLE
更换backbone

### ISSUE THREAD

**Issue by StayYouth1993** [Arthur151/ROMP#149]
您好，非常感谢能够开源这篇paper模型，效果真的非常棒。我这边希望能够替换backbone进行蒸馏，请问更换backbone进行蒸馏训练有什么需要注意的么？我这边有些疑惑不知道能否帮忙解答一下：

1. 更换的backbone模型一般是需要通过什么预训练得到呢？【检测 or 分类任务？】
2. 更换backbone以后，backbone部分还需要继续训练么？
3. 更换backbone以后我看resnet最后边还有一个deepconv的适配层，关于这一层，需要单独蒸馏训练么？
4. 蒸馏的时候loss我这边用的是huber loss，在backbone直接输出层做的【目前输出给head部分保持了和hrnet一致的数据，不知是否合理，或者说应该考虑用resnet作为teacher？】
5. 蒸馏的loss function建议直接在最终层做还是更早一些？

万分感谢！

Best！

**Comment by Arthur151** [comment]
非常感谢您的积极评价。关于您想探讨的问题：
1. backbone的预训练我这里用的是2D pose estimation任务，但我也试过ImageNet的pretrain，也能训出来，就是时间久一点。
2. 您指的是，是否需要继续训练新的backbone是么？我这里试过是，backbone需要一起训练的。
3. 我试过蒸馏hrnet，resnet没试过，不清楚。
4. 我觉得hrnet的特征好一点，个人感觉，没有实验支撑。
5. 这个没研究过，不清楚。

**Comment by StayYouth1993** [comment]
非常感谢您的耐心解答，针对backbone的预训练这里我还是有些疑问哈：
1. 你这边训练backbone部分用的2d pose的数据集是什么呢？
2. 训练backbone的时候也是采用的imagenet任务作为pretrain的还是直接从0开始训练的呢？
> 从0开始训练的话要多久？如果是从imagenet任务开始训练大概需要多久？
3. 训练backbone对应的2D的head部分能否share呢？

Best！

**Comment by Arthur151** [comment]
1. pretrain 用的数据集有：coco,crowdpose,posetrack,crowdhuman
2. 我当时的代码是默认使用imagenet pretrain的。之前试过从0开始，其实也差不太多。
3. head的结构可以参考ROMP的前身[centerHMR V1版arxiv论文](https://arxiv.org/pdf/2008.12272v1.pdf)。当时是从Higher-HRNet的head改过来的。这部分代码可以直接参见Higher-HRNet的代码，还没有在ROMP里开源的计划，抱歉。

**Comment by StayYouth1993** [comment]
收到，万分感谢耐心解答！我去试试！
