### ISSUE TITLE
list index out of range, when "Test the data loading"

### ISSUE THREAD

**Issue by liangwx** [Arthur151/ROMP#152]

**Comment by liangwx** [comment]
@Arthur151

**Comment by Arthur151** [comment]
Please check the loaded image path.

**Comment by liangwx** [comment]
当_=3414的时候，出现的这个list index out of range，我看了一下是只loader了1张图片，前3413次都是2张

**Comment by Arthur151** [comment]
这样啊，你可真有耐心，我的那个image_base里的测试代码，只是测试加载的处理后的标柱是不是和图片对应正确，确认没有被中间处理搞坏了，我从来没跑过一个epoch。。。你要是硬要跑一个epoch，可以给Dataloader加个drop_last=True就好了。

**Comment by liangwx** [comment]
非常感谢，的确解决了问题，但是lsp数据集图片一共是9428张，每次load2张，4714次就可以不重复的load完一个epoch，请问为什么会在4714之前就出现list index out of range的问题，又为什么需要drop_last才能避免这个问题？

**Comment by Arthur151** [comment]
应该是有的图片没有标注，所以被排除掉了
