### ISSUE TITLE
Bus Error / Segmentation Fault

### ISSUE THREAD

**Issue by Karric** [Arthur151/ROMP#153]
I successfully installed the requirements for this on my macOS M1 Max machine. When I run

`python3 -m romp.predict.image --inputs=demo/images --output_dir=demo/image_results`

I get:

`[1]    59077 segmentation fault  python3 -m romp.predict.image --inputs=demo/images`

The demo images are the default ones from this repo. I did not change any settings or configs.

Any tips would be appreciated.

**Comment by Arthur151** [comment]
I think this bug might be caused by the visualization part. To check this guess, please set `save_visualization_on_img=False` in configs/image.yml. We can ensure this, if the code can be run without this bug. To fix this bug, you can try to set `renderer ='pytorch3d'`, to use 'pytorch3d' for rendering. 
Don't hestitate to reach to me, if there are anything wrong.

**Comment by Karric** [comment]
@Arthur151 - I updated `configs/image.yml` to use `save_visualization_on_img=False`. I tried `renderer='pytorch3d'` and `renderer='pyrender'` and got the same error.

I added a lot of print statements and the bus error seems to come from this line in `base_predictor.py`:
`from utils.demo_utils import save_meshes, get_video_bn, Time_counter`
If I comment out the above, I don't get the bus error, I get this instead:

> ImportError: cannot import name 'notf' from 'tensorboard.compat' (/Users/x/miniforge3/lib/python3.9/site-packages/tensorboard/compat/\_\_init\_\_.py)
> ...
>   File "/Users/x/miniforge3/lib/python3.9/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 41, in <module>
>     InputSpec = tf_base_layers.InputSpec
> AttributeError: partially initialized module 'tensorflow.python.layers.base' has no attribute 'InputSpec' (most likely due to a circular import)

**Comment by Karric** [comment]
Do you know if there's a tensorflow implementation of this without pytorch? Pytorch in general does not work well on M1 macOS.

**Comment by Arthur151** [comment]
> tensorboard



> @Arthur151 - I updated `configs/image.yml` to use `save_visualization_on_img=False`. I tried `renderer='pytorch3d'` and `renderer='pyrender'` and got the same error.
> 
> I added a lot of print statements and the bus error seems to come from this line in `base_predictor.py`: `from utils.demo_utils import save_meshes, get_video_bn, Time_counter` If I comment out the above, I don't get the bus error, I get this instead:
> 
> > ImportError: cannot import name 'notf' from 'tensorboard.compat' (/Users/x/miniforge3/lib/python3.9/site-packages/tensorboard/compat/__init__.py)
> > ...
> > File "/Users/x/miniforge3/lib/python3.9/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 41, in 
> > InputSpec = tf_base_layers.InputSpec
> > AttributeError: partially initialized module 'tensorflow.python.layers.base' has no attribute 'InputSpec' (most likely due to a circular import)

I think that this error might brought by the installation of tensorboard. Please comment the tensorboard import & call lines to avoid this. Tensorboard is only used during training. It won't effect the inference process.

Sorry, I haven't found the tensorflow implementation of ROMP.

**Comment by Karric** [comment]
@Arthur151 I commented out tensorboard. I now get this error:

`raise AssertionError("Torch not compiled with CUDA enabled")`

I'm on a new MacBook M1 Max, so the GPU does not have CUDA support. I'm not interested in training the model, I just want to use image.py and video.py — is CUDA necessary for this?

**Comment by Arthur151** [comment]
To avoid the CUDA bug. please set `GPUS: -1` in configs_ymls to run the code in cpu mode.

**Comment by Arthur151** [comment]
Sorry for the unpleasant experiments on Mac. I didn't expect that. My appologize.
