### ISSUE TITLE
[FAQ] Why 'pytorch3d' instead of 'pyrender'?

### ISSUE THREAD

**Issue by vivi90** [Arthur151/ROMP#157]
I am new to PyTorch and ROMP works fine with 'pyrender' for me on Windows 10 and Python 3.9.7.
So why should i use ROMP with 'pytorch3d' instead?

**Comment by Arthur151** [comment]
pyrender can't run on server where we train ROMP. For running ROMP on remote server, I replace pyrender with pytorch3d.Get Outlook for Android

**Comment by vivi90** [comment]
Thank you!
Let's add an note to https://github.com/Arthur151/ROMP/blob/48d599e2993e79dccb3323a833b3a24c9e633100/docs/installation.md

**Comment by Arthur151** [comment]
Thanks for the great suggestions. I have added it at [here](https://github.com/Arthur151/ROMP/blob/master/docs/installation.md#2-optional-install-pytorch3d-for-rendering-otherwise-please-refer-to-this-instruction-to-use-pyrender-via-seting-renderer-pyrender)
