### ISSUE TITLE
why only use 22 joints rather than 24

### ISSUE THREAD

**Issue by akk-123** [Arthur151/ROMP#160]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/98469560/154903762-31815dcc-2e1b-4945-bd67-99f63feef07d.png">

hi, @Arthur151 , why drop last two hand joints

**Comment by Arthur151** [comment]
Parameters of last two hand joints are used to control hand gesture, while we don't estimate them.Get Outlook for Android
