### ISSUE TITLE
肘关节旋转限制问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [Arthur151/ROMP#165]
请教个问题，我在测试过程中发现肘关节由于预测错误导致来回翻转，您知道如何通过限制角度来校正角度问题吗？

**Comment by Arthur151** [comment]
如果是视频的话，可以考虑参考这个施加平滑去抖：
https://github.com/Arthur151/ROMP/issues/162#issuecomment-1049634407

如果是想对输出的角度进行操作的话，可以用[这个函数](https://github.com/Arthur151/ROMP/blob/87e80901acbe8dd40bf975a5da010a0cd3357b35/romp/lib/utils/util.py#L405),将估计的角度（vec），转换成其他更易懂的形式，比如eular 欧拉角。

**Comment by JACKYLUO1991** [comment]
@Arthur151 感谢，这个问题貌似不是抖动问题，是由于手心手背来回翻转导致肘关节轴角预测错误，需要对角度加以约束。是否可以将其转为欧拉角再限制其角度呢？

**Comment by Arthur151** [comment]
来回翻转，其实就是角度的高频变化，都可以用我们的那个低通滤波器去平滑掉这种高频变化。也就是上个回复提到的。

当然可以转成欧拉角进行限制，然后再转回来vec进行mesh的估计。

整个过程可以参考：
https://github.com/Arthur151/ROMP/blob/87e80901acbe8dd40bf975a5da010a0cd3357b35/romp/predict/video.py#L122
L100-L122

**Comment by JACKYLUO1991** [comment]
@Arthur151 十分感谢！

**Comment by JACKYLUO1991** [comment]
@Arthur151 劳烦问一下，对一欧元滤波参数的含义不是很清晰...

**Comment by Arthur151** [comment]
认真看一下代码就清楚了。说不太明白。。
https://cristal.univ-lille.fr/~casiez/1euro/

**Comment by luoww1992** [comment]
@JACKYLUO1991 , i also have the same question in webcam with romp, not simple_romp.
how to add it in romp in webcam?
thank you!

**Comment by luoww1992** [comment]
@Arthur151 ,
i have added the smooth with OneEuroFilter. But no change.
how to add it(video.py: outputs.update(self.model.module._result_parser......)) in romp in webcam?

**Comment by Arthur151** [comment]
Hi, @luoww1992 ,

Maybe you need to adjust the coefficient (smooth_coeff to smaller number) to get better smoothness.
