### ISSUE TITLE
crop操作

### ISSUE THREAD

**Issue by owlmoo** [Arthur151/ROMP#169]
作者您好，我想拿你们的模型在自建数据集上做训练，但是直接训效果不好，做crop后应该会改善一点。你们的代码里提供了根据bbox进行crop的操作吗，我注意到训练的时候有概率会看到crop后的可视化，但是没有找到做操作的代码位置。

**Comment by Arthur151** [comment]
是的，有的。
在lib/dataset/image_base.py里调用了lib/utils/augments.py里的
https://github.com/Arthur151/ROMP/blob/3f0e5c6e4729e9a95fbd7bd3e05737ed2dbcc214/romp/lib/utils/augments.py#L150
可以在https://github.com/Arthur151/ROMP/blob/3f0e5c6e4729e9a95fbd7bd3e05737ed2dbcc214/romp/lib/utils/augments.py#L176
设置图片截图框

**Comment by owlmoo** [comment]
哦，找到了！谢谢大佬！
