### ISSUE TITLE
训练时间问题

### ISSUE THREAD

**Issue by Wyethjjj** [Arthur151/ROMP#170]
作者您好，我将Basic ResNet block的数量改为3，修改之后训练速度特别慢，后来我又将其改回来，可是训练依旧不如从前，部分log如下所示：
Epoch: [0][100/19445] Time 2.87 RUN 0.87 Lr 5e-05 Loss 617.70 | Losses {'reg': 567.27, 'det': 50.43, 'CenterMap': 50.43, 'P_KP2D': 167.41, 'MPJPE': 149.72, 'PAMPJPE': 88.8, 'Pose': 151.92, 'Shape': 0.76, 'Prior': 8.66}
Epoch: [0][150/19445] Time 3.50 RUN 0.88 Lr 5e-05 Loss 507.33 | Losses {'reg': 462.25, 'det': 45.08, 'CenterMap': 45.08, 'P_KP2D': 136.46, 'MPJPE': 143.47, 'PAMPJPE': 69.17, 'Pose': 109.13, 'Shape': 0.86, 'Prior': 3.17}
Epoch: [0][200/19445] Time 4.52 RUN 0.90 Lr 5e-05 Loss 461.33 | Losses {'reg': 425.56, 'det': 35.76, 'CenterMap': 35.76, 'P_KP2D': 103.63, 'MPJPE': 138.02, 'PAMPJPE': 79.82, 'Pose': 100.42, 'Shape': 0.81, 'Prior': 2.87}
Epoch: [0][250/19445] Time 4.62 RUN 0.90 Lr 5e-05 Loss 432.20 | Losses {'reg': 386.74, 'det': 45.46, 'CenterMap': 45.46, 'P_KP2D': 95.82, 'MPJPE': 124.5, 'PAMPJPE': 67.42, 'Pose': 95.41, 'Shape': 0.83, 'Prior': 2.76}
Epoch: [0][300/19445] Time 4.48 RUN 0.90 Lr 5e-05 Loss 446.01 | Losses {'reg': 402.76, 'det': 43.25, 'CenterMap': 43.25, 'P_KP2D': 91.53, 'MPJPE': 140.57, 'PAMPJPE': 79.84, 'Pose': 87.18, 'Shape': 0.84, 'Prior': 2.8}
Epoch: [0][350/19445] Time 5.96 RUN 0.90 Lr 5e-05 Loss 434.57 | Losses {'reg': 389.19, 'det': 45.38, 'CenterMap': 45.38, 'P_KP2D': 91.37, 'MPJPE': 127.12, 'PAMPJPE': 75.18, 'Pose': 91.93, 'Shape': 0.69, 'Prior': 2.9}
Epoch: [0][400/19445] Time 5.32 RUN 0.90 Lr 5e-05 Loss 415.13 | Losses {'reg': 372.84, 'det': 42.29, 'CenterMap': 42.29, 'P_KP2D': 77.94, 'MPJPE': 138.16, 'PAMPJPE': 71.34, 'Pose': 81.85, 'Shape': 0.68, 'Prior': 2.87}
Epoch: [0][450/19445] Time 6.87 RUN 0.91 Lr 5e-05 Loss 417.61 | Losses {'reg': 371.05, 'det': 46.56, 'CenterMap': 46.56, 'P_KP2D': 77.61, 'MPJPE': 125.83, 'PAMPJPE': 85.55, 'Pose': 78.66, 'Shape': 0.72, 'Prior': 2.69}
Epoch: [0][500/19445] Time 5.74 RUN 0.91 Lr 5e-05 Loss 425.18 | Losses {'reg': 382.45, 'det': 42.73, 'CenterMap': 42.73, 'P_KP2D': 75.84, 'MPJPE': 139.61, 'PAMPJPE': 88.98, 'Pose': 74.82, 'Shape': 0.6, 'Prior': 2.6}

Time之前都为0，RUN要比之前大将近一倍，请问作者我可以检查哪里来进行调整？

**Comment by Arthur151** [comment]
https://github.com/Arthur151/ROMP/blob/3f0e5c6e4729e9a95fbd7bd3e05737ed2dbcc214/romp/train.py#L57
看这里可以知道，Time指的是数据加载时间，RUN是模型运行+loss反传时间，看你的log应该是数据加载时间过长，和模型没有关系。
