### ISSUE TITLE
How to decide the focal length

### ISSUE THREAD

**Issue by ZhengdiYu** [Arthur151/ROMP#171]
Hi, I was wondering how should we decide focal length when we are in various situation, for example sometimes very close or far away

And here in ROMP, we rescale the image into 512. When we apply to a different camera which from what I see the focal length is [1265, 1265] while the image has different size. If I want to project the 3D mesh onto the image,. How should I change the focal length?

**Comment by Arthur151** [comment]
Hi, long time no see~
I am seeking the solution to get the camera parameter estimation involved too. I guess maybe SLAM / SFM - related method can help with that. 

The focal length f is calculated as
```
f = (H / 2)  / (tan(FOV/2)) 
```
where H is the height of image, and FOV is the field of view (angle).
You can first calculate the FOV with given focal length (like [1265, 1265]) and original image height H,  and then re-calculate the f for our H=512.

**Comment by ZhengdiYu** [comment]
> Hi, long time no see~ I am seeking the solution to get the camera parameter estimation involved too. I guess maybe SLAM / SFM - related method can help with that.
> 
> The focal length f is calculated as
> 
> ```
> f = (H / 2)  / (tan(FOV/2)) 
> ```
> 
> where H is the height of image, and FOV is the field of view (angle). You can first calculate the FOV with given focal length (like [1265, 1265]) and original image height H, and then re-calculate the f for our H=512.

Great! Thanks for that.

By the way, does your image.py support multi-GPU? I think the logic is only for single gpu and if we use multi-gpu, there will be errors. I will try to fix this.

And, does save_mesh_stand_on_img support running on server without desktop? My laptop is Windows so it's sometimes annoying to get the environment set up, for which I prefer to run it on server. But it would crash with only one message :"aborted" before we call image_result = plt.show(camera=camera_pose) in vedo_visualizer.py

**Comment by Arthur151** [comment]
Why does it not support multi-GPU? Anything wrong in logic?

save_mesh_stand_on_img uses vedo for rendering, which need visulization hardwares which most servers don't have.
