### ISSUE TITLE
simple-romp output .npz file

### ISSUE THREAD

**Issue by marson666** [Arthur151/ROMP#180]
Hi, thanks for your great work!
I am trying to use the simple-romp output .npz file of 'joints' as 3D keypoints positions, but i find that it has no global root position movement, i find that in romp export folder, it uses 'cam_trans' [here](https://github.com/Arthur151/ROMP/blob/1b1c37322f7096da5f544b11a1e1c1c13bf6a259/romp/predict/base_predictor.py#L53) to trans global position. But the simple-romp output .npz file only has 'cam' param, does the cam has the same meaning with 'cam_trans' ?
Look forward to your reply!

**Comment by Arthur151** [comment]
Hi, thanks for your kind words!
At [here](https://github.com/Arthur151/ROMP/blob/2db91146ad3d880a9542d6f78d688cc1dcc980cc/simple_romp/romp/post_parser.py#L99), we also convert 'cam_trans' from 'cam'.
Feel free to create your own version of simple-romp. Just to run `python setup.py install` in `simple-romp` folder after editing.
