### ISSUE TITLE
[BUG] center map radius error

### ISSUE THREAD

**Issue by ZhengdiYu** [Arthur151/ROMP#187]
https://github.com/Arthur151/ROMP/blob/f1d0d227d3cb655dc0e66e5ce6435bc8cfcc4ccb/romp/lib/maps_utils/centermap.py#L138-L145

Here, you mean to normalize back bbox_hw_norm by `(bbox_norm+1)/2*args().centermap_size` . But it's not correct, it should be `bbox_hw_oncm = (bbox_norm)/2*args().centermap_size `:

if x_min=a, x_max=b, then W=b-a

In the code you first normalize x_min and x_max by xmin = xmin *2 -1, or, if it's computed from kps, you would normalize kps first, then compute the box based on the normalized kps. 

So the correct way to transfer bboxes_HW_norm back is [(x_max+1) /2 * centermap_size - (x_min+1) /2 * centermap_size].  `bbox_hw_oncm = (bbox_norm)/2*args().centermap_size `

This is not equal to [(x_max - x_min) + 1] /2 *centermap_size

This would make it completely wrong. To the current version, it doesn't really matter that much, as it only affects the radius calculation.

**Comment by Arthur151** [comment]
Thanks a lot for your carefully code review! 
So nice to have you, Zhengdi Yu!
I have fixed this according to your instruction and declare your contribution in last commit.
