### ISSUE TITLE
关于h36m的smpl参数问题

### ISSUE THREAD

**Issue by SidneyRey** [Arthur151/ROMP#189]
作者您好，感谢您的贡献！
我有两个数据处理的问题，想请教：
1）human3.6m的annots，怎么对应到视频上
2）用您提供的h36m smpl GT，训练单人任务，中心抠图作为输入。GT中除了要改2D joints，3D Joints和smpl参数是否需要改动
期待您的回复，谢谢。

**Comment by Arthur151** [comment]
这部分数据预处理的代码，我还没有整理。我找找吧。。不一定找得到，三年前写的。
https://github.com/Arthur151/ROMP/blob/master/romp/lib/dataset/preprocess/h36m_extract_frames.py
可能这个视频帧抽取代码，会对您有帮助。
单人不需要改什么3D标注，他们都是根结点配准的。
