### ISSUE TITLE
How to convert model to pth?

### ISSUE THREAD

**Issue by ArtiX-GP** [Arthur151/ROMP#194]
Can I convert .pkl file to .pth? For further conversion to ptl?

I tried to convert using `torch.jit.script`, but I have error
```
Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults
```

**Comment by Arthur151** [comment]
Hi, I just update an example at [here](https://github.com/Arthur151/ROMP/tree/master/simple_romp#tools)

**Comment by vivi90** [comment]
@Arthur151 How about an extra package `romp-tools`?
https://github.com/Arthur151/ROMP/commit/ea7e390fcc86ad90c730e0a4d10d270f7d5ecf4e

**Comment by Arthur151** [comment]
If we can build a toolbox which can be useful to all related method, of course, we need a individual package.

**Comment by ArtiX-GP** [comment]
`AttributeError: 'collections.OrderedDict' object has no attribute 'eval'`
It's not .pth file, structure of converted file same as .pkl file :(

**Comment by ArtiX-GP** [comment]
I tried convert model using
```
...
model_scripted = torch.jit.script(self.model)  # Export to TorchScript
model_scripted.save('model_scripted.pt') 
```

I have the error:

```
...
TypeError: 
'numpy.int64' object in attribute 'Conv2d.out_channels' is not a valid constant.
Valid constants are:
1. a nn.ModuleList
2. a value of type {bool, float, int, str, NoneType, torch.device, torch.layout, torch.dtype}
3. a list or tuple of (2)
```

It fixes in 'models/base.py' by force convert `out_channels` to `int` instead of `numpy.int64`.

But there are other errors, up to errors inside the PyTorch library. That is, this option is not suitable at the moment. Maybe someone has a solution?

**Comment by Arthur151** [comment]
I am not familiar with this. Why do we need to convert it to pt?
I have converted ROMP to onnx / tensorRT, which would be released later.

**Comment by ArtiX-GP** [comment]
Obviously the problem is in DataParallel, judging by the existing discussions on github. Maybe you know how to remove DataParallel.

It's great that you managed to convert to ONNX? When can you suggest a solution for converting to ONNX?

I ran into the problem of converting the model to .ptl, I want to try to run it in ONNX format

**Comment by Arthur151** [comment]
I will release the next version with onnx and relative code before the end of this week. 
I will update this issue when I make it.

**Comment by ArtiX-GP** [comment]
Hi, @Arthur151 ! How is the progress with the release, will it be published today or tomorrow?
If suddenly there are difficulties with the release, maybe you can help with exporting the model to .onnx? Please

**Comment by Arthur151** [comment]
Yes, the progress is fine. I will release it tommorrow with onnx support. I am working on solving some reliance problem.

**Comment by Arthur151** [comment]
Hi, I update v0.0.4 with support for onnx
