### ISSUE TITLE
[simple-romp] Semantic versioning & releases

### ISSUE THREAD

**Issue by vivi90** [Arthur151/ROMP#195]
It seems, that the version of `simple-romp` might be wrong:
https://github.com/Arthur151/ROMP/blob/50fff8bde341232c4ac34f8dadc3c3604ce2290d/simple_romp/setup.py#L13
According to:
https://semver.org
It should be: 
```
version='0.3.1', 
```
Because of:
```
<BREAKING_CHANGES>.<FEATURES>.<FIXES>
```
How do you think about this?

I would also love to have an version-tag (`simple-romp-v0.3.1` ?) to be able to create `conda` packages easierly:
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html#pypi-source
Of course i would also publish it for you, if it's okay.

**Comment by Arthur151** [comment]
Thanks for your good advise about version. I will follow this pattern then. 
I am still preparing 0.1.0, which have all features of previous code. I intend to update the formal version to fix the bugs reported.
I don't understand the conda package.

**Comment by vivi90** [comment]
> I don't understand the conda package.

No problem, i will do it for you.

**Comment by Arthur151** [comment]
Thanks! I will update this issue when I release the 0.1.0. 
Best regard,
Yu

**Comment by vivi90** [comment]
@Arthur151 
> [..] I will update this issue when I release the 0.1.0. [..]

Sorry, but i have huge problems to get an overview, which versions are published at which commits.

If i check the tags, then i get the following:
 * [v0.0](https://github.com/Arthur151/ROMP/releases/tag/v0.0) targets first [**ROMP** demo code](https://github.com/Arthur151/ROMP/tree/d9b20fbe2bbdb0ec59e5be74970dd08632f4ac9a)
 * [v0.1](https://github.com/Arthur151/ROMP/releases/tag/v0.1) introduces webcam support and targets [**ROMP** code](https://github.com/Arthur151/ROMP/tree/5b24bf33da28b181b816a7bdb7d43a4cf18317fd)
 * [v1.0](https://github.com/Arthur151/ROMP/releases/tag/v1.0) is Formal version 1.0 and targets [**ROMP** code](https://github.com/Arthur151/ROMP/tree/00cbc8430a20bdc0980c4daa641983e136f0e737)
 * [v1.1](https://github.com/Arthur151/ROMP/releases/tag/v1.1) is an collection of improvements and targets [**ROMP** code](https://github.com/Arthur151/ROMP/tree/0f896212bdc464f0ed09f6cf263c1212639e542c)
 * [S1](https://github.com/Arthur151/ROMP/releases/tag/S1) is the blend of ROMP and BEV in **Simple ROMP** *but* targets [**NOT** Simple ROMP code](https://github.com/Arthur151/ROMP/tree/dee1b80a5244dbca78637a494133958146b02bb9)

On the other hand, if i check the [`simple-romp` package at PyPi](https://pypi.org/project/simple-romp/#history) for `pip`, then i get:
 * [v0.0.1](https://pypi.org/project/simple-romp/0.0.1/#files) first Simple ROMP release targets to [**Simple ROMP** code](https://github.com/Arthur151/ROMP/tree/fdd55cfdf0544c59bffb37e1f7ab458f09d8b5b0)
 * one unpublised [update](https://github.com/Arthur151/ROMP/tree/2a28118d4be15aa0cf39c297ee0d0c67dda05a4d) that doesn't change the `version` in [`setup.py`](https://github.com/Arthur151/ROMP/blob/2a28118d4be15aa0cf39c297ee0d0c67dda05a4d/simple_romp/setup.py#L13) (but it SHOULD)
 * [v0.0.2](https://pypi.org/project/simple-romp/0.0.2/#files) Simple ROMP targets to **which commit?**
 * [v0.0.3](https://pypi.org/project/simple-romp/0.0.3/#files) Mac support for Simple ROMP targets to [**Simple ROMP** code](https://github.com/Arthur151/ROMP/tree/623687a37cb7d1ba4538baf1e3c6f65808a36e2c)
 * [remove black reliance](https://github.com/Arthur151/ROMP/tree/50fff8bde341232c4ac34f8dadc3c3604ce2290d) but not published or at least noted with an `version` change in [`setup.py`](https://github.com/Arthur151/ROMP/blob/50fff8bde341232c4ac34f8dadc3c3604ce2290d/simple_romp/setup.py#L13) (but it SHOULD)
 * [v0.0.4](https://pypi.org/project/simple-romp/0.0.4/#files) release targets to [**Simple ROMP** code](https://github.com/Arthur151/ROMP/tree/5649fb7d0bf8ad76d818ae678afa6752f6391811)
 * [v0.1.0](https://pypi.org/project/simple-romp/0.1.0/#files) introduces BEV blend and targets to [**Simple ROMP** code](https://github.com/Arthur151/ROMP/tree/e9d52d020e74078838094b1d44427b63fa7ecbce)

The problem for me are not so much the version mistakes in `setup.py`.
Thats happening sometimes.
My problem is the chaos, that on one hand there are GitHub releases that doesn't point to **Simple ROMP** releases (*even* if it's called [simple_romp](https://github.com/Arthur151/ROMP/releases/tag/S1)) and
on the other hand there are no release notes on PyPi.
So in conclusions it's very hard for me to find the different releases.

Please help me a little bit with an overview 🙂 

Additional: How about the following workflow?
![Mindmap diagram: Commit -> Tag -> Releases](https://www.plantuml.com/plantuml/png/SoWkIImgoStCIybDBE3IKd3EpytDBE7IqbAmIR8hoiyjq2sBq0D26_qaEuMGn7GkBQ2KUsQ9HscIGb1gJcfYSIfKSJ6nga5Y1Pa52WM9oTc9wQb0YKIe35WgEJyl9H4c2TVba9gN0dKb0000 "Workflow mindmap")
If you like it easy, then you just need to create the commits and the tags by your self.
All other steps can i do for you with the suitable rights.
It's also no problem for me to create the necessary Continuous Deployment pipelines to automate it.

**Comment by Arthur151** [comment]
Thanks a lot, my friend!

There are too much to fully understand.
You mean that we need an overview of the function of different version. Am I right?
You recommand to use different tag to classify the romp / simple-romp.

**Comment by vivi90** [comment]
@Arthur151 
> You recommand to use different tag to classify the romp / simple-romp.

Exactly 🙂 
Then we create GitHub releases based on these tags.
This way it is also easy to create pip and conda releases.

**Comment by Arthur151** [comment]
@vivi90 
Thanks a lot, Vivien!
I am trying to make the version number right following your guidance. 

I just rectify the release version,
https://github.com/Arthur151/ROMP/releases

I will make the pip package version consistent with the release version.

But I might take a different way, like regarding this repo as a series works.
V0.x CenterHMR -> V1.x ROMP -> V2.x simple_romp (ROMP+BEV)  -> ....
This means the version number is for this repo, instead of the version of ROMP. This is also the reason why the version number of simple_romp pip is independent. But you are right, we should make them consistent. 
Of course, this won't stop. 
I will write the history about this repo in a separate page. 

Any comments are welcome~

**Comment by vivi90** [comment]
@Arthur151 
> [..] This means the version number is for this repo, instead of the version of ROMP 

hm, there is no need for an 'repository version'.
I mean, there is no problem if you are using different version tags (and releases) for different things (romp, simple-romp, and so on) in the same repository.
As long as it's clear, wich releases are related to what (new romp version or simple-romp or something else).

Maybe it might be easier to create forks of this repository.
So for example an fork for simple-romp.
If there are huge changes in romp (for example something like the introduction of BEV) you are able to merge it into the other repositories as well.
Any tiny changes that are ONLY related to the fork (for example simple-romp CLI bugfixes) then it stays at these forks.
That might also be easier for other contributors and users.

**Comment by vivi90** [comment]
@Arthur151 

> I just rectify the release version, https://github.com/Arthur151/ROMP/releases

Even if an version number might be wrong, it's better to do not change an already released version to avoid confusion. 🙂

**Comment by Arthur151** [comment]
Thanks, I see you point.
