### ISSUE TITLE
occluded 2d kps

### ISSUE THREAD

**Issue by ZhengdiYu** [Arthur151/ROMP#196]
Hi, I notice that the person center is computed from 'visible' keypoints, which I think refers to the body joints that we can literally see in the image, instead of the occluded joints.

But for some datasets, the annotation is made by machine, which means that even the 2 person is heavily occluded, there might be full set of 2d keypoints in the annotation file. In this case, the '`person_center`' of the person in the back will actually be on the first person's body:

![image](https://user-images.githubusercontent.com/63605407/162357955-e9504fc7-f024-4adf-840a-45426ca29912.png)

I think **ROMP has the ability to predict the shape from the center of 'visible body parts'**. And when the two center comes too close to each other, the **CAR mechanism** will be activated to push them away. **But there is no guarantee that the center will be pushed to a pixel that belongs to the occluded person**. In this case, is it really possible to infer 2 different people using `pixels` from the same person?

So, in the end, can we really use the massive machine annotated data for training, concerning the above situation ? Also, can we train ROMP with bounding box center? 

I'm not sure if this is technically feasible. But I think the center based representation is actually an alternative of bounding box, these single points might carry equal information as bboxes due to the receptive field, it's no longer a single point, but a point that can represent an area. So to some extend, this is feasible, am I understanding correctly ?

But actually, in my previous works of feature matching / pixel-wise descriptor learning. This is actually difficult problem, we would normally filter those occluded points as it would carry ambiguity. For example, we can't let a pixel of a man to be matched to a car. even if there is an implicit man's pixel behind the car

**Comment by Arthur151** [comment]
Hi, I see your points. 
But if you can visualize some samples in crowded datasets and their annotations, you will find that the cases which two people share the same center position is quite rare. Even in occlusion, they might have different height, meanwhile, they mush be at different 3D position. Therefore, in most occlusion cases, the 2D center position of two people in occlusion might be close, while can be handled by CAR. 
I don't think we have to guarantee that the center will be pushed to a pixel that belongs to the occluded person. Why should we guarantee that? We just need to garantee that they are discriminative enough to be learnt by our model. CNN has enough receptive field to see the entire body.
Training ROMP with bounding box annotation for better detection is performed during pretraining. We really need these datasets for stable detection in crowd.

**Comment by ZhengdiYu** [comment]
Yes, I see, that's what I mean. Thanks!

By the way, there is also a bug in cropping method https://github.com/Arthur151/ROMP/issues/175. You just accidently set leftTop, rightBottom = np.clip(box[0], 0, width), np.clip(box[1], 0, height), you might also have a quick look on that one if you have time. Bye for now~
