### ISSUE TITLE
smplx and smpl

### ISSUE THREAD

**Issue by ZhengdiYu** [Arthur151/ROMP#199]
Hi, I tried to take your predicted smpl **θ** to a smplx model while disabling the face and hand, but it seems that the output is not the same.

Is there a way to convert your pose to smplx?

**Comment by ihongxx** [comment]
Did you succeed convert pose to smplx?

**Comment by Arthur151** [comment]
@ihongxx 
You can freely transfer the parameters between SMPLs via 

https://github.com/vchoutas/smplx/tree/main/transfer_model
