### ISSUE TITLE
Question about "poses" in results file

### ISSUE THREAD

**Issue by hsauod** [Arthur151/ROMP#203]
Hi Arthur, great congratulations to your wonderful work! 

I saw you mentioned that, "poses" in the result file come from rotation, which is parent relatived.
But who's pelvis' parent?  Could you please give me any information that  how did you calculate pelvis's rotation( very first 3 elements of 72 )?

**Comment by Arthur151** [comment]
Hi, good question. Rotation at pelvis is global rotation of entire body, which could be regarded as the human 3D orientation. You can take the background/world coordinate as the parent of pelvis.

**Comment by hsauod** [comment]
> Hi, good question. Rotation at pelvis is global rotation of entire body, which could be regarded as the human 3D orientation. You can take the background/world coordinate as the parent of pelvis.

Thank you very much for your quick response, Arthur!
1, May I know how did you define the origin and axis orientation in that world coordinate?

2, I just want to make sure that the rest 69 elements (72 - 3 = 69 ) in "poses" are radians (theta*x, theta*y, theta*z), am I right?

**Comment by Arthur151** [comment]
These are just the pose parameters of SMPL model. Please refer to that/our paper for details.
1. It takes the pelvis as the origin. 
2. the rest 69 poses are 3-dim axis-angle rotation.

**Comment by hsauod** [comment]
> These are just the pose parameters of SMPL model. Please refer to that/our paper for details.
> 
> 1. It takes the pelvis as the origin.
> 2. the rest 69 poses are 3-dim axis-angle rotation.

Thank you very much for your clarifying , Arthur!
