### ISSUE TITLE
centered MPJPE  evaluation  

### ISSUE THREAD

**Issue by xiaochehe** [Arthur151/ROMP#207]
你好！您在论文中提到CMU panoptic上面的MPJPE是“The evaluation metric is MPJPE after centering the root joint” 我注意到也有其他们的工作提到“MPJPE is calculated after aligning the pose by the root joint" 这应该和您是一个意思吧？！另外，这里的操作是 ”所有的预测的关节点都减去   预测的root关节点相对于gt中root关节点的空间位移“的意思吗？还是需要其它更复杂的空间变化？谢谢！

**Comment by Arthur151** [comment]
您好，非常抱歉回复不及时。
MPJPE是将所有预测的结果依照各自的根节点位置进行配准，然后再算L2。
和您的描述的差别就是，所有的预测的关节点都减去预测的root关节点的空间位移。这样才能实现统一配准。
