### ISSUE TITLE
BEV完整代码

### ISSUE THREAD

**Issue by 3013218123** [Arthur151/ROMP#208]
您好
从ROMP开始就一直参考您的工作了，受益匪浅，万分感谢。
您的新作BEV在人群深度上的效果看起来令人惊叹，我们想要用它在自己的数据集上进行微调，请问完整的BEV代码大致在几月份可以发布呢？

**Comment by Arthur151** [comment]
浩哥您好，
非常感谢您的积极评价！
训练及评测代码会在CVPR召开前开源，即六月份。

**Comment by 3013218123** [comment]
收到 了解了 再次感谢

**Comment by Arthur151** [comment]
目前还在整理代码，不好说几号能整理完，会在CVPR前放出的。感谢关注。

**Comment by Arthur151** [comment]
@liangwx @3013218123 
BEV代码已开源。
