### ISSUE TITLE
关于复现论文中的结果

### ISSUE THREAD

**Issue by QiAnBozZ** [Arthur151/ROMP#209]
首先感谢您优秀的工作！

我在根据docs/evaluation.md所写的尝试复现论文中的结果时，发现测试的指标并没有达到论文中的水平，想请您看一下是不是哪里出了问题。

CUDA_VISIBLE_DEVICES=0 python romp/lib/evaluation/collect_3DPW_results.py --configs_yml=configs/eval_3dpw_challenge.yml
python -m romp.test --configs_yml=configs/eval_3dpw_test.yml
python -m romp.test --configs_yml=configs/eval_3dpw_test_resnet.yml
python -m romp.test --configs_yml=configs/eval_3dpw_test_ft.yml
python -m romp.test --configs_yml=configs/eval_3dpw_test_resnet_ft.yml

这几行命令分别对应的是不是论文中Tab.1的最后一行、Tab.2的倒数第一、二行和Tab.3的倒数第一、三行？

运行这些代码我得到的结果如下：

首先是3DPW_challenge:

MPJPE: 182.35274653001787
MPJPE_PA: 166.38965381899567
PCK: 26.78395448300638
AUC: 0.45113494167624285
MPJAE: 63.859989172498125
MPJAE_PA: 62.683403766225

剩下的四行命令结果分别为：

MPJPE                        PAMPJPE                        config
87.25                         53.33                          eval_3dpw_test.yml
94.91                         56.49                          eval_3dpw_test_resnet.yml
76.74                         47.37                          eval_3dpw_test_ft.yml
85.16                         52.10                          eval_3dpw_test_resnet_ft.yml

**Comment by QiAnBozZ** [comment]
我发现ResNet-50的误差都比较大，而HRNet的Protocol 2有相对较小的差距，Protocol 3则是论文的水平。
ResNet-50的模型是没有使用额外数据集进行训练的吗？

**Comment by Arthur151** [comment]
Please note that in [evaluation](https://github.com/Arthur151/ROMP/blob/master/docs/evaluation.md) page, regarding evaluation on 3DPW_challenge.
This evaluation has been implemented in our released version 1.0, while the latest version 1.1 still need to debug.
https://github.com/Arthur151/ROMP/releases/tag/v1.0

关于ResNet-50，您可能需要跑Resnet训练的时候得到的测试结果是准确的，有的时候pytorch的evaluation 状态不知道为什么转换不过去，导致resnet结果异常，训练时候顺便测试，可以得到论文中结果。

**Comment by QiAnBozZ** [comment]
> Please note that in [evaluation](https://github.com/Arthur151/ROMP/blob/master/docs/evaluation.md) page, regarding evaluation on 3DPW_challenge. This evaluation has been implemented in our released version 1.0, while the latest version 1.1 still need to debug. https://github.com/Arthur151/ROMP/releases/tag/v1.0
> 
> 关于ResNet-50，您可能需要跑Resnet训练的时候得到的测试结果是准确的，有的时候pytorch的evaluation 状态不知道为什么转换不过去，导致resnet结果异常，训练时候顺便测试，可以得到论文中结果。

我在v1.0版本的代码上得到了论文中结果，非常感谢您的耐心解答！

但是我还有一点想要求教，论文中谈到了在3DPW上测试时使用了三种不同的协议，表一所说的“without using any ground truth during inference”，是不是说在第二个和第三个Protocol下，在采样param_maps时使用了ground truth中的center进行采样，而在第一个Protocol下，则没有使用任何gt信息？

**Comment by Arthur151** [comment]
@QiAnBozZ 
抱歉漏了您的这个issue。。
关于您的几个问题：
1.所有测试中ROMP都没有用GT信息。
2.mode不同，只是输出结果后和GT匹配方式的区别而已。我们并没有用GT来进行采样。训练过程也没有用GT来进行采样，如果您详细看过代码，应该可以发现，ROMP在训练过程中，只是将自己估计的结果和GT进行匹配，毕竟只有匹配过才能进行监督。evaluation也需要同样的基于center匹配过程才能进行评测。

**Comment by QiAnBozZ** [comment]
> @QiAnBozZ 抱歉漏了您的这个issue。。 关于您的几个问题： 1.所有测试中ROMP都没有用GT信息。 2.mode不同，只是输出结果后和GT匹配方式的区别而已。我们并没有用GT来进行采样。训练过程也没有用GT来进行采样，如果您详细看过代码，应该可以发现，ROMP在训练过程中，只是将自己估计的结果和GT进行匹配，毕竟只有匹配过才能进行监督。evaluation也需要同样的基于center匹配过程才能进行评测。

好的，谢谢您的解答，我再自己看一下evaluation的代码学习一下。
