### ISSUE TITLE
Joints in BEV

### ISSUE THREAD

**Issue by HuiliCui** [Arthur151/ROMP#211]
When viewing the NPZ file after running BEV，I have some questions about joints
1. Is the joints relative to the root? If  I  want to get the joints of the camera coordinate system,  only need to add cam_trans to the joints?
2. The shape of joints is [N,71,3], what is the sequence of the joints?

**Comment by Arthur151** [comment]
1. Yes, you are right.
2. About the joint defination, here is the code of generating them:
https://github.com/Arthur151/ROMP/blob/e30b7d17f13089fa9fa114df494192e31b0f43ed/simple_romp/romp/smpl.py#L29
The 71 joints are previous 54 joint + 17 h36m joints

previous 54 joint = 24+30:

SMPL_24 = {
    'Pelvis_SMPL':0, 'L_Hip_SMPL':1, 'R_Hip_SMPL':2, 'Spine_SMPL': 3, 'L_Knee':4, 'R_Knee':5, 'Thorax_SMPL': 6, 'L_Ankle':7, 'R_Ankle':8,'Thorax_up_SMPL':9, \
    'L_Toe_SMPL':10, 'R_Toe_SMPL':11, 'Neck': 12, 'L_Collar':13, 'R_Collar':14, 'Jaw':15, 'L_Shoulder':16, 'R_Shoulder':17,\
    'L_Elbow':18, 'R_Elbow':19, 'L_Wrist': 20, 'R_Wrist': 21, 'L_Hand':22, 'R_Hand':23
    }

SMPL_EXTRA_30 = {
    'Nose':24, 'R_Eye':25, 'L_Eye':26, 'R_Ear': 27, 'L_Ear':28, \
    'L_BigToe':29, 'L_SmallToe': 30, 'L_Heel':31, 'R_BigToe':32,'R_SmallToe':33, 'R_Heel':34, \
    'L_Hand_thumb':35, 'L_Hand_index': 36, 'L_Hand_middle':37, 'L_Hand_ring':38, 'L_Hand_pinky':39, \
    'R_Hand_thumb':40, 'R_Hand_index':41,'R_Hand_middle':42, 'R_Hand_ring':43, 'R_Hand_pinky': 44, \
    'R_Hip': 45, 'L_Hip':46, 'Neck_LSP':47, 'Head_top':48, 'Pelvis':49, 'Thorax_MPII':50, \
    'Spine_H36M':51, 'Jaw_H36M':52, 'Head':53
    }

h36m 17 joints are just used during evaluation. I am not sure what are their joint names. I regress them for fair comparison with previous methods. 

Thanks a lot for your reminds! I have added this to 
https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#joints-in-output-npz-file
