### ISSUE TITLE
test

### ISSUE THREAD

**Issue by guoees** [Arthur151/ROMP#212]
Hello, Excuse me, I ran into this problem while testing. I'm running into missing parameters and no data being generated while testing.
![image](https://user-images.githubusercontent.com/96688784/164445093-98469a2a-9ffe-42fa-b907-ceb0b2e215da.png)

**Comment by Arthur151** [comment]
Please use simple-romp for testing. It contains both ROMP and our new BEFV:
https://github.com/Arthur151/ROMP/tree/master/simple_romp
We also provide tools to convert the model trained by yourself to the format supported by simple-romp.

Beside, the missed parameters are fine.

**Comment by guoees** [comment]
First of all, thanks for your reply. I downloaded the latest, I don't know how to test it, I have converted the .pkl file to a .pth file.
I tried to replace the previous .pkl file in .romp with the new one, but the output of calling the camera is a bunch of garbled characters.
![image](https://user-images.githubusercontent.com/96688784/164461005-c6813e21-230c-4abe-8352-e80c7ab724b1.png)

**Comment by Arthur151** [comment]
What do you mean by calling the camera? romp -m webcam --show?

**Comment by guoees** [comment]
Yes.

**Comment by Arthur151** [comment]
Could you print the parameter dict key of your .romp/ROMP.pkl?
Could you provide the full output?

**Comment by guoees** [comment]
I print it out.
[1.txt](https://github.com/Arthur151/ROMP/files/8536322/1.txt)

**Comment by Arthur151** [comment]
@guoees  where is out.1.txt?

**Comment by guoees** [comment]
I'm so sorry, I may have misunderstood what you meant. The last one is printed by myself through the .pkl file trained by COCO2014.
In this .romp file, I just replaced the original ROMP.pkl file, and the rest is unchanged.
![image](https://user-images.githubusercontent.com/96688784/164586535-2fa1b8e2-50c4-4a24-b3e0-39c2a14db487.png)
The following is the output of romp -m webcam --show.
[romp --mode=webcam --show .txt](https://github.com/Arthur151/ROMP/files/8536475/romp.--mode.webcam.--show.txt)

**Comment by Arthur151** [comment]
I know why.
Please convert the model to simple-romp format follow this instruction:
https://github.com/Arthur151/ROMP/tree/master/simple_romp#tools
```
python tools/convert_checkpoints.py ROMP.pkl ROMP.pkl
```
Then put the converted model to .romp/ROMP.pkl

**Comment by guoees** [comment]
Thank you very much for your help, the problem has been solved.
