### ISSUE TITLE
How to use ROMP to achieve  motion capture with webcam

### ISSUE THREAD

**Issue by QiFuChina** [Arthur151/ROMP#220]
Here is the windows 10 platform, I see a video link on readme file shows ROMP can be used to achieve multi-person 3D mesh recovery in real time with webcam but I can't(or miss) find this part of tutorial.
Does someone can tell me where is it or where I can find information to do that?

**Comment by Arthur151** [comment]
https://github.com/Arthur151/ROMP/blob/7b4734270672e602f4fc5659d37479478e72b78b/simple_romp/README.md

here is it.

**Comment by QiFuChina** [comment]
> https://github.com/Arthur151/ROMP/blob/7b4734270672e602f4fc5659d37479478e72b78b/simple_romp/README.md
> 
> here is it.

Thank you
I also want to know how to get this function, I tried to run command `romp --mode=webcam --show ` but the terminal updates informatino with 'no human detected ' and doesn't open webcam.
Did I miss something?
![pic](https://user-images.githubusercontent.com/24989456/165871316-ffd0c122-67c6-4a71-99aa-a98158781062.png)

**Comment by Arthur151** [comment]
Could you provide the log what the command print?

About that, it is a function in old version, introduced at https://github.com/Arthur151/ROMP/blob/master/docs/old_readme.md

To install the old verison, https://github.com/Arthur151/ROMP/blob/master/docs/installation.md

**Comment by QiFuChina** [comment]
> Could you provide the log what the command print?
> 
> About that, it is a function in old version, introduced at https://github.com/Arthur151/ROMP/blob/master/docs/old_readme.md
> 
> To install the old verison, https://github.com/Arthur151/ROMP/blob/master/docs/installation.md

win10 安装老版本并在terminal下执行`python -u -m romp.predict.webcam --configs_yml='configs\webcam.yml'`时，返回结果为找不到对应的文件
` [Errno 2] No such file or directory: "E:\\ResourCode\\Romp-oldversion\\ROMP\\'configs\\webcam.yml'"`
是我遗漏了什么么？
完整log如下
`(romp) E:\ResourCode\Romp-oldversion\ROMP>python -u -m romp.predict.webcam --configs_yml='configs\webcam.yml'
yaml_timestamp  E:\ResourCode\Romp-oldversion\ROMP\rompactive_configs\active_context_2022-04-29_17_05_35.yaml
Traceback (most recent call last):
  File "C:\Users\xhtkj\miniconda3\envs\romp\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\xhtkj\miniconda3\envs\romp\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\predict\webcam.py", line 7, in <module>
    from .base_predictor import *
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\predict\base_predictor.py", line 1, in <module>
    from ..base import *
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\base.py", line 13, in <module>
    import config
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\lib\config.py", line 219, in <module>
    class ConfigContext(object):
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\lib\config.py", line 226, in ConfigContext
    parsed_args = parse_args(sys.argv[1:])
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\lib\config.py", line 187, in parse_args
    with open(config_yml_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: "E:\\ResourCode\\Romp-oldversion\\ROMP\\'configs\\webcam.yml'"`

**Comment by QiFuChina** [comment]
尝试去掉引号`python -u -m romp.predict.webcam --configs_yml=configs\webcam.yml`，输出log也是类似于找不到文件
(romp) E:\ResourCode\Romp-oldversion\ROMP>python -u -m romp.predict.webcam --configs_yml=configs\webcam.yml
yaml_timestamp  E:\ResourCode\Romp-oldversion\ROMP\rompactive_configs\active_context_2022-04-29_17_30_43.yaml
Traceback (most recent call last):
  File "C:\Users\xhtkj\miniconda3\envs\romp\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\xhtkj\miniconda3\envs\romp\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\predict\webcam.py", line 174, in <module>
    main()
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\predict\webcam.py", line 164, in main
    with ConfigContext(parse_args(sys.argv[1:])) as args_set:
  File "E:\ResourCode\Romp-oldversion\ROMP\romp\lib\config.py", line 235, in __enter__
    with open(self.yaml_filename, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\ResourCode\\Romp-oldversion\\ROMP\\rompactive_configs\\active_context_2022-04-29_17_30_43.yaml'

**Comment by Arthur151** [comment]
还是Windows的路径问题，这里的
https://github.com/Arthur151/ROMP/blob/653a0c9de13c7e242bc304147ae6559d1c6ff283/romp/lib/config.py#L18
https://github.com/Arthur151/ROMP/blob/653a0c9de13c7e242bc304147ae6559d1c6ff283/romp/lib/config.py#L13
project_dir不对

**Comment by vivi90** [comment]
@QiFuChina Does the issue still exists? 🙂

**Comment by QiFuChina** [comment]
> @QiFuChina Does the issue still exists? 🙂

Actually I'm working with other things recently and leave this so long that not finished, but I will close this
