### ISSUE TITLE
convert_fbx.py does not work for image & missing npz file for video

### ISSUE THREAD

**Issue by XXZhe** [Arthur151/ROMP#228]
I tried to convert the NPZ file of a single frame into FBX but it reports the error "IndexError: too many indices for tensor of dimension 1".
Also, I couldn't find the NPZ file for the exported video, which used to be exported along with the resulting video.

It will be appreciated if you can provide a method to convert the image NPZ file into FBX.

**Comment by Arthur151** [comment]
To achieve this feature, you just need to edit a few lines of code at
https://github.com/Arthur151/ROMP/blob/653a0c9de13c7e242bc304147ae6559d1c6ff283/romp/exports/convert_fbx.py#L245
You will see that for image npz, you can obtain only one frame results, therefore, one dimension as mentioned in error.
You can just change this part of code to 
```
        frame_nums = 1
        poses, trans = np.zeros((len(frame_nums), 72)), np.zeros((len(frame_nums), 3))
        for inds, frame_id in enumerate(frame_nums):
            poses[inds] = data[subject_ids]['poses']
            trans[inds] = data[subject_ids]['cam_trans']
```
Something likes that. It is quite simple, please try to change it by youself.

**Comment by XXZhe** [comment]
Thanks for the reply, the problem has been solved.
