### ISSUE TITLE
关于SMPL模型使用的问题

### ISSUE THREAD

**Issue by qqq1357962** [Arthur151/ROMP#229]
![image](https://user-images.githubusercontent.com/58675927/166923864-3805abdf-8a9b-45c0-9b82-663b581310cc.png)
您好，我注意到有已经开发好的smpl工具包，叫smplpytorch，不知您有没有注意过这个包，我把您代码中的smpl_wrapper抽取出来了，尝试着对比这两者的区别，我发现打出来的效果是使用您的wrapper打出来的joint(上图标记“smpl2”附近的打印)和smplpytorch这个包打出来的joint(标记“smpl3”附近的打印)是不一样的，我好奇，如果您注意到过smplpytorch这个包，为什么不直接拿来用，要自己实现一个smpl？是否做了某些优化？如果没有注意到过的话那打扰了，我自己慢慢对比下为什么不同吧……
(上图中的wrapper,smpl_layer初始化如下)
from smplpytorch.pytorch.smpl_layer import SMPL_Layer
smpl_layer = SMPL_Layer(
    gender='female',
    model_root=smpl_path)
from smpl_wrapper import SMPLWrapper
wrapper = SMPLWrapper()

**Comment by qqq1357962** [comment]
忘了交代了，我把wrapperd的forward方法改成这样了：
def forward(self, params_dict):#, meta_data):
        smpl_outs = self.smpl_model(**params_dict, return_verts=True, return_full_pose=True)
        outputs={}
        outputs["verts"] = smpl_outs["verts"]
        outputs["joints_smpl24"] = smpl_outs["joints_smpl24"]
        return outputs

**Comment by Arthur151** [comment]
我的初衷是整理一版简洁，易懂的版本出来，去掉了一切非必要的操作。代码看上去更清晰。同时，使用自己的代码，可以让simple-romp更稳定而统一，避免因其他库版本更新，接口函数变化而引起的不必要的bug。
我始终觉得，人家的再好也不如自己的。
我的版本是做了一些加速的，可以导出成onnx，快速计算。

**Comment by qqq1357962** [comment]
好的，非常感谢！
