### ISSUE TITLE
smpl 模型参数问题

### ISSUE THREAD

**Issue by YongtaoGe** [Arthur151/ROMP#238]
请教作者 我发现本仓库提供的smpl_packed_info里面的参数与smpl网站上"basicModel_neutral_lbs_10_207_0_v1.0.0.pkl"不太一致，这是什么原因导致的呢？这对结果有影响吗

**Comment by Arthur151** [comment]
抱歉，漏掉了这个issue了，请问有什么不同呢？我只是重新整理成更加方便加载使用的形式了

**Comment by YongtaoGe** [comment]
作者你好 我比较了一下 smpl_packed_info提供的参数好像是和 basicModel_female_lbs_10_207_0_v1.0.0.pkl 一致的，也就是用的是女性的smpl模型？

**Comment by Arthur151** [comment]
感谢提醒，我去check一下
