### ISSUE TITLE
请问为什么使用FoVPerspectiveCameras?

### ISSUE THREAD

**Issue by liangwx** [Arthur151/ROMP#239]
请问为什么使用FoVPerspectiveCameras而不是和estimate_translation里面一样的"透视投影相机模型",比如PerspectiveCameras.
训练和推理阶段使用不同的相机模型不会影响模型结果的正确性吗?

**Comment by Arthur151** [comment]
Good one @liangwx
FoVPerspectiveCameras只是用于渲染，并不涉及到关键点的2D投影计算。所以不会影响评测

**Comment by MayuOshima** [comment]
你好，请问FoVPerspectiveCameras和PerspectiveCameras有什么区别吗？我看pytorch3d的docs里写的，这个FoVPerspectiveCameras就是OpenGLPerspectiveCameras，那应该和PerspectiveCameras是一样的？看了下参数的计算也没看出来区别，不懂为什么FoVPerspectiveCameras如果涉及里关键点的2D投影计算会影响评测。

**Comment by Arthur151** [comment]
是的，没错，FoVPerspectiveCameras仅仅只是用来可视化，不会影响评测德。

**Comment by MayuOshima** [comment]
> 是的，没错，FoVPerspectiveCameras仅仅只是用来可视化，不会影响评测德。

那就是说，如果使用FoVPerspectiveCameras来投影关键点，就会影响测评了是吧？
可是为什么会影响呢？如果说FoVPerspectiveCameras其实就是PerspectiveCameras的话，应该不影响才对呀

**Comment by Arthur151** [comment]
没有这个意思，FoVPerspectiveCameras仅仅是pyrender/pytorch3D内部用于将3D mesh渲染到图像平面的相机模型，不会涉及投影关键点的计算过程。至于FoVPerspectiveCameras和PerspectiveCameras是不是一样的，并没有研究过，如果您有研究，确定他们是一样的，那么感谢您的分享。

**Comment by MayuOshima** [comment]
> 没有这个意思，FoVPerspectiveCameras仅仅是pyrender/pytorch3D内部用于将3D mesh渲染到图像平面的相机模型，不会涉及投影关键点的计算过程。至于FoVPerspectiveCameras和PerspectiveCameras是不是一样的，并没有研究过，如果您有研究，确定他们是一样的，那么感谢您的分享。

哦哦原来如此！我明白您的意思了！
谢谢您的热情回复！
