### ISSUE TITLE
how to get a video's .npz file?

### ISSUE THREAD

**Issue by 7568** [Arthur151/ROMP#240]
Hi, thanks for your great work.  I want to get a .npz file by a video , when I use command `bev -m video -i a.mp4 -o ../outputs/result.mp4  --GPU=6  --renderer=pyrender` , the result is each frame's .npz file . I want to get one .npz file of a video , how can i do? I have try a lot of params like '--calc_smpl , --render_mesh , --smpl_path' , not the result is not i want.

**Comment by Arthur151** [comment]
Great suggestion. Sorry, I missed this feature in simple-romp. 
I will add this feature to the code as soon as possible. I will update this issue then.

**Comment by Arthur151** [comment]
Update:
I just submited a new commit to this repo. to support saving video results as `BEV_results/video_results.npz`.

To use it now, please clone the latest ROMP repo. and install simple-romp via
```
pip uninstall simple-romp
cd ROMP/simple-romp
python setup.py install
```

The formal version of simple-romp release will be made later. I still need to test the other functions. 
Best,
Yu

**Comment by 7568** [comment]
thank you very much.

**Comment by Arthur151** [comment]
@xjchao7
I have fixed it.
Please upgrade to the newest version via

pip install --upgrade simple-romp
I will keep watching and fix all related issues.
So please let me know if any bugs occured.
