### ISSUE TITLE
How to download the bev.pth?

### ISSUE THREAD

**Issue by xjchao7** [Arthur151/ROMP#243]
Thank you for your perfect work.  I have a question when I try bev command. It said " Failure in downloading the BEV model, please download it by youself from https://github.com/Arthur151/ROMP/releases/download/S1/BEV.pth". But I cannot find this BEV.pth.

Could you please the download link for bev inference model?

Thank you very much.

**Comment by Arthur151** [comment]
Thanks a lot for this valuable bug report!!!
I am fixing it!

**Comment by Arthur151** [comment]
@xjchao7 
I have fix it.
Please upgrade to the newest version via
```
pip install --upgrade simple-romp
```
I will keep watching and fix all related issues.
So please let me know if any bugs occured.

**Comment by Arthur151** [comment]
I am waiting here~

**Comment by xjchao7** [comment]
> 

Thank you so much for your prompt reply ~It works well.

**Comment by Arthur151** [comment]
Got it. 
Thanks for your report! 
Best,
Yu
