### ISSUE TITLE
About pretrained backbone

### ISSUE THREAD

**Issue by jhkim0759** [Arthur151/ROMP#244]
You said you trained the backbone(HRNet, ResNet) with detection and 2dpose datasets on here(https://github.com/Arthur151/ROMP/issues/121#issuecomment-1026449589)

Then could you tell me exactly which dataset you used?

Thank you

**Comment by Arthur151** [comment]
Sure, datasets for pre-training:
CrowdHuman, coco, mpii, lsp, AI-Challenger, crowdpose.

**Comment by Arthur151** [comment]
Please note that, about backbone pretraining, one can use the pre-trained model of Higher-HRNet-32.
It would be very helpful for faster converge.

**Comment by jhkim0759** [comment]
I will take note.
Thank you for your information
