### ISSUE TITLE
CMU Panoptic

### ISSUE THREAD

**Issue by ZhengdiYu** [Arthur151/ROMP#249]
https://github.com/Arthur151/ROMP/blob/feaeb38d6a2809eac1979fed568d75c2f75eab2c/romp/lib/dataset/cmu_panoptic_eval.py#L56

Hi, I noticed that there is something like this. Why do we need to scale the kp2d like this?  And how did you generate the annotation for CMU?

**Comment by Arthur151** [comment]
Hi, ZhengdiYu,

For a fair comparison with previous methods, we directly use the evaluation data & protocol from previous method, CRMH.
https://github.com/JiangWenPL/multiperson
Their input image is of size, 832 x 512. Therefore, to convert it back to original image, we need to scale it like that.

**Comment by ZhengdiYu** [comment]
Thanks. So they actually use a downsampled image for training and eval? 

But I think that during pre-processing, all the the kp2ds will be rescale to [-1, 1]. Is this scaling in the dataloader still meaningful?

**Comment by Arthur151** [comment]
These data is just used for evaluation, no data from CMUP is used for training. 

We need to make them correct. Correct scale consistent with original image is better.

**Comment by ZhengdiYu** [comment]
Okay, I'm trying to play with the webcam now. But it show an animation character in the window. Can I use the default white mesh instead? Just like the mesh overlay on the image.

**Comment by Arthur151** [comment]
Please use the webcam of simple_rompGet Outlook for Android
