### ISSUE TITLE
question about the mixed_dataset.py

### ISSUE THREAD

**Issue by xjchao7** [Arthur151/ROMP#252]
Hi~Thank you for your work.

Recently, When I run the trainning code by using only two datasets (dataset: 'mpii,crowdpose'), I met a problem as following:
/ROMP-master/romp/lib/models/../utils/../dataset/mixed_dataset.py", line 73, in __getitem__
    upper_bound = self.partition[dataset_id]
IndexError: index 2 is out of bounds for axis 0 with size 2

And When I print the dataset_id, it shows 1 or 2. Could you please help me with this error?

Thank you very much!

**Comment by Arthur151** [comment]
https://github.com/Arthur151/ROMP/blob/master/docs/train.md#training-guidance

**Comment by xjchao7** [comment]
> https://github.com/Arthur151/ROMP/blob/master/docs/train.md#training-guidance

Thank you. I found out that this was indeed due to my dataset being set up incorrectly and I should have followed the steps in the link.
