### ISSUE TITLE
About heads

### ISSUE THREAD

**Issue by wangyang357** [Arthur151/ROMP#253]
Hello author！I'm learning romp，it's a great work！
I'm curious about why three heads use the same structure，can you give me a hint？

**Comment by Arthur151** [comment]
Hi, @wangyang357 
Could you provide some specific reasons for why we should design different structure for each head?
The design of ROMP follow the principle of Occam's razer.

**Comment by wangyang357** [comment]
我觉得您说的很有道理，但有一点我还想跟您请教一下，为什么从trans_block分开三头，而不是在结尾1×1卷积那里再分成三头？请您赐教，感谢！

**Comment by Arthur151** [comment]
因为不同的任务需要单独的特征提取，需要一些层来学task-specific的特征。看最近的论文的模型设计都可以发现这点，就是需要提前进行任务解耦合。

**Comment by wangyang357** [comment]
嗯嗯！明白。根据您说的，我比较好奇为什么三个头都是同一套结构，却能应用在三种不同任务中？或者说为什么相同结构在不同任务需求下都有效果？

**Comment by Arthur151** [comment]
结构相同，学到的参数是不同的。为什么非要设计不同的结构呢？
