### ISSUE TITLE
Issue while exporting into .fbx

### ISSUE THREAD

**Issue by ujjawalcse** [Arthur151/ROMP#254]
Hey @Arthur151 , Thanks for this amazing work.
I ran` bev` on the given demo videos used in colab, Generated the `video_results.npz`  using the below command.

`!bev -m video -i /content/ROMP/demo/videos/sample_video.mp4 -o /content/drive/MyDrive/3DAI/ROMP/BEV_Results
`
Then I'm trying to export it to an fbx animation file but getting the below error, 
```
python convert2fbx.py --input output_bev/video_results.npz --output output_bev/video_results.fbx --gender=male
Input path: output_bev/video_results.npz
Output path: output_bev/video_results.fbx
Processing: /home/ujjawal/my_work/motion_tracking3D/ROMP/output_bev/video_results.npz
Missing tracking IDs in results. Using the first pose results for animation.
To get the tracking IDs, please use temporal optimization during inference.
Traceback (most recent call last):
  File "convert2fbx.py", line 418, in <module>
    subject_id=args.subject_id
  File "convert2fbx.py", line 245, in process_poses
    poses[inds] = frame_results[frame_name]['poses'][0]
KeyError: 'poses'
Segmentation fault (core dumped)
```
Can you point it down what am i missing?

**Comment by ujjawalcse** [comment]
Thanks @Arthur151 for your quick response.
Solved the above issue and get the results too for one demo video.
But I'm getting error for the other demo video after processing 239 frames.

`!bev -m video -t -i /content/ROMP/demo/videos/sample_video.mp4 -o /content/drive/MyDrive/3DAI/ROMP/BEV_Output/sample_video`

```
[------------------------------------    ] 235/257 ( 91%)  22 to go 
BEV 'forward' executed in 0.1518s, FPS 6.6
[------------------------------------    ] 236/257 ( 91%)  21 to go 
BEV 'forward' executed in 0.1529s, FPS 6.5
[------------------------------------    ] 237/257 ( 92%)  20 to go 
BEV 'forward' executed in 0.1717s, FPS 5.8
[-------------------------------------   ] 238/257 ( 92%)  19 to go 
BEV 'forward' executed in 0.1600s, FPS 6.3
[-------------------------------------   ] 239/257 ( 92%)  18 to go 
BEV 'forward' executed in 0.1673s, FPS 6.0
[-------------------------------------   ] 240/257 ( 93%)  17 to go 
Traceback (most recent call last):
  File "/usr/local/bin/bev", line 33, in <module>
    sys.exit(load_entry_point('simple-romp==1.0.4', 'console_scripts', 'bev')())
  File "/usr/local/lib/python3.7/dist-packages/simple_romp-1.0.4-py3.7-linux-x86_64.egg/bev/main.py", line 299, in main
    outputs = bev(image)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/simple_romp-1.0.4-py3.7-linux-x86_64.egg/romp/utils.py", line 728, in wrap_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/simple_romp-1.0.4-py3.7-linux-x86_64.egg/bev/main.py", line 147, in forward
    outputs = rendering_romp_bev_results(self.renderer, outputs, image, rendering_cfgs)
  File "/usr/local/lib/python3.7/dist-packages/simple_romp-1.0.4-py3.7-linux-x86_64.egg/vis_human/main.py", line 33, in rendering_romp_bev_results
    mesh_colors = mesh_color_trackID(outputs['track_ids'])
  File "/usr/local/lib/python3.7/dist-packages/simple_romp-1.0.4-py3.7-linux-x86_64.egg/vis_human/vis_utils.py", line 241, in mesh_color_trackID
    return np.array([color_table[tid % len(color_table)] for tid in track_ids])
TypeError: 'numpy.int32' object is not iterable
```
Can you figure it out why it's like that?

**Comment by Arthur151** [comment]
Thanks a lot for reporting this bug!

I have update a new version of simple-romp to fix this.
To use the latest version,
```
pip install --upgrade simple-romp
```

Best,
Yu

**Comment by ujjawalcse** [comment]
Hey @Arthur151 ,
Thanks, It's working now.

Also, I tried on my local PC having following configuration,
```
Ubuntu 18.04
RTX 2070 Super
torch 1.5.1+cu101
cuda 10.1
python 3.7
```

Fixed two issue that i got while running on the above mentioned configurations.
1. `python3.7/site-packages/simple_romp-1.0.5-py3.7-linux-x86_64.egg/bev/post_parser.py`  line no. 64 is modified from 
    `center_zyxs = torch.stack([topk_zs[mask], topk_ys[mask], topk_xs[mask]]).permute((1,0)).long()`
to
    `center_zyxs = torch.stack([topk_zs[mask].long(), topk_ys[mask].long(), topk_xs[mask].long()]).permute((1,0)).long()
`

2. `python3.7/site-packages/simple_romp-1.0.5-py3.7-linux-x86_64.egg/bev/model.py`    line no. 101 is modified from
    `center = torch.clip(center, 1, size-1).long()`
to
   `center = torch.clamp(center, 1, size-1).long()`

**Comment by Arthur151** [comment]
Thanks for your help, Ujjawal Kumar Singh! 
I have modified these as you suggest and mentioned your contribution in commit. 
https://github.com/Arthur151/ROMP/commit/5a8fd850dfab8d9e7cebfb4ecd7a90d46581d7b6

**Comment by ujjawalcse** [comment]
Thanks @Arthur151 ,
Closing the issue now.
