### ISSUE TITLE
master分支下的romp是否支持训练

### ISSUE THREAD

**Issue by xiaoxin-Crayon** [Arthur151/ROMP#258]
我发现您关于训练的文档里写的是针对ROMPV1.1和ROMPv1.0版本的，请问现在的master分支支持训练嘛
![图片](https://user-images.githubusercontent.com/75933370/171078747-77cd3cb6-366a-4584-9795-dce2ca4c2c12.png)

**Comment by Arthur151** [comment]
是的，支持的。
