### ISSUE TITLE
[FAQ] Difference between "romp" and "bev"

### ISSUE THREAD

**Issue by vivi90** [Arthur151/ROMP#259]
There should be at least in the [quick start guide](https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md) an short summary of the differences betwen `bev` and `romp` according to the described commands.

**Comment by Arthur151** [comment]
Sorry for the late reply. I got catched by a deadline, tired face... 
I add the describtion about the difference now.

**Comment by vivi90** [comment]
@Arthur151 No problem, thank you 🙂
