### ISSUE TITLE
smpl_thetas 表示的意思

### ISSUE THREAD

**Issue by 7568** [Arthur151/ROMP#260]
你好大佬，谢谢你的研究，输出的结果中，smpl_thetas 是表示每个关节点的坐标吗？如果是坐标，为什么我不能在blender中，使用24个球拼出一个人形的动作。

**Comment by Arthur151** [comment]
不知关节点的坐标，坐标值放在joints里。
smpl_thetas是24个SMPL关节点的3D旋转角(3-dim axis-angle形式)

**Comment by 7568** [comment]
谢谢您的回复，那理论上我是可以通过joints 控制关节的坐标，模拟出动作的吗？

**Comment by Arthur151** [comment]
是的，这个功能已经有了。

**Comment by 7568** [comment]
非常感谢，能给我说说smpl_thetas和joints 的关系吗？还有就是本项目中使用joints 控制关节的坐标的文件在哪里？再次感谢！！！

**Comment by Arthur151** [comment]
建议您可以学习一下SMPL模型相关的知识，就是如何用姿态参数控制人体运动，以及如何回归出关节点坐标。
相关的代码，我整理了一个容易理解的简化版本，您试着跑一下，就很容易能理解。

https://github.com/Arthur151/ROMP/blob/master/simple_romp/romp/smpl.py
