### ISSUE TITLE
关于数据集标签的一些问题

### ISSUE THREAD

**Issue by QiAnBozZ** [Arthur151/ROMP#263]
关于数据集的标签，我有一些问题。
1. coco数据集的pose和shape参数是如何得到的？我在另一篇issue里看到h36m的数据集是从[Mosh++](https://github.com/nghorbani/moshpp) and [soma](https://github.com/nghorbani/soma))的工作得到的，其他的数据集的标注也是这样得到的吗？
2. 我看到各个数据集返回的标签中，kp2ds是标注文件中直接读取的2d坐标，然后映射到SMPL_ALL_54上得到的(54,3)的坐标，其中有的关节坐标因为标注没有所以是(-2,-2)；而kp3ds则是由smpl参数回归得到的54个关节点的3D坐标。请问这样做有什么深意吗？为什么不都读取标注中的坐标，或者都用SMPL来回归呢？

**Comment by Arthur151** [comment]
1.coco等2D pose数据集的smpl标注来自于EFT
https://github.com/facebookresearch/eft

2.2D pose数据集的smpl标注，只是伪标注，用它回归的joints投影到图像中，并没有数据集原始的2Dpose那么准。

**Comment by QiAnBozZ** [comment]
好的，十分感谢！

**Comment by QiAnBozZ** [comment]
还有一个问题需要请教您一下，每个数据集的get_image_info()返回的vmask_2d和vmask_3d分别代表什么含义呢？
