### ISSUE TITLE
Regarding ROMP on AGORA dataset

### ISSUE THREAD

**Issue by ichbill** [Arthur151/ROMP#264]
Hi, thank you for your excellent work!

I have several questions regarding the ROMP experiments details on the AGORA dataset, and hope you can help me. 

1. AGORA dataset provides detailed annotations, such as ground truth camera data frames and ground truth fittings, but I found it hard to match all those annotations with the `img_info` dict when loading data. I'm not sure what annotations are matched for several keys, including `kp2ds`, `kp3ds`, `params`, `camMats` and `camDist`. Therefore I want to know how you use the AGORA annotations for model finetuning. If it is possible, could you share the code which you use to load agora dataset?

2. Besides, could you also share the config file of finetuning ROMP on agora? Because the only thing I can find is the training settings for BEV from your your "Putting People in their Place: Monocular Regression of 3D People in Depth".

**Comment by Arthur151** [comment]
@ichbill ， related code would be released today~
