### ISSUE TITLE
[simple-romp] Webcam export not working

### ISSUE THREAD

**Issue by vivi90** [Arthur151/ROMP#268]
I wanted to test the live webcam export in Blender.
Exactly this way, how it's demonstrated in the [README](https://github.com/Arthur151/ROMP/blob/master/README.md):
![Demonstration](https://raw.githubusercontent.com/Arthur151/ROMP/assets/demo/animation/blender_character_driven-min.gif)

My first try was to create the required `*.npz` from webcam:
```ps
romp -t -sc=3 --onnx --show_largest --mode=webcam --calc_smpl --render_mesh --save_video -o "E:\Projekte\romp-test2\test_result.mp4"
```
After that i wanted to use it accourding to the [export guidelines](https://github.com/Arthur151/ROMP/blob/master/simple_romp/doc/export.md#usage).
**But:** My first command did not create anything.

My `pip freeze` output:
```ps
black==22.3.0
certifi==2021.10.8
click==8.1.2
colorama==0.4.4
Cython==0.29.30
lap==0.4.0
mypy-extensions==0.4.3
numpy==1.22.3
opencv-python==4.5.5.64
pathspec==0.9.0
platformdirs==2.5.1
simple-romp==1.0.5
tomli==2.0.1
torch==1.11.0
typing_extensions==4.1.1
wincertstore==0.2
```
System:
 - Python: v`3.9.12`
 - OS: Windows 10 Enterprise (64-bit, Version `21H2`, Build `19044.1706`)

**Comment by vivi90** [comment]
@Arthur151 The documentation seems outdated.
According to the [export guidelines](https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#usage):
```ps
python tools/convert2fbx.py --input=/home/yusun/BEV_results/video_results.npz --output=/home/yusun/BEV_results/dance.fbx --gender=female
```
*(Btw.: how exactly works `--subject_id`?)*
https://github.com/Arthur151/ROMP/blob/1458ba0b05a63d64b7fff7898cd917d9fda378b5/simple_romp/tools/convert2fbx.py#L40
Where is `tools/bpy-2.82.1` and `post_install`? Can't find it.
After looking around a bit, i found this one:
https://github.com/Arthur151/ROMP/blob/1458ba0b05a63d64b7fff7898cd917d9fda378b5/scripts/webcam_blender.sh#L1
[Config file](https://github.com/Arthur151/ROMP/blob/master/configs/webcam_blender.yml) is available, but getting this:
```ps
(sromp) PS C:\Users\Vivien\Projekte\romp-test3> python -u -m romp.predict.webcam --configs_yml='E:\Projekte\romp-test3\webcam_blender.yml'
C:\tools\miniconda3\envs\sromp\python.exe: Error while finding module specification for 'romp.predict.webcam' (ModuleNotFoundError: No module named 'romp.predict')
```
I know, thats because `romp.predict.webcam` is not part of `simple-romp`.

*Btw.: Currently i am, failing to install `bpy` on windows. Any ideas?* 🙂

**Comment by Arthur151** [comment]
Hi, the way to install bpy on windows is at https://github.com/TylerGubala/blenderpy/releases
```
Windows

Download the *.whl file
Install your Windows library dependencies (see [the Blender wiki](https://wiki.blender.org/wiki/Building_Blender/Windows), install all dependencies that have lib in the name for your given platform)
pip install bpy-2.91a0-cp37-cp37m-win_amd64.whl && bpy_post_install
```
Please note that it only support python 3.7, so maybe conda env for python 3.7 would be great.

About live blender driving, please refer to this repo. 
https://github.com/yanch2116/CharacterDriven-BlenderAddon
My colleague is responsible for maintaining this funciton now. 
Best regard.

**Comment by vivi90** [comment]
> Hi, the way to install bpy on windows is at https://github.com/TylerGubala/blenderpy/releases
> [..]
> pip install bpy-2.91a0-cp37-cp37m-win_amd64.whl && bpy_post_install

Already tested, but not working because of `&&` (works only on linux)

```ps
(base) PS C:\Users\Vivien\Projekte\romp-test3> pip install bpy-2.91a0-cp37-cp37m-win_amd64.whl && bpy_post_install
In Zeile:1 Zeichen:49
+ pip install bpy-2.91a0-cp37-cp37m-win_amd64.whl && bpy_post_install
+                                                 ~~
Das Token "&&" ist in dieser Version kein gültiges Anweisungstrennzeichen.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
```

> About live blender driving, please refer to this repo. https://github.com/yanch2116/CharacterDriven-BlenderAddon My colleague is responsible for maintaining this funciton now. Best regard.

Okay, then i will ask there.

**Comment by vivi90** [comment]
ah, i see, sorry 🙂

**Comment by vivi90** [comment]
Note: 
I think the best way might be to use blender directly according to the [blender documentation](http://builder.openhmd.net/blender-hmd-viewport-temp/advanced/command_line/arguments.html#python-options):
> -P, --python <filename>
> Run the given Python script file.

But tested it and failed:
```ps
(base) PS C:\Users\Vivien\Projekte\romp-test3> blender -b -P convert2fbx.py -- --input=E:/Projekte/romp-test3/video_results.npz --output=E:/Projekte/romp-test3/results.fbx --gender=female
Blender 2.93.5 (hash a791bdabd0b2 built 2021-10-06 06:44:49)
Read prefs: C:\Users\Vivien\AppData\Roaming\Blender Foundation\Blender\2.93\config\userpref.blend
usage: blender.exe [-h] [--input INPUT_PATH] [--output OUTPUT_PATH] [--fps_source FPS_SOURCE] [--fps_target FPS_TARGET] [--gender GENDER] [--subject_id SUBJECT_ID] [--rotate_y ROTATE_Y]
blender.exe: error: unrecognized arguments: -b -P convert2fbx.py -- --input=E:/Projekte/romp-test3/video_results.npz --output=E:/Projekte/romp-test3/results.fbx --gender=female
```
