### ISSUE TITLE
Error in convert2fbx.py

### ISSUE THREAD

**Issue by Harsh-Vavaiya** [Arthur151/ROMP#270]
@gngdb @vivi90 @Arthur151 @vltmedia @ayedaemon 

I'm getting error "AttributeError: module 'blenderpy' has no attribute 'app'" while importing blenderpy, I'm using convert2fbx.py in both linux and windows.

python=3.7 and have followed your guidelines to install it. please, help me ASAP.

**Comment by Arthur151** [comment]
This error is the installation problem of bpy.

There are two reason that might cause this bug.
1. didn't properly install the bpy,
Please follow [this instruction](https://github.com/Arthur151/ROMP/blob/master/simple_romp/doc/export.md).
Install via 
```
pip install /path/to/downloaded/bpy-2.91a0-cp37-cp37m-manylinux2014_x86_64.whl && bpy_post_install
```
2. There might be some other python libs that share the same name as blenderpy. To avoid this, I recommand that you can create a new anaconda env with python 3.7 and install bpy as instruction above.

I think the bug could be well handled with the second step.

**Comment by Harsh-Vavaiya** [comment]
I'm using conda environment, as I said earlier, I've followed all the instructions word to word mentioned in the link you shared.

**Comment by vivi90** [comment]
@Harsh-Vavaiya Maybe it might also be worth to take a look at: https://github.com/yanch2116/CharacterDriven-BlenderAddon

**Comment by Harsh-Vavaiya** [comment]
I'm trying that also.

**Comment by Harsh-Vavaiya** [comment]
@vivi90 I may sound like a noob, but can you please tell me that I'm going right as I'm not a regular user of the blender with scripting.

I've pasted your script in it,(above you shared) then changed the path, (I want a BVH file so, changed the extension in output_path) and pressed the play button. 

am I right? If yes I'm getting the error at line number 273.
