### ISSUE TITLE
Occlusion benchmarks

### ISSUE THREAD

**Issue by RedOrient** [Arthur151/ROMP#271]
Hello, thank you very much for your work.

Your paper mentioned the evaluation of occlusion benchmarks, tab 5 and tab 6. Tab 6 are known.. The question is how to generate the results of tab 5

Although you are in eval Tab 5 is also mentioned in eval.md, but it is confirmed that tab 4 is actually mentioned here

**Comment by Arthur151** [comment]
Thanks for the remind. Vivian.
