### ISSUE TITLE
Need help in generate smoothened results

### ISSUE THREAD

**Issue by Harsh-Vavaiya** [Arthur151/ROMP#272]
@gngdb @vivi90 @Arthur151 @vltmedia @ayedaemon  I've set smoothening coefficient at 24 but still, it has flickering.

https://user-images.githubusercontent.com/38744737/174255311-36b791f8-3c18-49de-87a4-c7312c38546e.mp4

and I'm using mode="video".

**Comment by Arthur151** [comment]
Hi, the smaller smoothening coefficient would be helpful. Maybe 2. or even 1.

**Comment by Harsh-Vavaiya** [comment]
ok, let me try.

**Comment by Arthur151** [comment]
Let's check, 
1.Have you re-generated the npz results from video with the new code?
2.Have you set the `temporal_optimization=True`, like this https://github.com/Arthur151/ROMP/blob/master/docs/config_guide.md#temporal_optimization-bool
3.Have you used the newly generated npz for exporting fbx?

4.How do you add the one-euro filter? Could you please show me the code?

**Comment by Harsh-Vavaiya** [comment]
@vivi90 Yes, it is. I've used temporal optimization.
