### ISSUE TITLE
COCO数据集相关问题

### ISSUE THREAD

**Issue by liangwx** [Arthur151/ROMP#273]
https://github.com/Arthur151/ROMP/blob/1458ba0b05a63d64b7fff7898cd917d9fda378b5/romp/lib/dataset/coco14.py#L73
请问后面的False是否应该改为True

**Comment by liangwx** [comment]
因为明明在eft_annots.npz中是存在beta参数的,为什么对应mask位置是False呢?

**Comment by liangwx** [comment]
lsp和mpii数据集也是一样

**Comment by Arthur151** [comment]
Hi，@liangwx，好久不见~
这3个数据集的smpl参数都是通过EFT算法粗略拟合估计的，theta参数可以用来训练，但是beta参数就没有太大价值了。
