### ISSUE TITLE
关于画图软件

### ISSUE THREAD

**Issue by liangwx** [Arthur151/ROMP#275]
![图片](https://user-images.githubusercontent.com/26651880/175291269-d3d62e68-4f46-40fd-8f23-68835a7f7404.png)
请问您这个两个图使用的是什么画图软件呢？以及您常用什么软件画与人体估计相关的流程框架示意图？有什么开源项目推荐吗？

**Comment by Arthur151** [comment]
@liangwx 
我是用的用的ppt画图。都是这个项目内的可视化代码生成的。
