### ISSUE TITLE
3DPW PA-MPJPE

### ISSUE THREAD

**Issue by qihangran** [Arthur151/ROMP#276]
请问测试3dpw的时pa mpjpe时，采用的是多少个关节点。
我看之前好多文章用的14个点，有的也有用24个点的，romp用的多少啊？

**Comment by Arthur151** [comment]
@qihangran 不同的评测protocol用的关键点数量不同的。
如果是3DPW challenge,用的是全部24个点。
如果是和VIBE在test集上比较，他们的protocol用的LSP 14个点。
