### ISSUE TITLE
相机选型问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [Arthur151/ROMP#279]
你好，在运行过程中我发现普通相机的运动模糊对结果影响较大，请问你们用的相机硬件是什么型号的呢？

**Comment by Arthur151** [comment]
我做demo用的就是网上买的100左右的网络摄像头。ubuntu下测试运行只有640x480的分辨率。。。
如果要本来拍摄的就很高清，而不是插值出来的，确实需要比较稳定的工业相机。

**Comment by JACKYLUO1991** [comment]
@Arthur151 现在遇到的最大的问题就是连续动作过快时候的运动模糊，普通相机应该搞不定...

**Comment by Arthur151** [comment]
可能用高速相机能解决这个问题。

**Comment by JACKYLUO1991** [comment]
@Arthur151 多谢楼主，我去调研一下
