### ISSUE TITLE
SMPL Model

### ISSUE THREAD

**Issue by mkhoshle** [Arthur151/ROMP#280]
Hi, 
I have a question regarding smpl model you are using in your code. In the `requirements.txt` I see that `smplx` is installed only. However in the paper only SMPL is referenced. Are you using SMPL to create the 3D reconstruction given pose and shape or are you using SMPL-x?
If you are using SMPL-x the reconstructed hand gestures should be pretty close to the image, but then why is this not the case looking at the results?

I would appreciate your feedback,
Thanks,

**Comment by Arthur151** [comment]
Hi, @mkhoshle 
Good question. 
Yes, so far, both BEV and ROMP use the SMPL model and estimate the body pose only. 
The lib `smplx` contains the implementation of SMPL model, which is employed to use the same evaluation code for a fair comparison with other SOTAs. 
Best

**Comment by mkhoshle** [comment]
Thank you very much for the clarification.
