### ISSUE TITLE
关于相机内外参的问题

### ISSUE THREAD

**Issue by sycamore27** [Arthur151/ROMP#282]
您好，感谢您的开源模型和贡献。我是一个新手，想请教一下如何从输出的参数中估计相机的内参和外参呢？
我看到输出的：
`outputs =  dict_keys(['cam', 'global_orient', 'body_pose', 'smpl_betas', 'smpl_thetas', 'center_preds', 'center_confs', 'cam_trans', 'verts', 'joints', 'pj2d_org'])`
其中cam是n * 3的弱透视相机参数，cam_trans是n * 3的相机到root的平移参数，如何计算得到普通针孔相机的3 * 3的内参、4 * 4的外参呢？
感谢！！！

**Comment by Arthur151** [comment]
您好，我们不估计相机的内参，而是预定义了相机的内参，可以参见：

https://github.com/Arthur151/ROMP/blob/e4613fd564cd632ac531228b94f949eaed76345e/simple_romp/romp/utils.py#L332

外参中的rotation是默认相机朝向正前方的，translation也就是`cam_trans`

**Comment by sycamore27** [comment]
好的，感谢解答！！！

**Comment by sycamore27** [comment]
您好，想确认一下cam_trans是n * 3的相机到root的平移参数，即包含了相机到bounding box的偏移和bounding box到root 节点吗？还是仅仅是在bounding box内的偏移呢？

**Comment by Arthur151** [comment]
@sycamore27 
cam_trans是相机为原点的相机坐标空间里，人体根节点(也就是你说的root)到相机的3D translation。
