### ISSUE TITLE
Custom Avatar Export

### ISSUE THREAD

**Issue by ShByeon3968** [Arthur151/ROMP#287]
Hello first of all thank you for your work. A problem occurs in the process of loading and exporting my Mixamo Avatar file as fbx in convert2fbx.py. The hierarchical structure of the skeleton is attached to the picture. Can you solve this problem? Thank you
![hierarchy](https://user-images.githubusercontent.com/101382267/176875893-63d1ea3f-7cea-405f-bac9-df2b9f1a03bf.png)
![20220701191243](https://user-images.githubusercontent.com/101382267/176875897-8f3685a8-ea83-4e1b-85e7-f991700dd413.png)

**Comment by Arthur151** [comment]
Please proper set the name of skeleton. 
https://github.com/Arthur151/ROMP/blob/8132c045ab68ebf037d57ee1e5d6a2afdebd3767/simple_romp/tools/convert2fbx.py#L93
Besides, current export code may not well adapt to Maximo model. Sorry about that.
