### ISSUE TITLE
[CHORE] Let's #GiveUpGitHub

### ISSUE THREAD

**Issue by vivi90** [Arthur151/ROMP#288]
GitHub becomes more and more the wrong platform for FOSS projects:
https://sfconservancy.org/blog/2022/jun/30/give-up-github-launch

So currently [i am](https://codeberg.org/vivi90) switching over from GitHub to [CodeBerg](https://codeberg.org).
How do you think about doing the same with your project? 🙂

**Comment by Arthur151** [comment]
Hi, Vivian.
Currently, Github is fine for me. Thanks for the suggestion and let me know the other choices. 
Best
