### ISSUE TITLE
Run video inference encoutered error

### ISSUE THREAD

**Issue by Rabbit314271** [Arthur151/ROMP#292]
Hello! ROMP is really a great work, and your document makes everything so easy to use.
But when I followed the step in google colab to install ROMP in my local machine, and run 

`python -m romp.predict.image --inputs=demo/images --output_dir=demo/image_results --renderer=pytorch3d`

then I encountered bug report as:

`No configs_yml is set, set it to the default --configs_yml=configs/image.yml
yaml_timestamp  /home/gpu/content/ROMP/active_configs/active_context_2022-07-03_15_21_17.yaml
Loading the configurations from configs/image.yml
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gpu/content/ROMP/romp/predict/image.py", line 79, in <module>
    main()
  File "/home/gpu/content/ROMP/romp/predict/image.py", line 71, in main
    processor = Image_processor(args_set=args_set)
  File "/home/gpu/content/ROMP/romp/predict/image.py", line 14, in __init__
    super(Image_processor, self).__init__(**kwargs)
  File "/home/gpu/content/ROMP/romp/predict/base_predictor.py", line 12, in __init__
    super(Predictor, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument args_set'`

then I print the args_set, it looks like this:

`{'args_set': Namespace(FOV=60, GPUS=0, HMloss_type='MSE', PCK_thresh=150, Rot_typ                                                                                      e='6D', Synthetic_occlusion_ratio=0, add_offsetmap=True, adjust_lr_epoch=[], adju                                                                                      st_lr_factor=0.1, baby_threshold=0.8, backbone='hrnet', batch_size=64, beta_dim=1                                                                                      0, bv_with_fv_condition=True, calc_PVE_error=False, calc_mesh_loss=True, calc_pck                                                                                      =False, calc_smpl_mesh=True, cam_dim=3, cam_dist_thresh=0.1, center_def_kp=True,                                                                                       centermap_conf_thresh=0.25, centermap_size=64, character='smpl', collect_subdirs=                                                                                      False, collision_aware_centermap=False, collision_factor=0.2, color_jittering_rat                                                                                      io=0.2, configs_yml='configs/image.yml', dataset='h36m,mpii,coco,aich,up,ochuman,                                                                                      lsp,movi', dataset_rootdir='/home/gpu/content/dataset/', deconv_num=0, depth_loss                                                                                      _type='Piecewise', distillation_learning=False, distributed_training=False, epoch                                                                                      =120, eval=False, eval_2dpose=False, eval_datasets='pw3d', f=None, fast_eval_iter                                                                                      =-1, fine_tune=True, fix_backbone_training_scratch=False, focal_length=443.4, fps                                                                                      _save=24, fv_conditioned_way='attention', gpu='0', head_block_num=2, homogenize_p                                                                                      ose_space=False, hrnet_pretrain='/home/gpu/content/ROMP/trained_models/pretrain_h                                                                                      rnet.pkl', image_loading_mode='image', input_size=512, inputs='demo/images', inte                                                                                      ractive_vis=False, kernel_sizes=[5], learn_2dpose=False, learn_AE=False, learn_kp                                                                                      2doffset=False, learn_relative=False, learn_relative_age=False, learn_relative_de                                                                                      pth=False, learn_relative_shape=False, local_rank=0, log_path='/home/gpu/content/                                                                                      log/', loss_thresh=1000, lr=0.0003, make_tracking=False, master_batch_size=-1, ma                                                                                      tch_preds_to_gts_for_supervision=False, matching_mode='all', matching_pckh_thresh                                                                                      =0.6, max_person=64, max_supervise_num=-1, merge_smpl_camera_head=False, mesh_clo                                                                                      th='ghostwhite', model_path='trained_models/ROMP_HRNet32_V1.pkl', model_precision                                                                                      ='fp32', model_return_loss=False, model_version=1, multi_person=True, new_trainin                                                                                      g=False, num_depth_level=8, nvxia_model_path='/home/gpu/content/ROMP/model_data/c                                                                                      haracters/nvxia', nw=4, optimizer_type='Adam', output_dir='demo/image_results', p                                                                                      erspective_proj=False, print_freq=50, renderer='pytorch3d', resnet_pretrain='/hom                                                                                      e/gpu/content/ROMP/trained_models/pretrain_resnet.pkl', rot_dim=6, rotate_prob=0.                                                                                      2, sampling_aggregation_way='floor', save_centermap=False, save_dict_results=True                                                                                      , save_mesh=True, save_visualization_on_img=True, scale_anchor=True, show_largest                                                                                      _person_only=False, show_mesh_stand_on_image=False, shuffle_crop_mode=False, shuf                                                                                      fle_crop_ratio_2d=0.1, shuffle_crop_ratio_3d=0.9, smil_model_path='/home/gpu/cont                                                                                      ent/ROMP/model_data/smpl_models/smil_packed_info.pth', smpl_joint_num=22, smpl_me                                                                                      sh_root_align=False, smpl_model_path='/home/gpu/content/ROMP/model_data/smpl_mode                                                                                      ls/smpl_packed_info.pth', smpl_prior_path='/home/gpu/content/ROMP/model_data/para                                                                                      meters/gmm_08.pkl', smpl_uvmap='/home/gpu/content/ROMP/model_data/parameters/smpl                                                                                      _vt_ft.npz', smpla_model_path='/home/gpu/content/ROMP/model_data/smpl_models/SMPL                                                                                      A_NEUTRAL.pth', soi_camera='far', supervise_cam_params=False, supervise_global_ro                                                                                      t=False, surrounding_camera=False, tab='hrnet_cm64_process_images', teacher_model                                                                                      _path='/export/home/suny/CenterMesh/trained_models/3dpw_88_57.8.pkl', temporal_op                                                                                      timization=False, test_interval=2000, top_n_error_vis=6, track_memory_usage=False                                                                                      , use_coordmaps=True, use_eft=True, val_batch_size=4, voc_dir='/home/gpu/content/                                                                                      dataset/VOCdevkit/VOC2012/', wardrobe='/home/gpu/content/ROMP/model_data/wardrobe                                                                                      ', weight_decay=1e-06)}
`

I have totally no idea about why this occurs. Hope for your answer :)

**Comment by Arthur151** [comment]
Sorry about the bug. 
The inference usage of original version of ROMP has been out of data. The google colab would be updated later. 
For inference, please use simple-romp.
https://github.com/Arthur151/ROMP/tree/master/simple_romp
