### ISSUE TITLE
BEV's Evaluation on RH dataset Encoutered Error

### ISSUE THREAD

**Issue by Rabbit314271** [Arthur151/ROMP#293]
Hi, Doc. Sun. It works perfect when I run a BEV's evaluation on CMU-Panoptic dataset. However, when I use RH Dataset for evaluation , after 80 iterations like

`processing in crowd mode
BEV 'forward' executed in 1.8504s, FPS 0.5
[-                                       ]   71/1836 (  3%) 1765 to go
BEV 'forward' executed in 0.0923s, FPS 10.8
[-                                       ]   72/1836 (  3%) 1764 to go
BEV 'forward' executed in 0.1033s, FPS 9.7
[-                                       ]   73/1836 (  3%) 1763 to go
BEV 'forward' executed in 0.0940s, FPS 10.6
[-                                       ]   74/1836 (  4%) 1762 to go
BEV 'forward' executed in 0.0832s, FPS 12.0
[-                                       ]   75/1836 (  4%) 1761 to go
BEV 'forward' executed in 0.0859s, FPS 11.6
[-                                       ]   76/1836 (  4%) 1760 to go
BEV 'forward' executed in 0.0892s, FPS 11.2
[-                                       ]   77/1836 (  4%) 1759 to go
BEV 'forward' executed in 0.2021s, FPS 4.9
[-                                       ]   78/1836 (  4%) 1758 to go
BEV 'forward' executed in 0.2111s, FPS 4.7
[-                                       ]   79/1836 (  4%) 1757 to go
BEV 'forward' executed in 0.1024s, FPS 9.8
[-                                       ]   80/1836 (  4%) 1756 to go`

, a list of `No person detected!` occured like

`processing in crowd mode
No person detected!
No person detected!
No person detected!
No person detected!
No person detected!
No person detected!
`

, and then it pomps out error like 

`File "/usr/local/anaconda3/lib/python3.8/site-packages/bev/main.py", line 138, in forward
    outputs = self.process_long_image(image, show_patch_results=self.settings.show_patch_results)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/bev/main.py", line 213, in process_long_image
    ch, cw = croped_images[cid].shape[:2]
IndexError: list index out of range`

It functions well in the beginning, so I wondered why the evaluation encountered error in the middle of the process. Hope for your answer :-)

**Comment by Arthur151** [comment]
Sorry about the bug, let me check it now.

**Comment by Arthur151** [comment]
@Rabbit314271 
Thanks for the bug report.
I have seen the reason that caused this bug.  

Please fetch the latest code from this rep. and re-install simple-romp via
```
pip uninstall simple-romp # you may need to run this multiple times to avoid that you may install multiple version of simple-romp
cd ROMP/simple-romp
python setup.py install
```
With the latest code,  during evaluation, it shouldn't run into the long image mode with setting `crowd=False`.
Let me know if you encounter other problems

**Comment by Rabbit314271** [comment]
Thank you very much for the hot-fixing~ That's really nice of you.
