### ISSUE TITLE
Question about posetrack dataset

### ISSUE THREAD

**Issue by YangChangHee** [Arthur151/ROMP#294]
Thank your works!

Your thesis is very impressive and wonderful.

I have 2 Questions.
I understand that the dataset below is used when training BEVs.
 dataset: h36m,muco,coco,lsp,agora,pw3d,relative_human,posetrack
 eval_datasets: 'relative,agora'

However, Google drive has only annots_train21_full.npz of posetrack data.
1.
Then after I change the dataset above as below,
h36m,muco,coco,lsp,agora,pw3d,relative_human,posetrack21
Then, should I change the dataset above as below and receive the image file from the official dataset site?

2.
Or should I change the code below to 21 on the data loader after using it as it is?
dataset: h36m,muco,coco,lsp,agora,pw3d,relative_human,posetrack

**Comment by Arthur151** [comment]
Hi, @YangChangHee 
Thanks for your kind words. We really appreciate that.

About your question,
The datasets are registered at 
https://github.com/Arthur151/ROMP/blob/75078ff12ca53241f0d2653cdc7f9b4c0522dbfa/romp/lib/dataset/mixed_dataset.py#L31
You can see that `posetrack` has already correspond to PoseTrack21. So you don't have to chage it to posetrack21

**Comment by YangChangHee** [comment]
Thank You!
I have another question.

In train.md, shscripts/V1_train.sh(nohup.
[nohup.log](https://github.com/Arthur151/ROMP/files/9051704/nohup.log)
log) is the result of training with scripts, but the accuracy does not seem to converge properly.
Epoch needs to train up to 120, doesn't it converge before that?
Do you happen to know what number of tables are in the ROMP paper?

**Comment by YangChangHee** [comment]
I'm sorry. I think it's my mistake. Forget "what number of tables are in the ROMP paper"
If you look at the nohup.log, MPJPE has a maximum accuracy of 92, and the accuracy is getting worse. Should I wait until it converges more?
