### ISSUE TITLE
Training code release

### ISSUE THREAD

**Issue by nicolasugrinovic** [Arthur151/ROMP#30]
Hi, kudos for the great work!
When are you planning to release the training code?
Thanks

**Comment by Arthur151** [comment]
Thanks for your interests! 
The paper is still under submission. 
The training code will be released when the paper is accepted.

**Comment by nicolasugrinovic** [comment]
Great thank you. 
I really like that your approach is bottom-up and specially the idea of repulsion fields of the body centers!
Hope it is released soon. Do you know the date of the acceptance announcement?

**Comment by Arthur151** [comment]
Really appreciate your attension! Sorry, I don't know the exact data. But I believe it won't be too long.
I will try my best to get the code released as soon as possible.

**Comment by Arthur151** [comment]
We are really sorry for the delayed release of training code. ROMP just gets in ICCV 2021. I am preparing the training code (on fire). There are multiple version of ROMP training code. I will release the code for fine-tunning first in convenience of a fast try. My appology.

**Comment by leviome** [comment]
> We are really sorry for the delayed release of training code. ROMP just gets in ICCV 2021. I am preparing the training code (on fire). There are multiple version of ROMP training code. I will release the code for fine-tunning first in convenience of a fast try. My appology.

Awesome!

**Comment by Arthur151** [comment]
The training code has been released, along with almost all evaluation protocols~

**Comment by dluvizon** [comment]
Hi @Arthur151 ,

Congratulations for this awesome work and thank you so much for sharing this code!
Concerning training, I noticed a required file "datasets/h36m/h36m_train.txt" that I was not able to find yet.
I checked the source code, ZIP files in the releases and Google Drive, without success. So I suppose this file should be in the original H36M dataset, right?
Otherwise, can it be generated just considering all frames from the training subjects?

Thanks.

**Comment by dluvizon** [comment]
As an additional comment: I just noticed that the file "datasets/mpii/annot/train.json" is also required for training. Maybe I missed something in the installation process?

**Comment by Arthur151** [comment]
Sorry, my mistake. I have uploaded these files to the [google drive](https://drive.google.com/drive/u/1/folders/1Vm2Nqaz5Bon2Kblcg8DQguwa9ti1Tn6h). 
Please be aware to change [this line](https://github.com/Arthur151/ROMP/blob/cffb38e489921fd6603c72f0ab9dc97c70987548/romp/lib/dataset/h36m.py#L77).

Don't hestitate to contact me if there are any issues. I will fix them as soon as possible.

**Comment by liangwx** [comment]
Yes hh, When I add the "datasets/h36m/h36m_train.txt", I  run "python -m romp.lib.dataset.h36m" again, but get error like this:
Exception has occurred: TypeError
Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhaohan/Install/anaconda3/envs/romp-py37-cu111/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhaohan/Install/anaconda3/envs/romp-py37-cu111/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhaohan/Install/anaconda3/envs/romp-py37-cu111/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhaohan/wxl/ROMP/romp/lib/dataset/image_base.py", line 342, in __getitem__
    return self.get_item_single_frame(index)
  File "/home/zhaohan/wxl/ROMP/romp/lib/dataset/image_base.py", line 85, in get_item_single_frame
    info = self.get_image_info(index)
  File "/home/zhaohan/wxl/ROMP/romp/lib/dataset/h36m.py", line 86, in get_image_info
    image = cv2.imread(imgpath)[:,:,::-1]#把BGR转成RGB
TypeError: 'NoneType' object is not subscriptable
  File "/home/zhaohan/wxl/ROMP/romp/lib/dataset/image_base.py", line 492, in test_dataset
    for _,r in enumerate(dataloader):
  File "/home/zhaohan/wxl/ROMP/romp/lib/dataset/h36m.py", line 123, in <module>
    test_dataset(h36m, with_3d=True,with_smpl=True,)

**Comment by Arthur151** [comment]
This error is pretty obvious. You can try to print the `imgpath` in `image = cv2.imread(imgpath)[:,:,::-1]`.
Please make sure the imgpath refer to the correct path.
I guess that you didn't put the h36m dataset at the right place. Or the name of the image folder is wrong.
To correct this, please check [this line](https://github.com/Arthur151/ROMP/blob/1d2d96bd39f67a0a86ce7e397e3af856b3c5ee00/romp/lib/dataset/h36m.py#L10) and [this line](https://github.com/Arthur151/ROMP/blob/1d2d96bd39f67a0a86ce7e397e3af856b3c5ee00/romp/lib/dataset/h36m.py#L11)

**Comment by Arthur151** [comment]
@liangwx  Come on. I am on fire.

**Comment by liangwx** [comment]
@Arthur151  Sorry to reply so late, I find the "spacing" of the image path in h36m.txt is not compatible with my ubuntu envirenment. What'more, maybe you'd like to use Relative Path other than Absolute one.

**Comment by Arthur151** [comment]
I see. Thanks for the bug report. I have update the h36m_train.txt in google drive.
欢迎再次光临。
