### ISSUE TITLE
关于3DPW评估中的三种协议

### ISSUE THREAD

**Issue by RedOrient** [Arthur151/ROMP#304]
大佬好，我在阅读论文中有些困惑，我对于3DPW评估中的三种协议是这样理解的

协议一：不用3dpw-train数据进行训练，对整个3dpw数据集进行评估
协议二：不用3dpw-train数据进行训练，对3dpw-test进行评估
协议三：使用3dpw-train数据进行训练，对3dpw-test进行评估

请问是这样吗？

**Comment by Arthur151** [comment]
@RedOrient 是的，1评估用的ground truth label和评测代码与2/3都不一样。

**Comment by featherwit-right** [comment]
> @RedOrient 是的，1评估用的ground truth label和评测代码与2/3都不一样。

finetune的含义我也有一点不太清楚。
表二中是协议二的结果，可以看到也有不使用额外数据集的结果。那么不使用额外数据集也不使用3dpw-train，那模型是在什么数据集上进行训练的呢？

**Comment by Arthur151** [comment]
这个额外数据集指的是相对于baseline方法SPIN所使用的训练集而言的，也就是COCO, Human3.6M等数据集。
