### ISSUE TITLE
请问数据集读取时返回的valid_masks代表什么含义呢？

### ISSUE THREAD

**Issue by featherwit-right** [Arthur151/ROMP#307]
valid_masks好像是代表某些标签是否存在或者是否准确。
根据代码，valid_masks[3,4,5]似乎分别代表pose参数的前3位，剩余位以及shape参数是否有效。
那valid_masks的其余几位是什么含义呢？

**Comment by Arthur151** [comment]
@featherwit-right ,您好，感谢您的提问，
关于每一位表示的意义在

https://github.com/Arthur151/ROMP/blob/91dac0172c4dc0685b97f96eda9a3a53c626da47/romp/lib/dataset/image_base.py#L99

**Comment by featherwit-right** [comment]
好的了解了，谢谢
