### ISSUE TITLE
question about Gaussion kernel size and CAR useage during training ROMP

### ISSUE THREAD

**Issue by ChangjianLi** [Arthur151/ROMP#309]
作者大大你好
I have a question about the training codes. I have read through the codes and I couldn't find the methods of Gaussion kernel size and CAR calculation used for the training. Did I missed some part lol

**Comment by Arthur151** [comment]
Hi, 
The implementation is quite simple
CAR:
https://github.com/Arthur151/ROMP/blob/91dac0172c4dc0685b97f96eda9a3a53c626da47/romp/lib/maps_utils/centermap.py#L99
Gaussion kernel size:
https://github.com/Arthur151/ROMP/blob/91dac0172c4dc0685b97f96eda9a3a53c626da47/romp/lib/maps_utils/centermap.py#L362

**Comment by ChangjianLi** [comment]
> Hi, The implementation is quite simple CAR:
> 
> https://github.com/Arthur151/ROMP/blob/91dac0172c4dc0685b97f96eda9a3a53c626da47/romp/lib/maps_utils/centermap.py#L99
> 
> 
> Gaussion kernel size:
> https://github.com/Arthur151/ROMP/blob/91dac0172c4dc0685b97f96eda9a3a53c626da47/romp/lib/maps_utils/centermap.py#L362

Thx for the reply : ). But are these methods used during training and testing? I looked through the result_parser.py and the function used to calculate centermap is _self.centermap_parser.parse_centermap(outputs['center_map'])_ instead of CAR method

**Comment by Arthur151** [comment]
They are just used to generate the ground truth body center heatmap to guide more discriminative representation learning. 
In other word, they are only used for training.
