### ISSUE TITLE
关于数据集处理中的减去root_trans。

### ISSUE THREAD

**Issue by QiAnBozZ** [Arthur151/ROMP#311]
在之前一个版本的数据集代码中多数数据集有：
kp3ds -= root_trans[:,None]
就是所有的3d的坐标标签都是减去根节点之后的坐标。
这样处理的话，模型预测的坐标是否就不是世界坐标系下的坐标了，而是以根节点（左、右臀中点）为零点的坐标？

最新版本的数据集是不是因为这个原因，把root_trans也传入了模型？

**Comment by Arthur151** [comment]
@QiAnBozZ ，您好，是的！
kp3ds用于监督3D pose的时候，都是采用根节点配准后的3D关节点位置用于监督的。
新版本中传给模型监督用的root_trans是处理过后，将各个数据集不同相机空间的trans, 用pnp转化到我们预定义的一个标准相机空间里了。
https://github.com/Arthur151/ROMP/blob/bafc86897c387caae125e7119b31dc30ee317bf0/romp/lib/dataset/image_base.py#L399
这样便于训练，因为我们的输入图片的相机参数是未知的。
