### ISSUE TITLE
全局旋转的抖动问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [Arthur151/ROMP#317]
您好，通过阅读代码我发现一欧元滤波用在了除全局旋转外的其它关节轴角上，请问一下对于全局旋转的抖动问题该如何解决呢？

**Comment by Arthur151** [comment]
一欧元滤波施加在全局旋转，会导致异常的突然翻转。目前还没有找到导致这一异常翻转的原因，因此没有施加到全局旋转上。

**Comment by JACKYLUO1991** [comment]
@Arthur151 我也发现这个问题，我用当前帧和前一帧的球面线性插值处理，但是效果仍然有限...
