### ISSUE TITLE
关于3dpw的测试协议

### ISSUE THREAD

**Issue by featherwit-right** [Arthur151/ROMP#318]
您好，感谢您优秀的工作！
我是第一次接触这个领域的新手，所以关于论文中的各种Protocol有一些疑惑。
根据我的调研，在HMR领域，大家一开始都是在各种数据集上进行训练(H36M、COCO等等)，然后再在3DPW上进行测试。
所以，论文中不加 * 的实验结果，意味着是在混合数据集（不含3dpw training set）下训练，在3dpw test set进行测试得到的结果；
而加 * 的实验结果则意味着是在混合数据集（包含3dpw training set）下训练，在3dpw test set进行测试得到的结果。
即 extra datasets指的是3dpw training set。
而finetune指的是在混合数据集上进行训练之后，在得到的参数基础上，在3dpw training set上重新训练一遍。
不知这样的理解是否正确？

**Comment by Arthur151** [comment]
您好，很感谢您对的ROMP的认可。
1.extra datasets也包含crowdpose，就是使用了对比的baseline方法没有用到的训练数据集，就叫extra datasets。
2.finetuning确实是指在特定的评测数据集的训练集上进行评测。
