### ISSUE TITLE
如何更改romp姿态参数提取模型？

### ISSUE THREAD

**Issue by YiningPeng** [Arthur151/ROMP#319]
您好，运行`romp --mode=video --calc_smpl -i=path/to/input -o=path/to/output`，使用的是ROMPv1模型，但是我想要更换为ROMP_HRNet32_V1.pkl模型，请问从哪里下载？又在哪里更改代码呢？

**Comment by Arthur151** [comment]
您好，ROMPv1模型就是ROMP_HRNet32_V1.pkl通过[这里](https://github.com/Arthur151/ROMP/tree/master/simple_romp#convert-checkpoints)
转成了simple-romp的格式.
如果您想改用其他的模型，可以通过
https://github.com/Arthur151/ROMP/tree/master/simple_romp#convert-checkpoints
转换后，设置
https://github.com/Arthur151/ROMP/blob/bafc86897c387caae125e7119b31dc30ee317bf0/simple_romp/romp/main.py#L37
