### ISSUE TITLE
Pretrained Resnet Model?

### ISSUE THREAD

**Issue by mkhoshle** [Arthur151/ROMP#320]
Hi, 

Downloading the following file: `wget https://github.com/Arthur151/ROMP/releases/download/v1.1/trained_models_try.zip` I can only see pretrained HRNET model. Is the pretrained resnet available also? Where can I get it?

Thanks,

**Comment by Arthur151** [comment]
Hi, you can use other pre-trained ResNet-50 model for human pose estimation, like 
https://github.com/microsoft/human-pose-estimation.pytorch

**Comment by mkhoshle** [comment]
@Arthur151 Thank you!
