### ISSUE TITLE
wrong index when adjusting z-wise 

### ISSUE THREAD

**Issue by 170928** [Arthur151/ROMP#321]
In function ' coarse2fine_localization', for adjusting z-wise only, I think we use cam_maps_3d[:, :, :, :, 0], not [:, :, :, :, 2] because self.coordmap_3d is the result of concatenate (Z_map, Y_map, X_map). 

```python
        center_maps_3d = self.center_map_refiner(center_maps_3d.unsqueeze(1)).squeeze(1)
        cam_maps_3d = self.coordmap_3d + cam_maps_offset.unsqueeze(-1).transpose(4,1).contiguous()
        cam_maps_3d[:,:,:,:,2] = cam_maps_3d[:,:,:,:,2] + cam_maps_offset_bv.unsqueeze(2).contiguous()
```

**Comment by Arthur151** [comment]
Hi, MJ Shin @170928 
Thanks a lot for pointing out this error! I will fix it in the next version.

**Comment by vivi90** [comment]
@Arthur151 Is it already fixed? 🙂

**Comment by Arthur151** [comment]
Yes.
