### ISSUE TITLE
Questions about 3D translation calculation

### ISSUE THREAD

**Issue by 170928** [Arthur151/ROMP#322]
In coarse2fine_localization function, there is code as belows:
```python
cam_maps_3d = self.coordmap_3d + cam_maps_offset.unsqueeze(-1).transpose(4,1).contiguous()
          # cam_maps_offset_bv adjust z-wise only
cam_maps_3d[:,:,:,:,2] = cam_maps_3d[:,:,:,:,2] + cam_maps_offset_bv.unsqueeze(2).contiguous()
cam_maps_3d = self.cam_map_refiner(cam_maps_3d.unsqueeze(1).transpose(5,1).squeeze(-1))
```
I have some questions at this function.

> In Figure 2, 3D anchor map is added after calculating 3D Offset Map. But, in this function, 3D anchor map is added to CAM_MAPS_OFFSET first (orange box in Figure 2). Can you explain why?
I think right codes for this part is as below.
```python
# (B, 1, 128, 128, 3) + (B, 64, 1, 128) -> (B, 64, 128, 128, 3) + (B, 64, 128, 128, 3)
offset_maps_3d = cam_maps_offset.unsqueeze(-1).transpose(4, 1).repeat(1, 64, 1, 1, 1) + cam_maps_offset_bv.unsqueeze(2).unsqueeze(-1).repeat(1, 1, 128, 1, 3)
offset_maps_3d = self.cam_map_refiner(offset_maps_3d) # (B, 3, 64, 128, 128)

translation_3d = offset_maps_3d + self.coordmap_3d 
```

> I can't understand why (1) convert_cam_params_to_centermap_coords and (2) denormalize_center functions are required. Can you explain details about these functions .. :( 
It is hard to know why cam3dmap_anchors is subtracted and using argmin ....
```python
cam_czyx = denormalize_center(convert_cam_params_to_centermap_coords(cams_preds.clone(), self.cam3dmap_anchor), size=self.outmap_size)
```

**Comment by Arthur151** [comment]
Hi, good questions! Really happy to discuss these details with you. 

1.About the `cam_maps_offset_bv`, as shown in the Fig.2, it is only used to adjust the z values ( I will fix your last issue). 
Adding the self.coordmap_3d (could be regarded as a bias) before or after the refiner would be the same. 

2. cams_preds are continuous 3D positions in camera space, while we are supposed to obtain the corresponding discrete location on 3D center map via matching the closet discrete 3D centers to the continuous 3D camera values. 
The argmin + subtraction is the matching process.

**Comment by 170928** [comment]
Thank you for your reply :)
