### ISSUE TITLE
`pretrain.yml` does not exist

### ISSUE THREAD

**Issue by mkhoshle** [Arthur151/ROMP#325]
Hello,

I was looking into the following script: `https://github.com/Arthur151/ROMP/blob/master/scripts/pretrain.sh`. In this script, you are using `pretrain.yml` however there is no such file in the repository.

Thanks

**Comment by Arthur151** [comment]
Sorry, pretraining process is not supported by this rep. Like we discussed before, you can the training code of  2D pose estimation methods, like HigherHRNet for HRNet-32, simple baseline for ResNet-50, or directly use their trained models.
