### ISSUE TITLE
Is it possible to keep the old version of model_data.zip?

### ISSUE THREAD

**Issue by jiangwei221** [Arthur151/ROMP#326]
I saw model_data.zip has changed on 21 Jun 2022. See: https://github.com/Arthur151/ROMP/releases/tag/v1.1
Is it possible to have an old copy of it?

**Comment by jiangwei221** [comment]
Yes, it is, thanks a lot!

**Comment by Arthur151** [comment]
B.T.W., @jiangwei221 
Doc. Jiang Wei, congrats for the impressive NeuMan! 
It would be very helpful to promote the related research. 
Best regrads. 
Yu

**Comment by jiangwei221** [comment]
Thanks Dr. Sun!
In NeuMan, we used ROMP as the default SMPL estimator. It is very robust to challenging poses!
