### ISSUE TITLE
Question about cpu usage and gpu usage.

### ISSUE THREAD

**Issue by Havagoodone** [Arthur151/ROMP#328]
Hi.

I have a question about cpu usage and gpu usage.

When I excuted the model with command "romp --mode=webcam --show, desktop's cpu usage was over 70% and gpu usage was under 5%.

I checked I used gpu-mode and cuda_is_available was true.

The cpu was i7-8700k and gpu was RTX 2060.

I'm wondering the result was right or I did something wrong.

Thank you very much!! :)

**Comment by Arthur151** [comment]
Hi, good questions. 

The key is that the FPS. 
If the FPS is about 30, then we are fine. If the FPS is only 1, then we have to check whether the GPU memory is used. 

Let me know if there is something wrong.

**Comment by Havagoodone** [comment]
Thanks for your reply!!

**Comment by vivi90** [comment]
Possible duplicate to: https://github.com/Arthur151/ROMP/issues/337
