### ISSUE TITLE
[simple-romp] Pixel color pattern should be documented

### ISSUE THREAD

**Issue by vivi90** [Arthur151/ROMP#339]
## State of the art
The image processing library [Pillow](https://pypi.org/project/Pillow) uses the **RGB** (red, green, blue) pixel format.
In contrast the visual processing library [OpenCV](https://pypi.org/project/opencv-python) uses the **BGR** (blue, green, red) pattern.
Both libraries are popular.

## ROMP implementation
Since ROMP uses mainly OpenCV:
https://github.com/Arthur151/ROMP/blob/d78880a1c56bd92df7e8f28d5d5aa19c6b7106f6/simple_romp/romp/main.py#L181
https://github.com/Arthur151/ROMP/blob/d78880a1c56bd92df7e8f28d5d5aa19c6b7106f6/simple_romp/romp/main.py#L189
https://github.com/Arthur151/ROMP/blob/d78880a1c56bd92df7e8f28d5d5aa19c6b7106f6/simple_romp/romp/utils.py#L117
There is of course an conversion, since the model requires the *RGB* pattern:
https://github.com/Arthur151/ROMP/blob/d78880a1c56bd92df7e8f28d5d5aa19c6b7106f6/simple_romp/romp/utils.py#L27

## Example
Of cource i might do something like this..
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Pillow example."""

# Pillow
from PIL import Image
# Numpy
from numpy import asarray
# OpenCV
from cv2 import (  # pylint: disable=no-name-in-module
    cvtColor,
    COLOR_RGB2BGR
)
# ROMP
from romp import ROMP
from romp.main import default_settings as romp_default_settings


image = Image.open("example.png")
result = ROMP(romp_default_settings)(
    cvtColor(asarray(image), COLOR_RGB2BGR)
)
...
```
But the part `cvtColor(..., COLOR_RGB2BGR)` is critical.
It's easy to make an mistake there, if the user doesn't take a look at the source code of ROMP.

## Recommendation
I think the best solution might be to add an note to the README file of simple-romp, that it expects the **BGR** pattern for it's input data.

**Comment by Arthur151** [comment]
Thanks a lot! Yes, this is an essential note we have to add. 
I have add it to cooresponding code line, see 
https://github.com/Arthur151/ROMP/tree/master/simple_romp#calling-as-python-lib
