### ISSUE TITLE
OpenGL.error.GLError

### ISSUE THREAD

**Issue by NoLookDefense** [Arthur151/ROMP#34]
Thanks for your work. I am running your demo with **CUDA_VISIBLE_DEVICES=0 python core/test.py --gpu=0 --configs_yml=configs/single_image.yml**
But an error occurs. 
I am running with ubuntu16.04. The python verison is 3.6.9. How should I check what's happening?

(romp) jack@jack-System-Product-Name:~/Documents/ROMP/src$ CUDA_VISIBLE_DEVICES=0 python core/test.py --configs_yml=configs/single_image.yml
pygame 2.0.1 (SDL 2.0.14, Python 3.6.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO:root:{'tab': 'hrnet_cm64_single_image_test', 'configs_yml': 'configs/single_image.yml', 'demo_image_folder': '/path/to/image_folder', 'local_rank': 0, 'model_version': 1, 'multi_person': True, 'collision_aware_centermap': False, 'collision_factor': 0.2, 'kp3d_format': 'smpl24', 'eval': False, 'max_person': 64, 'input_size': 512, 'Rot_type': '6D', 'rot_dim': 6, 'centermap_conf_thresh': 0.25, 'centermap_size': 64, 'deconv_num': 0, 'model_precision': 'fp32', 'backbone': 'hrnet', 'gmodel_path': '../trained_models/ROMP_hrnet32.pkl', 'print_freq': 50, 'fine_tune': True, 'gpu': '0', 'batch_size': 64, 'val_batch_size': 1, 'nw': 4, 'calc_PVE_error': False, 'dataset_rootdir': '/home/jack/Documents/dataset/', 'high_resolution': True, 'save_best_folder': '/home/jack/Documents/checkpoints/', 'log_path': '/home/jack/Documents/log/', 'total_param_count': 85, 'smpl_mean_param_path': '/home/jack/Documents/ROMP/models/satistic_data/neutral_smpl_mean_params.h5', 'smpl_model': '/home/jack/Documents/ROMP/models/statistic_data/neutral_smpl_with_cocoplus_reg.txt', 'smplx_model': True, 'cam_dim': 3, 'beta_dim': 10, 'smpl_joint_num': 22, 'smpl_model_path': '/home/jack/Documents/ROMP/models', 'smpl_J_reg_h37m_path': '/home/jack/Documents/ROMP/models/smpl/J_regressor_h36m.npy', 'smpl_J_reg_extra_path': '/home/jack/Documents/ROMP/models/smpl/J_regressor_extra.npy', 'kernel_sizes': [5], 'GPUS': 0, 'use_coordmaps': True, 'webcam': False, 'video_or_frame': False, 'save_visualization_on_img': True, 'output_dir': '/path/to/outputdir', 'save_mesh': True, 'save_centermap': True, 'save_dict_results': True, 'multiprocess': False}
INFO:root:------------------------------------------------------------------
INFO:root:start building model.
Using ROMP v1
INFO:root:using fine_tune model: ../trained_models/ROMP_hrnet32.pkl
INFO:root:finished build model.
Traceback (most recent call last):
  File "core/test.py", line 225, in <module>
    main()
  File "core/test.py", line 205, in main
    demo = Demo()
  File "core/test.py", line 7, in __init__
    self._prepare_modules_()
  File "core/test.py", line 14, in _prepare_modules_
    self.visualizer = Visualizer(resolution=self.vis_size, input_size=self.input_size,with_renderer=True)
  File "/home/jack/Documents/ROMP/src/core/../lib/models/../utils/../maps_utils/../dataset/../dataset/../dataset/../visualization/visualization.py", line 23, in __init__
    self.renderer = get_renderer(resolution=resolution)
  File "/home/jack/Documents/ROMP/src/core/../lib/models/../utils/../maps_utils/../dataset/../dataset/../dataset/../visualization/../visualization/renderer.py", line 142, in get_renderer
    renderer = Renderer(faces,resolution=resolution[:2])
  File "/home/jack/Documents/ROMP/src/core/../lib/models/../utils/../maps_utils/../dataset/../dataset/../dataset/../visualization/../visualization/renderer.py", line 72, in __init__
    point_size=1.0)
  File "/home/jack/anaconda3/envs/romp/lib/python3.6/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/jack/anaconda3/envs/romp/lib/python3.6/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/jack/anaconda3/envs/romp/lib/python3.6/site-packages/pyrender/platforms/egl.py", line 188, in init_context
    EGL_NO_CONTEXT, context_attributes
  File "/home/jack/anaconda3/envs/romp/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/jack/anaconda3/envs/romp/lib/python3.6/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 12297,
	baseOperation = eglCreateContext,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7ff367d4e268>,
		<OpenGL._opaque.EGLConfig_pointer object at 0x7ff367d4e1e0>,
		<OpenGL._opaque.EGLContext_pointer object at 0x7ff367e84d08>,
		<OpenGL.arrays.lists.c_int_Array_7 object at 0x7ff367e64d08>,
	),
	result = <OpenGL._opaque.EGLContext_pointer object at 0x7ff367d311e0>
)

**Comment by NoLookDefense** [comment]
Also, when I am about to run the evaluation code, another error happens:

pygame 2.0.1 (SDL 2.0.14, Python 3.6.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO:root:{'tab': 'hrnet_cm64_pw3d_challenge', 'configs_yml': 'configs/eval_3dpw_challenge.yml', 'demo_image_folder': 'None', 'local_rank': 0, 'model_version': 1, 'multi_person': True, 'collision_aware_centermap': False, 'collision_factor': 0.2, 'kp3d_format': 'smpl24', 'eval': True, 'max_person': 64, 'input_size': 512, 'Rot_type': '6D', 'rot_dim': 6, 'centermap_conf_thresh': 0.2, 'centermap_size': 64, 'deconv_num': 0, 'model_precision': 'fp32', 'backbone': 'hrnet', 'gmodel_path': '/home/jack/Documents/ROMP/trained_models/ROMP_hrnet32.pkl', 'print_freq': 50, 'fine_tune': False, 'gpu': '0', 'batch_size': 64, 'val_batch_size': 64, 'nw': 4, 'calc_PVE_error': False, 'dataset_rootdir': '/home/jack/Documents/3d_pose_dataset/3dpw', 'high_resolution': True, 'save_best_folder': '/home/jack/Documents/checkpoints/', 'log_path': '/home/jack/Documents/log/', 'total_param_count': 85, 'smpl_mean_param_path': '/home/jack/Documents/ROMP/models/satistic_data/neutral_smpl_mean_params.h5', 'smpl_model': '/home/jack/Documents/ROMP/models/statistic_data/neutral_smpl_with_cocoplus_reg.txt', 'smplx_model': True, 'cam_dim': 3, 'beta_dim': 10, 'smpl_joint_num': 22, 'smpl_model_path': '/home/jack/Documents/ROMP/models', 'smpl_J_reg_h37m_path': '/home/jack/Documents/ROMP/models/smpl/J_regressor_h36m.npy', 'smpl_J_reg_extra_path': '/home/jack/Documents/ROMP/models/smpl/J_regressor_extra.npy', 'kernel_sizes': [5], 'eval_dataset': 'pw3d_challenge', 'GPUS': 0, 'nw_eval': 2, 'old_version': True, 'output_dir': 'result'}
INFO:root:------------------------------------------------------------------
INFO:root:start building model.
Using ROMP v1
INFO:root:using fine_tune model: /home/jack/Documents/ROMP/trained_models/ROMP_hrnet32.pkl
INFO:root:finished build model.
Traceback (most recent call last):
File "lib/evaluation/collect_3DPW_results.py", line 203, in <module>
submitor = Submit()
File "lib/evaluation/collect_3DPW_results.py", line 15, in __init__
self.collect_3DPW_layout()
File "lib/evaluation/collect_3DPW_results.py", line 39, in collect_3DPW_layout
raw_labels = read_pickle(label_path)
File "lib/evaluation/collect_3DPW_results.py", line 173, in read_pickle
return pickle.load(open(file_path,'rb'),encoding='iso-8859-1')
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by NoLookDefense** [comment]
I am looking forward to your reply. Thank you!

**Comment by Arthur151** [comment]
About opengl visualization problem, here are two possible solutions:
1) You may try to use pyrender in OSMesa mode, which will take advantage of cpu for visualization
https://github.com/Arthur151/ROMP/blob/master/docs/bugs.md#visualization-bug-openglerrorglerror-glerrorerr--12289baseoperation--eglmakecurrent-
2) Here is a [related issue](https://github.com/mmatl/pyrender/issues/86) that might be helpful.

About loading pkl files, please make sure that you get the 3DPW datasets organized as:
3DPW
 - sequenceFiles

**Comment by NoLookDefense** [comment]
Thanks for your explanation! The pkl problem has been solved successfully.
I am going to solve the visualisation problem, but I saw that the commands for ubuntu is a lot messy... I wonder whether how many comments are there and where to press the enter.
<img width="974" alt="Screenshot 2021-04-12 at 19 34 16" src="https://user-images.githubusercontent.com/81567453/114388297-139fc600-9bc6-11eb-9865-2df39fe9b7c1.png">

**Comment by NoLookDefense** [comment]
Oh, I ran the evaluation code successfully. But there's still an error after processing.
I wonder are there anything missed?

pygame 2.0.1 (SDL 2.0.14, Python 3.6.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO:root:{'tab': 'hrnet_cm64_pw3d_challenge', 'configs_yml': 'configs/eval_3dpw_challenge.yml', 'demo_image_folder': 'None', 'local_rank': 0, 'model_version': 1, 'multi_person': True, 'collision_aware_centermap': False, 'collision_factor': 0.2, 'kp3d_format': 'smpl24', 'eval': True, 'max_person': 64, 'input_size': 512, 'Rot_type': '6D', 'rot_dim': 6, 'centermap_conf_thresh': 0.2, 'centermap_size': 64, 'deconv_num': 0, 'model_precision': 'fp32', 'backbone': 'hrnet', 'gmodel_path': '/home/jack/Documents/ROMP/trained_models/ROMP_hrnet32.pkl', 'print_freq': 50, 'fine_tune': False, 'gpu': '0', 'batch_size': 64, 'val_batch_size': 64, 'nw': 4, 'calc_PVE_error': False, 'dataset_rootdir': '/home/jack/Documents/3d_pose_dataset/3dpw', 'high_resolution': True, 'save_best_folder': '/home/jack/Documents/checkpoints/', 'log_path': '/home/jack/Documents/log/', 'total_param_count': 85, 'smpl_mean_param_path': '/home/jack/Documents/ROMP/models/satistic_data/neutral_smpl_mean_params.h5', 'smpl_model': '/home/jack/Documents/ROMP/models/statistic_data/neutral_smpl_with_cocoplus_reg.txt', 'smplx_model': True, 'cam_dim': 3, 'beta_dim': 10, 'smpl_joint_num': 22, 'smpl_model_path': '/home/jack/Documents/ROMP/models', 'smpl_J_reg_h37m_path': '/home/jack/Documents/ROMP/models/smpl/J_regressor_h36m.npy', 'smpl_J_reg_extra_path': '/home/jack/Documents/ROMP/models/smpl/J_regressor_extra.npy', 'kernel_sizes': [5], 'eval_dataset': 'pw3d_challenge', 'GPUS': 0, 'nw_eval': 2, 'old_version': True, 'output_dir': 'result'}
INFO:root:------------------------------------------------------------------
INFO:root:start building model.
Using ROMP v1
INFO:root:using fine_tune model: /home/jack/Documents/ROMP/trained_models/ROMP_hrnet32.pkl
INFO:root:finished build model.
INFO:root:gathering datasets
INFO:root:Loading 3DPW in whole mode, split all
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/flat_guitar_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/flat_packBags_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_upstairs_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_runForBus_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_walking_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_car_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/outdoors_fencing_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_stairs_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_runForBus_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_warmWelcome_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_bar_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_crossStreets_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_weeklyMarket_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/office_phoneCall_00.pkl
lib/evaluation/../../lib/models/../utils/../maps_utils/../dataset/pw3d.py:151: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  all_params[video_name]['betas'] = np.array(data_gt['betas'])
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_walkBridge_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_walkUphill_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_arguing_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_windowShopping_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_sitOnStairs_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_rampAndStairs_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_cafe_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_bus_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_enterShop_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/test/downtown_downstairs_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_basketball_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_shakeHands_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_giveDirections_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_capoeira_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_arguing_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_laceShoe_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_relaxOnBench_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/outdoors_climbing_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_backpack_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_rangeOfMotions_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_goodNews_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/outdoors_freestyle_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/outdoors_slalom_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/outdoors_climbing_02.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_captureSelfies_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_golf_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_box_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/outdoors_slalom_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_warmWelcome_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/outdoors_climbing_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_bodyScannerMotions_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_dancing_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_jacket_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/train/courtyard_relaxOnBench_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/outdoors_parcours_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/downtown_walkDownhill_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/courtyard_rangeOfMotions_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/courtyard_hug_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/outdoors_golf_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/courtyard_jumpBench_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/outdoors_freestyle_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/outdoors_parcours_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/outdoors_crosscountry_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/courtyard_dancing_00.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/courtyard_basketball_01.pkl
Processing:  /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles/validation/courtyard_drinking_00.pkl
INFO:root:3DPW dataset all split total 50534 samples, loading mode whole
Initialization finished!
final results will be saved to  result/R_ROMP_hrnet32/results.zip
Processing 0/790
Processing 60/790
Processing 120/790
Processing 180/790
Processing 240/790
Processing 300/790
Processing 360/790
Processing 420/790
Processing 480/790
Processing 540/790
Processing 600/790
Processing 660/790
Processing 720/790
Processing 780/790
Runtime: 1405.630137681961,per sample 0.027815532867383932
Saving results in  result/R_ROMP_hrnet32
  adding: test/ (stored 0%)
  adding: test/flat_guitar_01.pkl (deflated 34%)
  adding: test/flat_packBags_00.pkl (deflated 34%)
  adding: test/downtown_upstairs_00.pkl (deflated 35%)
  adding: test/downtown_runForBus_01.pkl (deflated 39%)
  adding: test/downtown_walking_00.pkl (deflated 38%)
  adding: test/downtown_car_00.pkl (deflated 49%)
  adding: test/outdoors_fencing_01.pkl (deflated 33%)
  adding: test/downtown_stairs_00.pkl (deflated 35%)
  adding: test/downtown_runForBus_00.pkl (deflated 40%)
  adding: test/downtown_warmWelcome_00.pkl (deflated 36%)
  adding: test/downtown_bar_00.pkl (deflated 41%)
  adding: test/downtown_crossStreets_00.pkl (deflated 41%)
  adding: test/downtown_weeklyMarket_00.pkl (deflated 41%)
  adding: test/office_phoneCall_00.pkl (deflated 41%)
  adding: test/downtown_walkBridge_01.pkl (deflated 42%)
  adding: test/downtown_walkUphill_00.pkl (deflated 33%)
  adding: test/downtown_arguing_00.pkl (deflated 34%)
  adding: test/downtown_windowShopping_00.pkl (deflated 37%)
  adding: test/downtown_sitOnStairs_00.pkl (deflated 35%)
  adding: test/downtown_rampAndStairs_00.pkl (deflated 34%)
  adding: test/downtown_cafe_00.pkl (deflated 42%)
  adding: test/downtown_bus_00.pkl (deflated 61%)
  adding: test/downtown_enterShop_00.pkl (deflated 36%)
  adding: test/downtown_downstairs_00.pkl (deflated 50%)
  adding: train/ (stored 0%)
  adding: train/courtyard_basketball_00.pkl (deflated 37%)
  adding: train/courtyard_shakeHands_00.pkl (deflated 36%)
  adding: train/courtyard_giveDirections_00.pkl (deflated 34%)
  adding: train/courtyard_capoeira_00.pkl (deflated 37%)
  adding: train/courtyard_arguing_00.pkl (deflated 34%)
  adding: train/courtyard_laceShoe_00.pkl (deflated 33%)
  adding: train/courtyard_relaxOnBench_00.pkl (deflated 35%)
  adding: train/outdoors_climbing_00.pkl (deflated 34%)
  adding: train/courtyard_backpack_00.pkl (deflated 33%)
  adding: train/courtyard_rangeOfMotions_00.pkl (deflated 34%)
  adding: train/courtyard_goodNews_00.pkl (deflated 33%)
  adding: train/outdoors_freestyle_00.pkl (deflated 33%)
  adding: train/outdoors_slalom_00.pkl (deflated 34%)
  adding: train/outdoors_climbing_02.pkl (deflated 36%)
  adding: train/courtyard_captureSelfies_00.pkl (deflated 39%)
  adding: train/courtyard_golf_00.pkl (deflated 33%)
  adding: train/courtyard_box_00.pkl (deflated 33%)
  adding: train/outdoors_slalom_01.pkl (deflated 33%)
  adding: train/courtyard_warmWelcome_00.pkl (deflated 49%)
  adding: train/outdoors_climbing_01.pkl (deflated 33%)
  adding: train/courtyard_bodyScannerMotions_00.pkl (deflated 33%)
  adding: train/courtyard_dancing_01.pkl (deflated 39%)
  adding: train/courtyard_jacket_00.pkl (deflated 34%)
  adding: train/courtyard_relaxOnBench_01.pkl (deflated 41%)
  adding: validation/ (stored 0%)
  adding: validation/outdoors_parcours_01.pkl (deflated 34%)
  adding: validation/downtown_walkDownhill_00.pkl (deflated 33%)
  adding: validation/courtyard_rangeOfMotions_01.pkl (deflated 40%)
  adding: validation/courtyard_hug_00.pkl (deflated 40%)
  adding: validation/outdoors_golf_00.pkl (deflated 33%)
  adding: validation/courtyard_jumpBench_01.pkl (deflated 33%)
  adding: validation/outdoors_freestyle_01.pkl (deflated 33%)
  adding: validation/outdoors_parcours_00.pkl (deflated 34%)
  adding: validation/outdoors_crosscountry_00.pkl (deflated 40%)
  adding: validation/courtyard_dancing_00.pkl (deflated 40%)
  adding: validation/courtyard_basketball_01.pkl (deflated 33%)
  adding: validation/courtyard_drinking_00.pkl (deflated 34%)
Saving dir: result/R_ROMP_hrnet32
~~start evaluation~~
submit_dir result/R_ROMP_hrnet32
truth_dir /home/jack/Documents/3d_pose_dataset/3dpw/sequenceFiles
len(fnames_gt),len(fnames_pred):  60 0
Traceback (most recent call last):
  File "pw3d_eval/evaluate.py", line 492, in <module>
    main(submit_dir, truth_dir, output_filename)
  File "pw3d_eval/evaluate.py", line 401, in main
    fnames_gt, fnames_pred = get_paths(submit_dir, truth_dir)
  File "pw3d_eval/evaluate.py", line 389, in get_paths
    assert len(fnames_gt) == len(fnames_pred), print('len(fnames_gt),len(fnames_pred): ',len(fnames_gt),len(fnames_pred))
AssertionError: None

**Comment by Arthur151** [comment]
Yes, the error is pretty clear:
len(fnames_gt),len(fnames_pred): 60 0
assert len(fnames_gt) == len(fnames_pred)
The predicted results didn't get loaded successfully.
Please make sure `result/R_ROMP_hrnet32` has all predictions.

**Comment by NoLookDefense** [comment]
Thank you! Evaluation problem solved. 
BTW, I wonder why a model can generate different results with different devices?

**Comment by Arthur151** [comment]
I think the reason lie in the computation precision. We use AMP (automatic mixed precision) for training.
Better GPU device support half precision, while the normal one doesn't. You can get this character easily after looking into the differences between GPUs.

**Comment by NoLookDefense** [comment]
Thanks for your explanation! Almost all steps are finished successfully, except for the visualisation....
Actually,  it didn't work when I used the pyrender in OSMesa mode as mentioned in . I am wondering that what's your linux and python version, and did you assign with "--no-opengl-files" when you install your nvidia driver?

**Comment by Arthur151** [comment]
Thanks for you interets in our work. 
My Ubuntu is 18.04 LTS. The python is in 3.7.3. I install the nvidia driver via the Software & Update -> additional driver. 
It would be nice if you can run the visualization code in egl mode. 
I am re-building the entire visualization pipeline for better experience. But I still need some time to compare different plans.

**Comment by NoLookDefense** [comment]
> Thanks for you interets in our work.
> My Ubuntu is 18.04 LTS. The python is in 3.7.3. I install the nvidia driver via the Software & Update -> additional driver.
> It would be nice if you can run the visualization code in egl mode.
> I am re-building the entire visualization pipeline for better experience. But I still need some time to compare different plans.

Thank you! You made an outstanding contribution to the society, and I I wish you all the best in the future.

**Comment by NoLookDefense** [comment]
Hey. I have tested that the video can be shown in Ubuntu18.04. The system causes the error.

**Comment by Arthur151** [comment]
Glad to know that it finally works. 
Have a good day!
Best,
Yu Sun
