### ISSUE TITLE
在demo阶段，ROMP_HRNet32_V1.pkl作为pretrained weights，里面有module.final_layers.0.weight和module.final_layers.0.bias两个是使用不同于romp结构的模型pretrain的吗？

### ISSUE THREAD

**Issue by liangwx** [Arthur151/ROMP#340]
运行code的版本信息：
commit 02b9d1d8fe6a9797ea0c25ce75c83c975133dee8
Author: Yu Sun <yusun@stu.hit.edu.cn>
Date:   Fri Jan 21 13:56:09 2022 +0800

**Comment by liangwx** [comment]
@Arthur151

**Comment by Arthur151** [comment]
@liangwx 抱歉才看到这个问题。
是的，请参照这里
https://github.com/Arthur151/ROMP/blob/b108da9e9fe96282d8235a1051a7030d335d9869/romp/lib/models/romp_model.py#L38
final_layers.0估计的是2D keypoint heatmap，只在模型backbone预训练阶段使用，用来帮助模型学到必要的2D pose特征，能显著缩短从0训练的时间。正式学习3D pose的时候就不用了。
