### ISSUE TITLE
[simple-romp] Webcam device number selection

### ISSUE THREAD

**Issue by vivi90** [Arthur151/ROMP#341]
## Problem
https://github.com/Arthur151/ROMP/blob/ff5ea02b2fb524ba55631fc398f722af04e053e4/simple_romp/romp/main.py#L197
The webcam source might not be necessarily number '0'.
Especially if virtual webcam drivers are used.

## Recommended solution
Add command line and configuration option to change the device number.

**Comment by Arthur151** [comment]
Vivian, thanks for your constructive comments. This function has been added in the last commit.

**Comment by vivi90** [comment]
@Arthur151 Please publish this feature as an release at PyPi. 🙂
