### ISSUE TITLE
Details about the format of "results" and "sequence_results" in the output npz file?

### ISSUE THREAD

**Issue by cocoshe** [Arthur151/ROMP#348]
Where can I get the details about it? It seems to be very complex ndarray

**Comment by cocoshe** [comment]
And I just find that my "sequence_results" is empty, but the "results" seems to contain all the png files output?

**Comment by Arthur151** [comment]
Here is the brief introduction about the output:

https://github.com/Arthur151/ROMP/blob/master/docs/config_guide.md#save_dict_results--bool

When the code is running in temporal/tracking mode, sequence_results would not be empty.
