### ISSUE TITLE
关于ROMP在CMU_Panoptic上推理

### ISSUE THREAD

**Issue by xljh0520** [Arthur151/ROMP#352]
您好，我在做CMU_Panoptic的测试时，发现[此处](https://github.com/Arthur151/ROMP/blob/master/romp/lib/dataset/cmu_panoptic_eval.py#L44)的文件夹没有找到。按照[dataset.md](https://github.com/Arthur151/ROMP/blob/master/docs/dataset.md)处理好后的文件结构是这样。请问能提供对应标注解决这个问题嘛？或者是怎么修改dataset.py读取annots.npz的内容？
```
|-- dataset
|   |-- cmu_panoptic
|   |   |-- images
|   |   |-- annots.npz
```

**Comment by Arthur151** [comment]
您好，
这个文件夹在
https://drive.google.com/file/d/1zdaCmc53367CaOOMoBwt6nn5APocX4Rv/view?usp=sharing

**Comment by xljh0520** [comment]
您好，我下载了这个文件，目前是[这里](https://github.com/Arthur151/ROMP/blob/master/romp/test.py#L48)有点问题
```
AttributeError: 'Namespace' object has no attribute 'smpl_J_reg_h37m_path'
```
我尝试用SPIN的[J_regressor_h36m.npy](https://github.com/nkolot/SPIN/tree/master/data)，但最终得到的MPJPE和论文中数据有不少差距，这里是我的log。请问是哪里有问题呢？[cmu_log.txt](https://github.com/Arthur151/ROMP/files/9717305/cmu_log.txt)

**Comment by Arthur151** [comment]
@xljh0520 
您好，关于CMU Panoptic上的评测，建议您使用新版代码：

https://github.com/Arthur151/ROMP/blob/master/simple_romp/evaluation/eval_cmu_panoptic.py

这个更清晰简单，虽然是BEV评测的版本，而且也可以很容易替换成ROMP。

**Comment by neverstoplearn** [comment]
> @xljh0520 您好，关于CMU Panoptic上的评测，建议您使用新版代码：
> 
> https://github.com/Arthur151/ROMP/blob/master/simple_romp/evaluation/eval_cmu_panoptic.py
> 
> 这个更清晰简单，虽然是BEV评测的版本，而且也可以很容易替换成ROMP。 最主要是，BEV的evaluation结果更好一些。

where I can got smpl_J_reg_h37m,thanks.

**Comment by Siroming** [comment]
> 您好， 这个文件夹在 https://drive.google.com/file/d/1zdaCmc53367CaOOMoBwt6nn5APocX4Rv/view?usp=sharing

你好，这个链接过期了，可以发一下新的吗
