### ISSUE TITLE
Missing Function:  'convert_cam_to_3d_trans'

### ISSUE THREAD

**Issue by bpataybac** [Arthur151/ROMP#354]
Using Google Colab get an error message:

!cd /content/ROMP
!python -m romp.predict.image --inputs=demo/images --output_dir=demo/image_results --renderer=pytorch3d --configs_yml=configs/image.yml

Output:
yaml_timestamp  /content/ROMP/active_configs/active_context_2022-10-18_19_57_42.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/ROMP/romp/predict/image.py", line 7, in <module>
    from .base_predictor import *
  File "/content/ROMP/romp/predict/base_predictor.py", line 2, in <module>
    from utils.cam_utils import convert_cam_to_3d_trans
****ImportError: cannot import name 'convert_cam_to_3d_trans' from 'utils.cam_utils'**** (/content/ROMP/romp/lib/models/../utils/cam_utils.py)

**Comment by Arthur151** [comment]
Sorry for that. The Colab demo hasn't been updated with the new version of code. 

Please try 
https://github.com/Arthur151/ROMP/tree/master/simple_romp

It could be install via pip and run in Ubuntu, Window, or Mac.

**Comment by yangqing-20** [comment]
> Using Google Colab get an error message:
> 
> !cd /content/ROMP !python -m romp.predict.image --inputs=demo/images --output_dir=demo/image_results --renderer=pytorch3d --configs_yml=configs/image.yml
> 
> Output: yaml_timestamp /content/ROMP/active_configs/active_context_2022-10-18_19_57_42.yaml Traceback (most recent call last): File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/usr/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/content/ROMP/romp/predict/image.py", line 7, in from .base_predictor import * File "/content/ROMP/romp/predict/base_predictor.py", line 2, in from utils.cam_utils import convert_cam_to_3d_trans ****ImportError: cannot import name 'convert_cam_to_3d_trans' from 'utils.cam_utils'**** (/content/ROMP/romp/lib/models/../utils/cam_utils.py)

hello, could you tell me if you have solved the problem?

**Comment by bpataybac** [comment]
Hi,  Inference works well in an IDE using the command line examples after cloning the Repo.  Thanks so much. Brad
