### ISSUE TITLE
直接复制别人的conda环境，bev命令失效

### ISSUE THREAD

**Issue by Quicksand0** [Arthur151/ROMP#355]
我直接复制了别人的conda环境过来，我们俩的环境路径不一样（之前是Users路径下，我现在是ProgramData路径下）。发现bev命令调用的仍然是之前的路径的python。
![image](https://user-images.githubusercontent.com/22209803/196606813-f79f91ca-b6c3-42b7-9f72-9c2c127e7fc3.png)
请教一下，这个bev调用的python路径怎么能改成我现在的conda环境路径。

**Comment by Arthur151** [comment]
您可以clone这个repo，然后进入simple-romp文件夹里，用您想用的python进行
python setup.py install

**Comment by Quicksand0** [comment]
> 您可以clone这个repo，然后进入simple-romp文件夹里，用您想用的python进行 python setup.py install

可以了，非常感谢。
