### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by FireMonkey796** [Arthur151/ROMP#36]
Hello. Thanks for your work. I am currently conducting some researches on 3d human pose estimation, and I want to consult some concepts. 

I noticed that there are lots of information containing in the pkl files. I am a newcomer in this field, and the values make me confused. For example, I wonder that what's the difference between "pose", "pose2d", "poses_60Hz" and "jointPositions"? And also, there are 5 items containing the information of SMPL including "betas", "betas_clothed" and "pose", and what's their exact meaning?

Or to be simplified, are there any references which can explain such items with exact meanings in details? It will be my pleasure if you are willing to help me!

**Comment by Arthur151** [comment]
These information is well explained in the readme.txt of 3DPW datasets.
- sequence: String containing the sequence name
- betas: SMPL shape parameters for each actor which has been used for tracking (List of 10x1 SMPL beta parameters)
- poses: SMPL body poses for each actor aligned with image data (List of Nx72 SMPL joint angles, N = #frames)
- trans: tranlations for each actor aligned with image data (List of Nx3 root translations)
- poses_60Hz: SMPL body poses for each actor at 60Hz (List of Nx72 SMPL joint angles, N = #frames)
- trans_60Hz: tranlations for each actor at 60Hz (List of Nx3 root translations)
- betas_clothed: SMPL shape parameters for each clothed actor (List of 10x1 SMPL beta parameters)
- v_template_clothed:
- gender: actor genders (List of strings, either 'm' or 'f')
- texture_maps: texture maps for each actor
- poses2D: 2D joint detections in Coco-Format for each actor (only provided if at least 6 joints were detected correctly)
- jointPositions: 3D joint positions of each actor (List of Nx(24*3) XYZ coordinates of each SMPL joint)
- img_frame_ids: an index-array to down-sample 60 Hz 3D poses to corresponding image frame ids
- cam_poses: camera extrinsics for each image frame (Ix4x4 array, I frames times 4x4 homegenous rigid body motion matrices)
- campose_valid: a boolean index array indicating which camera pose has been aligned to the image
- cam_intrinsics: camera intrinsics (K = [f_x 0 c_x;0 f_y c_y; 0 0 1])

**Comment by FireMonkey796** [comment]
Thank you! I just missed it. The concept are getting clearer. 
But what's the relationship between the items with and without 60Hz? Like poses and poses_60Hz, trans and trans_60Hz

**Comment by FireMonkey796** [comment]
I also find that the value of "pose2d" are integers which I think it's the exact position within the image. 
But as for "poses" and "poses_60Hz", the values are constrained within (-1, 1). I wonder what's the actual meaning of these values?

**Comment by Arthur151** [comment]
The 3DPW dataset could be freely downloaded from [the website](https://virtualhumans.mpi-inf.mpg.de/3DPW/).
You can dig into the details of the annotations if you download it.
