### ISSUE TITLE
Why is the betas  of BEV output in 11 dimensions instead of 10 dimensions? 

### ISSUE THREAD

**Issue by sycamore27** [Arthur151/ROMP#362]
Why is the betas  of BEV output in 11 dimensions instead of 10 dimensions? 
Which ten numbers represent the betas of SMPL? Thank you!

**Comment by hosseinfeiz** [comment]
you can consider only the first 10 components without a problem

**Comment by sycamore27** [comment]
> 

Got it, thank you very much

**Comment by Arthur151** [comment]
@sycamore27 
Thanks, @hosseinfeiz .Yes, The first ten dimensions is the SMPL betas. 
The 11-th dimension represents the kid offset. It is supposed to be 1 for the adults, 0 for the baby. It shows the interpolation between the adult shape space and baby shape space. The teenager is in-between them, like 0.5.
