### ISSUE TITLE
请问您论文中Figure 4的结果的测试视频可以分享一下吗？

### ISSUE THREAD

**Issue by liangwx** [Arthur151/ROMP#369]
保持分辨率不变，仅仅改变人数（且整个视频时长中的人数各自保持不变）的测试视频似乎不太好搜集

**Comment by liangwx** [comment]
另外您论文中table7与fig4中的webcam采集的视频的分辨率是多少？虽然随机分辨率在送入network之前都会resize到512，但是不同分辨率似乎会影响预处理的速度，进而影响到FPS

**Comment by Arthur151** [comment]
我是在crowdpose上测试的，图片中的人数就是标注数量。记录处理每个图片的时间，统计在不同人数图片上的FPS平均值。
我的相机是720p(720x480)的低分辨率相机。
