### ISSUE TITLE
save_mesh in video

### ISSUE THREAD

**Issue by alighofrani95** [Arthur151/ROMP#37]
First of all thanks a lot for this great repo

How can I export .obj file of a video ?

by change save_mesh to True nothing generate?

How can I save mesh of all video frames In one .fbx file? (Just like vibe repo https://github.com/mkocabas/VIBE
https://github.com/mkocabas/VIBE/blob/c0c3f77d587351c806e901221a9dc05d1ffade4b/lib/utils/fbx_output.py)

or How can I concat all .obj file by exporting via image config (not video) as one .fbx file?

I've try to use the .npy file of video to ROMP/src/lib/utils/convert_fbx.py and generate .fbx file but the generated file doesn't consist of any animation in belender.

Could you please help to solve this issue.

**Comment by alighofrani95** [comment]
> First of all thanks a lot for this great repo
> 
> How can I export .obj file of a video ?
> 
> by change save_mesh to True nothing generate?
> 
> How can I save mesh of all video frames In one .fbx file? (Just like vibe repo https://github.com/mkocabas/VIBE
> https://github.com/mkocabas/VIBE/blob/c0c3f77d587351c806e901221a9dc05d1ffade4b/lib/utils/fbx_output.py)
> 
> or How can I concat all .obj file by exporting via image config (not video) as one .fbx file?

I've try to use the .npy file of video to ROMP/src/lib/utils/convert_fbx.py and generate .fbx file but the generated file doesn't consist of any animation in belender.

Could you please help to solve this issue.

**Comment by Arthur151** [comment]
I have solved the mentioned issues via a new commit. 
Now the `save_mesh` is effective.

About FBX animation please refer to [export-to-blender-fbx](https://github.com/Arthur151/ROMP#export-to-blender-fbx).

Here  is the demo:
![fbx_animation](https://user-images.githubusercontent.com/17900300/115501944-b501d880-a2a6-11eb-85d8-2242c3d8df4a.gif)
