### ISSUE TITLE
How to get the results like blender_character_driven-min.gif using ROMP?

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#370]
Hello, thank you for your great jobs. I want to drive some characters like yours in blender_character_driven-min.gif. Can you tell me how to realize it? Thank you.

**Comment by caihaunqai** [comment]
> Hello, thank you for your great jobs. I want to drive some characters like yours in blender_character_driven-min.gif. Can you tell me how to realize it? Thank you.

![image](https://user-images.githubusercontent.com/56779804/204211560-be5264b1-c9bb-4652-893c-f409e1f263ef.png)

**Comment by Arthur151** [comment]
@caihaunqai This would be helpful:
https://github.com/yanchxx/CDBA
