### ISSUE TITLE
请问如何可视化预测的mesh结果？

### ISSUE THREAD

**Issue by QiAnBozZ** [Arthur151/ROMP#372]
您好，仓中的romp\lib\visualization是不是可视化的部分？我现在想把在3DPW上预测的mesh渲染一下投影到图片上，请问有没有可以直接运行的启动指令？
万分感谢~!

**Comment by Arthur151** [comment]
可以参考这个
https://github.com/Arthur151/ROMP/blob/master/simple_romp/vis_human/
里面有不同可视化库的封装函数，比如pyrenderer
pyrenderer.py

**Comment by QiAnBozZ** [comment]
好的，谢谢！

**Comment by QiAnBozZ** [comment]
好的，谢谢！
此外，请问[https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/vis_human/pyrenderer.py#L42](url)这一行的triangle改如何生成呢？对于SMPL生成的皮肤顶点，这一个值应该是相同的吧。

**Comment by Arthur151** [comment]
是的，就是SMPL里的face，表示三角面片的连接关系。

**Comment by QiAnBozZ** [comment]
> > 是的，就是SMPL里的face，表示三角面片的连接关系。
> 
> 好的，已经找到了。 我还有一个疑问，ROMP预测的应该是一个标准坐标系下的mesh坐标，那么如何将结果转换到真实的坐标系下并映射到图像上呢？

或者说pw3d数据集有标注绝对的深度吗

**Comment by Arthur151** [comment]
这需要估计相机的内外参，可以用pnp来转化到真实坐标系里。PW3D没有提供准确的绝对深度标注。
