### ISSUE TITLE
Training datasets

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#373]
Hello, thanks for your excellent job. Your illustratement is quite helpful, especially about the training dataset. I want to train ROMP by myself. I wonder if the datasets in the directory structure are the whole training datasets. Since I found that UP、AICH、OH are listed on the paper, none of them appear in the directory. Need we download them by ourselves or they have been uploaded in the google drive you provide? Thank you for your help.

**Comment by caihaunqai** [comment]
发现好多伙伴用中文交流哈，感谢作者哈，感觉工作做的很全～对新手很友好

**Comment by Arthur151** [comment]
Thanks for your kind words. 
@caihaunqai 
是的，有些数据集因为各种原因，就没有开源出来，不过目前开源的训练集已经足够训练，并进行与其他方法的对比实验了。
如果您想重新训练的话，建议您可以从我们提供的预训练参数/HigherHRNet(HRNet-32)的预训练参数开始,他们都进行了2D pose的训练，这部分预训练对于最后的性能、收敛的影响还是挺大的。
如果遇到问题，欢迎随时交流。

**Comment by caihaunqai** [comment]
> Thanks for your kind words. @caihaunqai 是的，有些数据集因为各种原因，就没有开源出来，不过目前开源的训练集已经足够训练，并进行与其他方法的对比实验了。 如果您想重新训练的话，建议您可以从我们提供的预训练参数/HigherHRNet(HRNet-32)的预训练参数开始,他们都进行了2D pose的训练，这部分预训练对于最后的性能、收敛的影响还是挺大的。 如果遇到问题，欢迎随时交流。

感谢回复，主要是遇到测试的时候有一些遮挡的相关问题，希望能否通过自己的训练得到改善，不知您是否有相关的建议？ 看到论文里其实有对遮挡进行优化，并且有一些EFT的合成数据，应该是对遮挡有一定的作用。主要想尝试在单人的场景，做一些动作的时候遇到的局部遮挡，例如转身时部分手部肢体是遮挡的。

**Comment by Arthur151** [comment]
自遮挡问题确实是一个目前方法难以解决的挑战
如果针对特定场景制作训练集然后调优模型确实会有改善的。如果只是去除抖动的话，之前提到的-t -sc=1就能明显改善。

**Comment by caihaunqai** [comment]
> 自遮挡问题确实是一个目前方法难以解决的挑战 如果针对特定场景制作训练集然后调优模型确实会有改善的。如果只是去除抖动的话，之前提到的-t -sc=1就能明显改善。

明白～请问-t -sc=1是使用什么方法进行防抖呢？

**Comment by Arthur151** [comment]
可以适当看一下代码实现，simple-romp还是很简洁的
