### ISSUE TITLE
测试数据集采集问题

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#374]
您好，想测试相关工作的实际表现，我用手机直接拍摄了一些视频，用ROMP进行预估，但是渲染出来的结果抖动比较明显，并且手部与身体接触的时候有穿模的现象，但人侧面行走的时候，被遮挡的手会预估错误。想请问是否输入的视频有一定的拍摄要求以及预处理（比如图像的大小等），或者是否需要添加一些后处理进行改善？ 感谢，期待回复！

**Comment by Arthur151** [comment]
@caihaunqai 
感谢您的建议，确实，ROMP在一些场景的表现还不太理想，我们在后续工作也在优化这些问题，目前的simple-romp有动作平滑方面的设置，运行的时候加上
-t -sc=3 可能好些，sc越小越平滑。
记得更新到最新的版本
pip install --upgrade simple-romp==1.0.6

**Comment by caihaunqai** [comment]
感谢！
