### ISSUE TITLE
About Multi-view

### ISSUE THREAD

**Issue by leviome** [Arthur151/ROMP#376]
Thanks for sharing the nice work!
This monocular method achieved impressive results, but in my opinion, multi-view will definitely improve the final performance.
Do you have any thoughts to upgrade ROMP to multi-view?

**Comment by Arthur151** [comment]
Hi, @leviome ,

Thanks for your kind words.  

Yes, I could imagine how popular multi-view ROMP would be. 
I have some thoughts about this direction, but they are not qualified to be the right solution. 

The idea of this paper might be helpful.
https://github.com/AlvinYH/Faster-VoxelPose

**Comment by leviome** [comment]
Thank you! Expecting your awesome work on multi-view pose estimation!
