### ISSUE TITLE
How to get the 3d position of the SMPL template in a image?

### ISSUE THREAD

**Issue by cocoshe** [Arthur151/ROMP#377]
Thanks for your great work!
I wanna ask how to get the 3d position of the SMPL template in a image like this in README, for example, I want to draw the SMPL of the person on the right bottom of the image, I think I need to use the `beta`, `pose` and `cam_trans`? Maybe I should use smpl model to get vertex first, or I only need to translate the `global_orient` by `trans`? I don't know clearly how to transform to the camera coordinate system, can you show me the code about this part? 
![image](https://user-images.githubusercontent.com/69197635/205330790-d1fcff97-ccff-44f4-a174-1268ce1127f8.png)

BTW, I noticed the code here in `convert2fbx.py` seemed to calculate the absolute 3D position of the global_orient, can you explain why the indexs are `1,2,0` instead of `0,1,2`? and what the `100` scaler mean?

https://github.com/Arthur151/ROMP/blob/master/simple_romp/tools/convert2fbx.py#L170

**Comment by cocoshe** [comment]
https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/romp/lib/visualization/vedo_visualizer.py#L94

I find the code here just now, it seems that I use the `betas` and `pose` to get the SMPL, then just add the vertex position and camera translation directly, it is right?

**Comment by Arthur151** [comment]
@cocoshe 
Thanks for your interests in ROMP/BEV.
About projecting 3D mesh/joints to image plane, it is implemented at 

ROMP - weak perspective camera :
https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/romp/main.py#L168
https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/romp/post_parser.py#L104
BEV - predefined perspective camera :
https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/bev/main.py#L174
https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/bev/post_parser.py#L140

About exporting fbx to Blender:
In our camera space of all predicitons, we take X-Right, Y-Up, Z-Forward
While Blender have a different coordinate defination, we convert to theirs via 1,2,0.
*100 is to convert the results (mesh vertex) from meter (m) to cm used by Blender.

**Comment by cocoshe** [comment]
> @cocoshe Thanks for your interests in ROMP/BEV. About projecting 3D mesh/joints to image plane, it is implemented at
> 
> ROMP - weak perspective camera :
> 
> https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/romp/main.py#L168
> 
> 
> https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/romp/post_parser.py#L104
> 
> 
> BEV - predefined perspective camera :
> https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/bev/main.py#L174
> 
> 
> https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/bev/post_parser.py#L140
> 
> About exporting fbx to Blender: In our camera space of all predicitons, we take X-Right, Y-Up, Z-Forward While Blender have a different coordinate defination, we convert to theirs via 1,2,0. *100 is to convert the results (mesh vertex) from meter (m) to cm used by Blender.

Thanks, it worked on my test. That really helps!
Besides, I wan't to ask a stupid question, why the joints shape and pose shape both are [N, 71, 3]? It's because the global orient? (Why not [N, 72, 3], since 24*3=72)

**Comment by Arthur151** [comment]
What do you mean both are of shape [N,71,3]? Do you refer to the predictions in saved npz output file?
The smpl pose parameters are saved in the name of 'smpl_thetas'. Of course, the shape of joints and SMPL pose parameters are different.

**Comment by cocoshe** [comment]
> What do you mean both are of shape [N,71,3]? Do you refer to the predictions in saved npz output file? The smpl pose parameters are saved in the name of 'smpl_thetas'. Of course, the shape of joints and SMPL pose parameters are different.

Seems that I misunderstood the meanings of `smpl_thetas` and `body_pose`, where can I get the detail meanings of romp output pkl file? Thanks again.

**Comment by Arthur151** [comment]
This is the old document about the saved file:

https://github.com/Arthur151/ROMP/blob/master/docs/config_guide.md#save_dict_results--bool

**Comment by cocoshe** [comment]
Thanks for all your reply👍
