### ISSUE TITLE
Can we improve the model with MTP and DSC？

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#378]
Hello, thank you for your good job. I wonder if we can improve the model to process some bad cases, like self-contact or occlusions, by adding MTP and DSC datasets? I find that they have some similar situations. Will you consider adding it to the ROMP training model if it can?  Thank you.

**Comment by Arthur151** [comment]
Both ROMP/BEV can be improved in self-contact or occlusions via learning from corresponding cases. But I am not sure about which datasets you are referring to. I am not familiar with MTP and DSC dataset. 
Anyway, current model is not well trainied to prevent self-interpolation. But it worth a try to model such important factors. If you want to discuss the details, I'd like to coorporate for further exploration.

**Comment by caihaunqai** [comment]
> Both ROMP/BEV can be improved in self-contact or occlusions via learning from corresponding cases. But I am not sure about which datasets you are referring to. I am not familiar with MTP and DSC dataset. Anyway, current model is not well trainied to prevent self-interpolation. But it worth a try to model such important factors. If you want to discuss the details, I'd like to coorporate for further exploration.

Thank you for your reply. I have downloaded MTP and DSC. MTP is Mimic The Pose, and  DSC is Discrete self-contact. They can be found on https://tuch.is.tue.mpg.de/Datasets.php. Both of them are datasets about self-interpolation, which you can find on On Self-Contact and Human Pose.  I have just downloaded them. But I am not sure if I should change their data format to fit in the ROMP training datasets.  I will appreciate it if you are interested in improving ROMP's self-interpolation cases.

**Comment by Arthur151** [comment]
Sure, you can see the guidance at
https://github.com/Arthur151/ROMP/blob/master/docs/train.md#training-guidance
2.Training with your own datasets:

**Comment by caihaunqai** [comment]
> Sure, you can see the guidance at https://github.com/Arthur151/ROMP/blob/master/docs/train.md#training-guidance 2.Training with your own datasets:

Do you think it's easier to train from scratch or fine-tune on ROMP's trained model? If fine-tuning, is it better to use only MTC and DSC or add all datasets including the datasets you use?

**Comment by Arthur151** [comment]
Fine-tunning would be the better and easier choice. It is better to train MTC and DSC with other dataset to prevent overfitting.

**Comment by caihaunqai** [comment]
Thank you. I will have a try.

**Comment by caihaunqai** [comment]
Thanks.
