### ISSUE TITLE
About bpy environment

### ISSUE THREAD

**Issue by NoLookDefense** [Arthur151/ROMP#38]
Hey bro. I am coming again for the another problem.
I want to run the new feature which can export the mesh to .fbx file, and it seems that "bpy" package is needed to download. But when I use _pip install bpy_, some CMake error always occurs. 
I wonder that which version of CMake you are using when you install bpy?

**Comment by Arthur151** [comment]
cmake version 3.10.2
Thanks for your attension.

**Comment by NoLookDefense** [comment]
> cmake version 3.10.2
> Thanks for your attension.

And how about the bpy version?

**Comment by Arthur151** [comment]
bpy 2.91a0

**Comment by NoLookDefense** [comment]
Complete the same. But I meet error while importing bpy. I am using ubuntu18.04 and python 3.7.10

(romp) user@user-System-Product-Name:~/Documents/ROMP/src$ python lib/utils/convert_fbx.py --input=../demo/videos/sample_video2_results/sample_video2_results.npz --output=../demo/videos/sample_video2.fbx --gender=female
Color management: using fallback mode for management
Color management: Error could not find role data role.
BLT_lang_init: 'locale' data path for translations not found, continuing
Color management: scene view "Filmic" not found, setting default "Standard".
blf_load_font_default: 'fonts' data path not found for 'droidsans.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
blf_load_font_default: 'fonts' data path not found for 'bmonofont-i18n.ttf', will not be able to display text
bpy: couldn't find 'scripts/modules', blender probably wont start.
Freestyle: couldn't find 'scripts/freestyle/modules', Freestyle won't work properly.
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
ModuleNotFoundError: No module named 'bpy_types'
ERROR (bpy.rna): /Blender/blender/source/blender/python/intern/bpy_rna.c:7236 pyrna_srna_ExternalType: failed to find 'bpy_types' module
F0507 10:25:17.279358 13523 utilities.cc:346] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
*** Check failure stack trace: ***
    @     0x7f64758057dd  google::LogMessage::Fail()
    @     0x7f64758076e3  google::LogMessage::SendToLog()
    @     0x7f647580536d  google::LogMessage::Flush()
    @     0x7f6475807fb9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f647580c6aa  google::glog_internal_namespace_::InitGoogleLoggingUtilities()
    @     0x7f6474fee519  libmv_initLogging
    @     0x7f64742b5767  main_python_enter
    @     0x7f647493f25b  bpy_module_delay_init
    @     0x7f647493f29d  dealloc_obj_dealloc
    @     0x55946d3aeda2  PyDict_SetItem
    @     0x55946d3af86f  PyDict_SetItemString
    @     0x55946d3b03cb  PyModule_AddObject
    @     0x55946d47a821  _PyImport_LoadDynamicModuleWithSpec
    @     0x55946d47a9a9  _imp_create_dynamic
    @     0x55946d3816a2  _PyMethodDef_RawFastCallDict
    @     0x55946d3817c1  _PyCFunction_FastCallDict
    @     0x55946d41dbd9  _PyEval_EvalFrameDefault
    @     0x55946d35fd09  _PyEval_EvalCodeWithName
    @     0x55946d3b00b7  _PyFunction_FastCallKeywords
    @     0x55946d41cae9  _PyEval_EvalFrameDefault
    @     0x55946d3afe2b  _PyFunction_FastCallKeywords
    @     0x55946d4186f0  _PyEval_EvalFrameDefault
    @     0x55946d3afe2b  _PyFunction_FastCallKeywords
    @     0x55946d418466  _PyEval_EvalFrameDefault
    @     0x55946d3afe2b  _PyFunction_FastCallKeywords
    @     0x55946d418466  _PyEval_EvalFrameDefault
    @     0x55946d3afe2b  _PyFunction_FastCallKeywords
    @     0x55946d418466  _PyEval_EvalFrameDefault
    @     0x55946d360d2b  _PyFunction_FastCallDict
    @     0x55946d37fa9e  object_vacall
    @     0x55946d3d9c0d  _PyObject_CallMethodIdObjArgs
    @     0x55946d36948c  PyImport_ImportModuleLevelObject
Aborted (core dumped)

Have you met such a problem before?

**Comment by Arthur151** [comment]
It is the bug of bpy. I have also met this before. 
Here is a [solution](https://github.com/TylerGubala/blenderpy/issues/13) that worked for me.

**Comment by NoLookDefense** [comment]
But the .fpx file is exported successfully. Is the error matters?

**Comment by Arthur151** [comment]
Your problem seems to be how to use the Blender... 
You can rotate the view by pressing the Middle mouse button and moving..
The 'strange triangle' is his bone. You can choose to hide it through manipulating the scene collection (at the top right).

**Comment by NoLookDefense** [comment]
Thanks for your help! It runs!

**Comment by NoLookDefense** [comment]
> I am really happy that you finally made it.
> It seems that you are unfamiliar with the Blender...
> You can rotate the view by pressing the Middle mouse button and moving..
> The 'strange triangle' you mentioned is his bone. You can choose to hide it through manipulating the scene collection (at the top right).

BTW, there is another problem I want to mention. Will the .fbx model compatible with Unity?

**Comment by Arthur151** [comment]
Here is a portable way: export the Blender fbx model to fbx compatible with Unity.
Here is  a video which introduce this simple action.
**https://www.youtube.com/watch?v=ysl0qYq5p9w**

Or here is a tutorial with more detail settings:
https://gamedevacademy.org/how-to-import-blender-models-into-unity-your-one-stop-guide/

Have a nice day.
