### ISSUE TITLE
Pytorch3d import error.

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#380]
Hello, I have followed all your installation instructions to train. However,  I meet this error, which you can see it in the picture. I try to solve it but it does not work. 
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/56779804/206072142-ac51bb86-7e44-4f59-8923-9a4d662c5777.png">

**Comment by Arthur151** [comment]
Please make sure that you have successfully install CUDA 10.2.
The sign is when you type `nvcc -V` in terminal, there should be something like this shows up:
```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_18:23:41_PST_2022
Cuda compilation tools, release 10.2, V10.2.***
```

**Comment by caihaunqai** [comment]
> Please make sure that you have successfully install CUDA 10.2. The sign is when you type `nvcc -V` in terminal, there should be something like this shows up:
> 
> ```
> $ nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Thu_Feb_10_18:23:41_PST_2022
> Cuda compilation tools, release 10.2, V10.2.***
> ```

Can I skip this visualizer and train first? When I solve this problem, I will add it.

**Comment by caihaunqai** [comment]
My CUDA is 11.1.

**Comment by Arthur151** [comment]
Yes, pytorch3D is used to visualize the results during training. I am afraid you can skip it. 
You can install multiple version of CUDA via change the .bashrc file.It is quite easy. I provide the simplest way to install pytorch3D. You can also build pytorch3D from source, then you can use any CUDA version you want. But this process is a bit complicated.

**Comment by caihaunqai** [comment]
> Yes, pytorch3D is used to visualize the results during training. I am afraid you can skip it. You can install multiple version of CUDA via change the .bashrc file.It is quite easy. I provide the simplest way to install pytorch3D. You can also build pytorch3D from source, then you can use any CUDA version you want. But this process is a bit complicated.

It is so kind of you. Is the second way to build pytorch3D from source as follows, which I have tried before? I use Linux.
![image](https://user-images.githubusercontent.com/56779804/206080784-8cc99c03-520b-4015-8be6-64e4a625a972.png)

**Comment by Arthur151** [comment]
Please refer to pytorch3D to build from source

**Comment by caihaunqai** [comment]
Ok, thank you.
