### ISSUE TITLE
No such file or directory: '/root/.romp/SMPL_FEMALE.pth'

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#381]
Hello, where can I download SMPL_FEMALE.pth? I met the following error. Is it the same as basicModel_f_lbs_10_207_0_v1.0.0.pkl? Thank you. 

FileNotFoundError: [Errno 2] No such file or directory: '/root/.romp/SMPL_FEMALE.pth'

**Comment by Arthur151** [comment]
Here you go:
https://github.com/Arthur151/ROMP/releases/tag/V2.0
