### ISSUE TITLE
Multi gpu use error

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#382]
Sorry to bother you again. I try to use 4 gpu cards to accelerate and add the batch size. I change the config file as follows. But I meet the error, ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set.  Is it need to train with "-m torch.distributed.launch" as usual? 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/56779804/206082794-660803ce-a8c9-4776-a4fc-f10f1d443e37.png">
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/56779804/206083109-f56eb811-dcd3-4cee-a919-47128ae4e693.png">

**Comment by Arthur151** [comment]
Please don't use distribute training. It's not stable now.
    	获取 Outlook for iOS
    
  

 发件人: ***@***.*** ***@***.***> 代表 caihaunqai ***@***.***>发送时间: 星期三, 十二月 7, 2022 11:46 上午收件人: Arthur151/ROMP ***@***.***>抄送: Subscribed ***@***.***>主题: [Arthur151/ROMP] Multi gpu use error (Issue #382) 
Sorry to bother you again. I try to use 4 gpu cards to accelerate and add the batch size. I change the config file as follows. But I meet the error, ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set.  Is it need to train with "-m torch.distributed.launch" as usual?

**Comment by caihaunqai** [comment]
OK. Thank you.
