### ISSUE TITLE
How to inference with trained model?

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#383]
Hello, thank you for your excellent job. I use the following code to inference successfully. But I do not find the default setting. How can I choose the model trained by myself?  Thank you.
<img width="854" alt="image" src="https://user-images.githubusercontent.com/56779804/206613398-3c9dc1f9-653f-40b7-8e60-e093230be82b.png">

**Comment by Arthur151** [comment]
@caihaunqai 
Here is it:

https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/romp/main.py#L37

Please add `--model_path=/path/to/ROMP_model.pth` during inference

Please note that you need to convert the model you trained to the format simple-romp used.

https://github.com/Arthur151/ROMP/tree/master/simple_romp#convert-checkpoints

**Comment by caihaunqai** [comment]
Thank you!
