### ISSUE TITLE
Why render mesh move up wrongly?

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#384]
Hello, I have used simle_romp to inference using my trained model. But the render results move up a little. Is there any wrong setting?
<img width="216" alt="image" src="https://user-images.githubusercontent.com/56779804/206616848-06921faa-b44a-4a0a-a47b-966caf761457.png">

**Comment by Arthur151** [comment]
@caihaunqai 
This is effected by root alignment operation at 

https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/romp/smpl.py#L102

Please consider to set it to True/False. It would be right. 
After change made, please re-install simple romp via:
```
pip uninstall simple-romp
cd simple_romp/
python setup.py install 
```

**Comment by AceCHQ** [comment]
Thank you. I have tried it and it works.

**Comment by caihaunqai** [comment]
Thank you. It works.
