### ISSUE TITLE
How can I convert other datasets to fit the ROMP input?

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#385]
Hello, thank you for your excellent job. I want to add another dataset, like MTC, into training datasets. However, I find the dataset files are complex in the romp/lib/dataset. Do I need to write a dataset file from scratch by myself considering the new dataset's parameters? Or do I have any convenient way to add new datasets?  Thank you.

**Comment by Arthur151** [comment]
I am afaid you have to add a new dataset file following 

https://github.com/Arthur151/ROMP/blob/master/docs/train.md#training-guidance

Maybe you can follow the format of 
https://github.com/Arthur151/ROMP/blob/master/romp/lib/dataset/mpi_inf_3dhp.py
as the template to properly `pack_data` and define `get_image_info`.

**Comment by caihaunqai** [comment]
Thank you.
