### ISSUE TITLE
The usage of EFT dataet

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#386]
您好，咨询您关于EFT伪标注的问题。看到EFT是把2D标注转为3D的标注，请问finetune的时候，加上2D的EFT伪标注会更好吗？还是直接在3D数据上finetune效果更好？另外在EFT的paper里看到加上剧烈的crop可以使得结果更好。请问在ROMP里可以添加吗？谢谢。

**Comment by Arthur151** [comment]
我们实验发现，加上EFT的伪标注对效果会有一点帮助，现在的训练代码里已经加上了。ROMP里也有crop的部分，您可以调节crop的尺度来制造"剧烈crop"的sample。就是调节每个数据集文件里的scale_range:
https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/romp/lib/dataset/h36m.py#L17

**Comment by Arthur151** [comment]
你可以自己调整一下感受一下，：

https://github.com/Arthur151/ROMP/blob/master/docs/dataset.md#test-the-data-loading

上述会调用这里的函数可视化
https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/romp/lib/dataset/h36m.py#L140

**Comment by Arthur151** [comment]
如果您单独设立一个这个场景的validation set，这个问题就不存在了。

**Comment by caihaunqai** [comment]
> 如果您单独设立一个这个场景的validation set，这个问题就不存在了。

明白了，感谢！
