### ISSUE TITLE
The usage of Synthetic_occlusion_ratio?

### ISSUE THREAD

**Issue by AceCHQ** [Arthur151/ROMP#388]
Hello, I found the code of synthetic_occlusion was abandoned. Can I use it for synthetic occlusion？ Thank you.

<img width="976" alt="image" src="https://user-images.githubusercontent.com/104981253/207245770-100bd91c-2897-4977-9359-872d822c9981.png">

**Comment by Arthur151** [comment]
@AceCHQ
Sure, this function is brought from 
https://github.com/isarandi/synthetic-occlusion/blob/master/augmentation.py

It is still kept in https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/romp/lib/utils/augments.py#L347

You can use it to insert occlusion object into the image if you want.

**Comment by caihaunqai** [comment]
Thank you. Have you try it before? Can it get some improvements for occlusion situation?

**Comment by AceCHQ** [comment]
> @AceCHQ Sure, this function is brought from https://github.com/isarandi/synthetic-occlusion/blob/master/augmentation.py
> 
> It is still kept in
> 
> https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/romp/lib/utils/augments.py#L347
> 
> You can use it to insert occlusion object into the image if you want.

Thank you. Have you try it before? Can it get some improvements for occlusion situations?

**Comment by Arthur151** [comment]
Yes, I have tried it. But for fair comparison with other methods, I didn't use it during experiments. 
I can't say whether it makes improment.

**Comment by caihaunqai** [comment]
Thank you. I will try it and I will response to you if it has improvements.
