### ISSUE TITLE
部分帧突变的问题

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#389]
您好，在运行ROMP的时候发现有时候简单的场景会发生动作的突变，想请问是否有什么策略或者后处理方法可以解决，比如伸直的手臂有时候突然弯曲之类的，只是少数帧。谢谢您！

**Comment by caihaunqai** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/56779804/207557023-7dcb7575-5e69-498e-b786-a247ee48e939.png">

**Comment by Arthur151** [comment]
可以考虑算一下关节角的角加速度 或关节点位置的加速度，然后滤除与临近帧加速度过大的帧
