### ISSUE TITLE
Hands of SMPL from ROMP

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#391]
Hello, thank you for your excellent job. I find that ROMP drop the last two hand joints in the paper. Is it means that our final FBX results converted from pkl do not have hands? But I find that the shape of smpl_thetas is (1, 72).  Is it mean that our results have hands? Thank you.

**Comment by Arthur151** [comment]
Sorry, I just pad zeros (1,6) to complete estimated body poses (1,66) to (1,72). We don't support hand pose estimation for now.
