### ISSUE TITLE
Can not find tools/bpy-2.82.1

### ISSUE THREAD

**Issue by AceCHQ** [Arthur151/ROMP#392]
Hello, I found the file convert2fbx.py containing "tools/bpy-2.82.1", but I can not find it. Can you share me? Thank you.

**Comment by Arthur151** [comment]
Oh, that doesn't work anymore, so I delete it. 
Maybe this would help, I haven't try it yet:
https://github.com/TylerGubala/blenderpy/releases
But there should be many related project about this.

**Comment by AceCHQ** [comment]
Thank you.
