### ISSUE TITLE
Can simple_romp render the mesh on a blank image, not the original one?

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#393]
Hello, thank you for your excellent job. I wonder if I can render the mesh on a blank image, not the original one? Need I modify the code to achieve it? Thank you.

**Comment by Arthur151** [comment]
Sure, you just need to replace the image 
https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/romp/main.py#L171
with a blank image like 
outputs = rendering_romp_bev_results(self.renderer, outputs, np.zeros_like(image), rendering_cfgs)

**Comment by AceCHQ** [comment]
Thank you. I have tried it, but it didn't work.

**Comment by caihaunqai** [comment]
Thank you. I have tried it, but it didn't work.

**Comment by Arthur151** [comment]
After change the simple_romp/romp/main.py, did you use the changed simple-romp via re-install the edited code?
```
pip uninstall simple-romp
cd simple_romp/
python setup.py install
```
p.s. this is just for romp, if you want to do the same thing for bev, please change the corresponding position of bev/main.py
