### ISSUE TITLE
Why the evaluation results of 3DPW of my finetune model is quite bad?

### ISSUE THREAD

**Issue by AceCHQ** [Arthur151/ROMP#396]
Hello, I have evaluated the model you provide, which is similar to the one shown in the paper. However, the model finetuned by myself is quite bad. Do I have anything wrong in evaluating it? But its prediction outputs are normal. 
<img width="465" alt="image" src="https://user-images.githubusercontent.com/104981253/208915426-a4733d45-e31f-4729-95cb-98f83e76d42e.png">

**Comment by Arthur151** [comment]
I guess you didn't convert the trained model to the proper format via
https://github.com/Arthur151/ROMP/tree/master/simple_romp#convert-checkpoints
Please check whether the model is properly loaded.
