### ISSUE TITLE
如何驱动我自己的smpl模型

### ISSUE THREAD

**Issue by Yuanhong200727** [Arthur151/ROMP#399]
您好，感谢您如此优秀的项目！
我想借助您的项目，通过实时的预测去驱动我自己的smpl模型，请问我该怎么做？

**Comment by Arthur151** [comment]
如果已知一个特定人的SMPL模型的beta形状参数，那么我们只需要使用ROMP实时估计出姿态参数，即可驱动该特定人的smpl模型。

**Comment by Yuanhong200727** [comment]
原谅我是SMPL的初学者，姿态参数控制人体的姿态，请问我该如何获取24个关节点的空间位置坐标去改变我的smpl模型在空间中的位置呢？还是说有其他的方法去改变特定模型的空间位置？还请指教

**Comment by Yuanhong200727** [comment]
我安装了simple_romp并在本地完美运行，请问我该如何修改代码来输出每一帧所有关节点的3D位置和姿态参数呢

**Comment by Arthur151** [comment]
您好，这些都已经存储在输出的npz文件里了，
https://github.com/Arthur151/ROMP/tree/master/simple_romp#how-to-load-the-results-saved-in-npz-file
3D位置:'joints', 关节3D旋转角'smpl_thetas'
