### ISSUE TITLE
关于joints的问题

### ISSUE THREAD

**Issue by Yuanhong200727** [Arthur151/ROMP#403]
作者您好！
请问输出的npy文件中的joints的坐标是以什么为原点的呢？

**Comment by Yuanhong200727** [comment]
请问cam_trans是每一帧人体根节点到相机的相对位置吗，我能否用joints中smpl其余23个关键点的坐标减去根节点的坐标得到相对坐标并结合cam_trans得到相机坐标系下的关键点坐标呢

**Comment by Arthur151** [comment]
joints就是相对于根节点的相对坐标。

**Comment by Yuanhong200727** [comment]
我把joints中的'Pelvis_SMPL’:0和根节点混为一谈了,也就是说cam_trans+joint就是24个关键点的相机坐标系下的坐标了吗？

**Comment by Arthur151** [comment]
是的

**Comment by Yuanhong200727** [comment]
感谢！您的repo对我帮助很大！
