### ISSUE TITLE
Missing trailing comma in lines with "typing-extensions>=4.1"

### ISSUE THREAD

**Issue by wevertonms** [Arthur151/ROMP#409]
I tried to install, but it failed, so I realized it's missing a trailing comma in the `setup.py` in lines 13 and 27. After adding that, the package installed successfully. 🎉 

https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/setup.py#L13

https://github.com/Arthur151/ROMP/blob/a349c6bf4d6229b8fba2e900d38ef210888937d0/simple_romp/setup.py#L27

**Comment by Arthur151** [comment]
Thanks a lot for reporting this. 

I have fixed it. 

Best,
Yu
