### ISSUE TITLE
Pose blend shape vector (207)

### ISSUE THREAD

**Issue by Fabioo29** [Arthur151/ROMP#41]
Hey, thanks for letting this open source! 

I was trying to merge your project with another one and for that other project I needed a 207-dim Pose Blend Shape as input. Checking your code the close I can get, it's a 72-dim pose parameter... Is there any way to convert those parameters to the 207 vector that I need? 

Thanks

**Comment by Arthur151** [comment]
What is the 207-dim Pose Blend Shape?

**Comment by Fabioo29** [comment]
https://files.is.tue.mpg.de/black/papers/SMPL2015.pdf [SMPL Paper // Page 5]

```
Pose blend shapes. We denote as R : R|✓
~| 7! R9K a function
that maps a pose vector ~✓ to a vector of concatenated part relative
rotation matrices, exp(~!). Given that our rig has 23 joints, R(~✓) is
a vector of length (23 ⇥ 9 = 207). Elements of R(~✓) are functions
of sines and cosines (Eq. (1)) of joint angles and therefore R(~✓) is
non-linear with ~✓.
```

The project that I'm trying to merge with yours is Tex2Shape

**Comment by Arthur151** [comment]
The estimated pose vector is 3D rotation vector of 24 joints(1 root joint+23 body joints), 72=24*3. 
The 23 ⇥ 9 = 207 you want might be the 3D rotation matrix of 23 body joints?
Please use [this](https://github.com/Arthur151/ROMP/blob/48b8dde4df507f4c15b0c0fd3c0144bb3f0e0bf0/src/lib/utils/util.py#L426) to convert the estimated 3-dim 3D rotation vectors to 9-dim 3D rotation matrix.

For example, 
```
transform_rot_representation(pose.reshape(-1,3), input_type='vec',out_type='mat')
```
