### ISSUE TITLE
The unit of 3d pose

### ISSUE THREAD

**Issue by FireMonkey796** [Arthur151/ROMP#42]
Hello. Thank you for your work.
I wonder that what's the unit of 3d pose? I found it completely different from the annotations in 2d which are the pixel value. Instead, they are the value at around [-5,5] like the screenshot.
What's the actual meaning of these values and how to measure them in the real world?

![3DPW](https://user-images.githubusercontent.com/82449893/117293677-488cf900-aea4-11eb-8d7d-23c2bf90dd24.png)

**Comment by Arthur151** [comment]
It seems like the ground truth of 3DPW dataset. 
The unit is meter.

**Comment by FireMonkey796** [comment]
But why the meter has negative value? Is it zero-centered, and the center point is pelvis?

**Comment by Arthur151** [comment]
No. the 'center point' you mentioned is the origin of the 3D coordinates. 
About the details of 3DPW datasets, please ask the author of the paper.
