### ISSUE TITLE
the coco2014 dataset is this？

### ISSUE THREAD

**Issue by balabalaboy** [Arthur151/ROMP#429]
![image](https://user-images.githubusercontent.com/125865806/224918072-60f4c3d8-5130-41d7-b5fe-9855456a2632.png)
![1678776533782](https://user-images.githubusercontent.com/125865806/224918523-e70be79e-75d0-4d61-81c7-0e8589340aec.jpg)

**Comment by Arthur151** [comment]
Yes, it is.
