### ISSUE TITLE
can bev render the mesh on a blank image with RGBA channels from which the A channel indicates transparency of the meshed model?

### ISSUE THREAD

**Issue by Lukzin** [Arthur151/ROMP#430]

**Comment by Arthur151** [comment]
To achieve this, you may need to edit this function:

https://github.com/Arthur151/ROMP/blob/12a624f00be92d1f7195f24106d151d2f26961f4/simple_romp/vis_human/main.py#L23

and re-install the simple-romp via
https://github.com/Arthur151/ROMP/blob/12a624f00be92d1f7195f24106d151d2f26961f4/simple_romp/reinstall.sh
 to make the change get effective.

**Comment by Lukzin** [comment]
Thanks a lot.
