### ISSUE TITLE
Issues with the post processing code

### ISSUE THREAD

**Issue by mkhoshle** [Arthur151/ROMP#445]
Hello,

I am training the code on 3DPW. I start from pre-trained resnet backbone and finetune the backbone during the training. During training the visualized results look pretty reasonable:
![im3](https://github.com/Arthur151/ROMP/assets/21323137/74f49b8e-f497-4ffe-be2e-632eed607f22)
![im3_reconstruction](https://github.com/Arthur151/ROMP/assets/21323137/2ef835b0-812c-4dbf-af22-691f71c3fe4e)
However when I save the model as a `.pkl` file and use it using `test.py` or `image.py` to do the prediction I get nothing. I am so confused, am I doing anything wrong here?
![media_images_Heatmaps_32_a24a022ab65db3f35b5a](https://github.com/Arthur151/ROMP/assets/21323137/8d25e87a-600a-4d6a-a6a6-15b14b92b9eb)

![media_images_Mesh_Rensering_17_cb851c8455cacb661a49](https://github.com/Arthur151/ROMP/assets/21323137/0cd8af71-f7e0-418f-b160-ce941367e635)

I appreciate any feedback.
Thanks

**Comment by Asteria0000** [comment]
Hi, do you solved this problem?
