### ISSUE TITLE
Estimated camera parameters

### ISSUE THREAD

**Issue by jamesyoung0623** [Arthur151/ROMP#448]
### Discussed in https://github.com/Arthur151/ROMP/discussions/447

<div type='discussions-op-text'>

<sup>Originally posted by **jamesyoung0623** June  1, 2023</sup>
Hello,
Thank you for the great work!
I want to ask how to construct the intrinsic and extrinsic parameters from the data in saved npz files.
There are items like cam, global_orient, center_preds, center_confs, and cam_trans but I don't know how to construct the intrinsic and extrinsic parameters with these data.
Can someone help?
Thanks in advance.</div>

**Comment by Dipankar1997161** [comment]
> ### Discussed in #447
> 
> Originally posted by **jamesyoung0623** June 1, 2023 Hello, Thank you for the great work! I want to ask how to construct the intrinsic and extrinsic parameters from the data in saved npz files. There are items like cam, global_orient, center_preds, center_confs, and cam_trans but I don't know how to construct the intrinsic and extrinsic parameters with these data. Can someone help? Thanks in advance.

I believe this comment can help you https://github.com/Arthur151/ROMP/issues/421#issue-1600146589

**Comment by jamesyoung0623** [comment]
Thanks a lot!
