### ISSUE TITLE
Tex Render (Vedo?) with video config

### ISSUE THREAD

**Issue by Fabioo29** [Arthur151/ROMP#45]
Hi! Is it possible yet to render the model mesh like in the inference with the  single_image config but with model texture (png)? 
I see that you have it working on inference with the webcam config already, that's why I'm asking.

Thanks for this project! :)

**Comment by Arthur151** [comment]
Thanks for your suggestion. 
I need some time to figure it out.

**Comment by Arthur151** [comment]
Sorry for the delay. I am trapped by some urgent projects. 
It could work with careful adjustment on the camera parameters

**Comment by Fabioo29** [comment]
@Arthur151 It's okay. I've managed to get it to work already that's why I closed. Thanks for your attention

**Comment by Arthur151** [comment]
Glad to know about that. 
May I ask how did you make it work? Is it convenient to share the relative code? So I can merge it into this repository and make more people enjoy your work.

**Comment by Fabioo29** [comment]
I'll do it for sure! :) 
I had to make a few changes on the code because I am working with another model(with more vertices) and made it to work with this new model but I will try to make it to work based on your code and I'll update you soon ;)

**Comment by Arthur151** [comment]
Thanks!

**Comment by Fabioo29** [comment]
@Arthur151 Sorry, I don't have time to go deep into it.
Btw, There's the main code block that I've used to add texture to the model object (.obj).

```python
tex = Image.open('../texture.jpg')
mat = trimesh.visual.material.SimpleMaterial(image=tex)
mesh = trimesh.exchange.load.load(open('../object_with_vt.obj','rb'), file_type='obj', force='mesh')
mesh.visual.material = mat
```

The problem here is adding vt indices into .obj. I had some troubles doing it then I started using those .obj from Tex2Shape which already had vt indices on it instead of trying to reproduce them properly. Once you can see the texture on the .obj model on a mesh viewer software like ctmviewer you're good to go with the snippet above. Sorry for not having the final solution for you but this way worked for me.

**Comment by Arthur151** [comment]
Thanks a lot! I will look into it. This seems like a portable way.
