### ISSUE TITLE
romp.pack_smpl_info: command not found

### ISSUE THREAD

**Issue by ivanvoid** [Arthur151/ROMP#451]
Unuintu 22.04, install using pip in conda env. 

Just running `romp -h` in terminal works, 

but `romp.pack_smpl_info -source_dir=/path/to/smpl_model_data` returns `romp.pack_smpl_info: command not found` error.
Any idea what to do?

**Comment by Arthur151** [comment]
Yes,sorry for this, I will fix this in an hour.

**Comment by Arthur151** [comment]
@ivanvoid 
I have upload a new version of smpl-romp to pypi.

Please refer to  https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md
```
# please provide the absolute path of the "smpl_model_data" folder to the source_dir 
romp.prepare_smpl -source_dir=/path/to/smpl_model_data
# (Optional) If you use BEV, please also run:
bev.prepare_smil -source_dir=/path/to/smpl_model_data
```


For ubuntu, you can use
```
pip install simple-romp==1.0.9
```
Later, when the simple-romp==1.1.0 gets passed the check, I will update this page. 

Please let me know if anything goes wrong.

**Comment by Arthur151** [comment]
Please refer to https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md
Now we have:
```
pip install simple-romp==1.1.1
```

**Comment by neverstoplearn** [comment]
> Please refer to https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md Now we have:
> 
> ```
> pip install simple-romp==1.1.1
> ```

thanks for your work. but when I use romp.pack_smpl_info -source_dir=/home/xxx/ROMP/smpl_model_data --gender='female' 
I got romp.pack_smpl_info: command not found error. other commond like  romp.prepare_smpl work will, I try 1.1.1 and 1.1.3, how can i fix it? thanks.

**Comment by alvaro-budria** [comment]
> > Please refer to https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md Now we have:
> > ```
> > pip install simple-romp==1.1.1
> > ```
> 
> thanks for your work. but when I use romp.pack_smpl_info -source_dir=/home/xxx/ROMP/smpl_model_data --gender='female' I got romp.pack_smpl_info: command not found error. other commond like romp.prepare_smpl work will, I try 1.1.1 and 1.1.3, how can i fix it? thanks.

I got the exact same error on `1.1.3.`.
