### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by imbasoul** [Arthur151/ROMP#452]
Hi, you may forget to upload this 'src/deform_conv_cuda.cpp' file into the repo. Because it was ignored by the .gitignore file in the first line.

Best,

**Comment by Arthur151** [comment]
@imbasoul 
Thanks for reminding! I have fixed this.
Please refer to [the latest intructions](https://github.com/Arthur151/ROMP/blob/master/simple_romp/trace2/README.md).
Best,
Yu
