### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/yusun/Infinity/project_data/trace_data/model_data/parameters/SMPL_NEUTRAL.pth'

### ISSUE THREAD

**Issue by jwings1** [Arthur151/ROMP#455]
I encountered an error while running the submission script with the following command:

```shell
CUDA_VISIBLE_DEVICES=0 trace2 -i <<path to video>> \
--subject_num=1 --save_path <<path to my_folder>> \
--results_save_dir <<path to my_folder>> \
--smpl_path ~/.romp/SMPL_NEUTRAL.pth \
--save_video
``` 
Error Message:
"FileNotFoundError: [Errno 2] No such file or directory: '/home/yusun/Infinity/project_data/trace_data/model_data/parameters/SMPL_NEUTRAL.pth' "

Expected Behavior:
I expected the submission script to run successfully and process the specified video file, generating the desired output.

Additional Information:
- I pulled changes earlier this morning and read #454 

Potential Causes:
Based on the error message, it appears that there is an issue with the construction of the path used in trace2/utils/visualize_results.py

Any help or insights on resolving this issue would be greatly appreciated. Thank you!

**Comment by Arthur151** [comment]
@jwings1 Sorry for the bugs. 
Please use the latest Github code and prepare SMPL model files following :
https://github.com/Arthur151/ROMP/tree/master/simple_romp/trace2#installation

**Comment by jwings1** [comment]
@Arthur151

Thank you for your quick response and the information provided. I was able to resolve the issue by replacing all occurrences of `/home/yusun` with `/home/<my_home>` in the script. The script is now running successfully as expected. 

I appreciate the hard work you and your team are putting into this project. Your consistent updates and quick responses to issues make a significant difference.

Thank you again for your help!

Best,
<Your Name>
