### ISSUE TITLE
About the camera map

### ISSUE THREAD

**Issue by NoLookDefense** [Arthur151/ROMP#46]
Hello. I feel a little concerned about your "camera map".

As illustrated in your paper, the camera map **_contains the 3-dim camera parameters (s, tx , ty ) that describe the 2D scale s and translation t = (tx , ty ) of the person in the image. The scale s reflects the body size and the depth to some extent. tx and ty , ranging in (−1, 1), reflect the normalized translation of the human body relative to the image center on the x and y axis, respectively._**

From my personal perspective, the camera map may contain 6 parameters: rotation and translation of 3 axis, which comprises the extrinsic parameters of the camera position. Maybe I may recognise the parameter **s** as the translation of z dimension, but I am wondering that how can we obtain the rotation of the xyz dimension?

**Comment by Arthur151** [comment]
For ROMP, we integrate the absolute rotation of camera and the absolute rotation of each person into the relative 3D rotation of person root  to the camera. The estimated 'global_orent' is the the relative 3D rotation of person to the camera. You may assume that the camera is always pointing to the negative direction of z axis, while the person rotates.

**Comment by NoLookDefense** [comment]
Thanks for your quick response. I may study deeper to understand it..
I saw that the output of the model contains a keyword "joints_smpl24". But it contains a tensor with a size of 45*3 instead of 24*3, which is different from other work. May I ask what's the meaning of the remaining 21*3 vector?

**Comment by Arthur151** [comment]
Sorry for the delay. The rest 21 joints are 5 face joints + 5 right hand joints + 5 left hand joints + 3 left foot joint + 3 right foot joints. Please refer to [this dict](https://github.com/Arthur151/ROMP/blob/7400b34d1d69112625a2165c78b5c754943651c0/src/lib/models/smpl.py#L401) for the details

**Comment by NoLookDefense** [comment]
That's all right. Thanks for your explanation!
