### ISSUE TITLE
输出特征图大小为64*64？

### ISSUE THREAD

**Issue by caihaunqai** [Arthur151/ROMP#465]
您好，感谢您的工作。我看到输出的特征图的大小都是64 * 64，例如中心点的图我理解是把原本不为64 * 64的原图进行了归一化，所以可以对应到64 * 64上。那么其他的预测信息，例如3d关节点的旋转，pose/shape等信息是如何对应到64 * 64上的呢？输出一共是（1+3+132 + 10）个channel，如何把输入转换为64 * 64，这个我看了好久，能否麻烦解释一下，感谢！

**Comment by Arthur151** [comment]
@caihaunqai 
输出的是两张图：
一张是人体中心位置图，1*64*64，每个值表示该位置为某个人的中心点的概率值，表示多个人在图像中的位置。
另一张是人体参数图，N*64*64，每个位置是一个N维向量，表示对应位置人的全部人体参数，也就是你说的（1+3+132 + 10），是64*64大小的图的每个位置都有一个这样的向量。

**Comment by caihaunqai** [comment]
明白，请问如果一张图只有一两个人，那么64*64的图里，其他的位置的像素值一般会是多少呢？因为他们实际并没有作用，会预测成一个一致的默认值吗？

**Comment by Arthur151** [comment]
不会是一个统一的值，每张图都不一样，我们使用改进的focal loss训练的，没有人的只是置信度低。
