### ISSUE TITLE
3DPW results

### ISSUE THREAD

**Issue by fabienbaradel** [Arthur151/ROMP#471]
Hi @Arthur151 ,
Thanks for your amazing work. In the supp. mat. of the BEV paper you are reporting result of ROMP and BEV on 3DPW test set (Table 5). But since your method is solving at the same time the detection and the regression I am wondering what kind of detection rate do you get? I am not able to find this information in your paper.
And for Table 5 (cf attached) do you compute the metrics on the matched person or on all the persons?
Thanks for you help,

![Screenshot 2023-07-25 at 14 52 26](https://github.com/Arthur151/ROMP/assets/11565723/7f255d19-0870-4323-8f5e-4b9f11fe83f3)

**Comment by Arthur151** [comment]
@fabienbaradel 
During evaluation, we directly match the ground truth with the most close prediction for evaluation. So I think this refers to all people. 
As we all know that 3DPW only provide the ground truth for 1 or 2 people in the scene. In many scenes, it lacks detection annotations for all people in the scene, while ROMP and BEV try to predict all people in the scene. So, you know.
