### ISSUE TITLE
can not find the SMPL_NEUTRAL.pkl and romp.prepare_smpl

### ISSUE THREAD

**Issue by lyk412** [Arthur151/ROMP#472]
Hi, thanks for your awesome work! I met some problem when follow [https://github.com/Arthur151/ROMP/blob/master/simple_romp/README.md#installation](url). To be concrete, I download "Download version 1.1.0 for Python 2.7 (female/male/neutral, 300 shape PCs)"  and unzip it, but `SMPL_NEUTRAL.pkl` is not found. Besides, I saw the command `romp.prepare_smpl -source_dir=/path/to/smpl_model_data`, but I can not locate the romp.prepare_smpl.

**Comment by yayuanli** [comment]
Hi @lyk412 , I am having the same issue. Could you share your solution? Thanks.

**Comment by yayuanli** [comment]
I think the basicmodel_neutral_lbs_10_207_0_v1.1.0.pkl is what they meant by SMPL_NEUTRAL.pkl

**Comment by SunMH-try** [comment]
@yayuanli Do you find romp.prepare_smpl? I cannot run this.
