### ISSUE TITLE
ROMP and BEV ckpt finetuned on AGORA

### ISSUE THREAD

**Issue by fabienbaradel** [Arthur151/ROMP#478]
Hi,
Thanks for your amazing work. I cannot find how to download ```BEV_ft_agora.pth``` on your repo. The ```train_models.zip``` does not have this model.
Would it be possible to share the ckpt? Sam for ROMp finetuned on AGORA?
Thanks for your time,

**Comment by Arthur151** [comment]
Hi @fabienbaradel 
As indicated by this instruction, 
https://github.com/Arthur151/ROMP/blob/master/docs/bev_evaluation.md#agora
current BEV model has been fine-tunned on AGORA. So you can just change the name to current model. 

About the ROMP model: Sorry, it is trained about two years ago. I didn't keep it. 
But if you have deployed the training code of ROMP, it should be easy to get it. 
Have a nice day.
