### ISSUE TITLE
Permission denied: '/home/yusun' when running demo of TRACE

### ISSUE THREAD

**Issue by IsshikiHugh** [Arthur151/ROMP#488]
When I try to run demo [here](https://github.com/Arthur151/ROMP/blob/master/simple_romp/trace2/README.md), I met the error of the strange path.

> Processing ['....../ROMP/simple_romp/video/trace_demo']
> ....../.miniconda3/envs/romp/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2895.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> FPS: 5.029649814077884
> Traceback (most recent call last):
>   File "....../.miniconda3/envs/romp/bin/trace2", line 33, in <module>
>     sys.exit(load_entry_point('simple-romp==2.0.2', 'console_scripts', 'trace2')())
>   File "....../.miniconda3/envs/romp/lib/python3.8/site-packages/simple_romp-2.0.2-py3.8-linux-x86_64.egg/trace2/main.py", line 141, in main
>     trace.save_results(outputs, tracking_results, kp3d_results, imgpaths)
>   File "....../.miniconda3/envs/romp/lib/python3.8/site-packages/simple_romp-2.0.2-py3.8-linux-x86_64.egg/trace2/main.py", line 129, in save_results
>     save_paths = preds_save_paths(self.results_save_dir, prefix=seq_name)
>   File "....../.miniconda3/envs/romp/lib/python3.8/site-packages/simple_romp-2.0.2-py3.8-linux-x86_64.egg/trace2/utils/utils.py", line 13, in __init__
>     os.makedirs(self.seq_save_dir, exist_ok=True)
>   File "....../.miniconda3/envs/romp/lib/python3.8/os.py", line 213, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "....../.miniconda3/envs/romp/lib/python3.8/os.py", line 213, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "....../.miniconda3/envs/romp/lib/python3.8/os.py", line 223, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/home/yusun'

And here is my command:

> `CUDA_VISIBLE_DEVICES=0 trace2 -i <path-to-demo>/trace_demo --subject_num=1 --save_path <path-to-save>`

------

I tried to use `--save_path` but it seems useless. Then I replace all the `/home/yusun` to an acceptable path, and the error doesn't disappear until I rebuild `simple_romp`. 

Am I using it incorrectly?

**Comment by Arthur151** [comment]
@IsshikiHugh 
Thanks for reporting this bug! 
You are doing great.

**Comment by avegetablechicken** [comment]
I used `--results_save_dir` instead of `--save_path` and it worked.
