### ISSUE TITLE
pth generation

### ISSUE THREAD

**Issue by xz-123-new** [Arthur151/ROMP#496]
how to generate file smpla_packed_info.pth, i can only get access to siml_packed_info.pth, seems like there used to have link https://github.com/Arthur151/ROMP/releases/download/V2.0/ to provide these pth file, how can i generate it myself now?

**Comment by zhengchangren95** [comment]
> how to generate file smpla_packed_info.pth, i can only get access to siml_packed_info.pth, seems like there used to have link https://github.com/Arthur151/ROMP/releases/download/V2.0/ to provide these pth file, how can i generate it myself now?

Hi, do you still have this file (siml_packed_info.pth), the link is 404 and can not be downloaded now. Thank you so much.
