### ISSUE TITLE
Segmentation of the people parts

### ISSUE THREAD

**Issue by darkhorrow** [Arthur151/ROMP#50]
Hello! I´ve been using your work recently and its very good! However, I´m stuck trying to do the segmentation of the different body parts in the mesh of the results.

So far, I tried to use the SMPL format and this labeler: https://github.com/ZhengZerong/SmplLabeling, but I do not find some information in the results as, in example, the J regressor.

There is a way with the current code to do this? If I didn´t explain myself well enough, do not hesitate to ask me.

Thank you in advance.

**Comment by Arthur151** [comment]
Hi, are you trying to get the body part index of each vertice of SMPL model?

**Comment by darkhorrow** [comment]
Yes, that would do the trick. But I don´t understand how to accomplish that with the j3d_smpl24 numpy array.

**Comment by Arthur151** [comment]
I think that you might be looking for 
https://github.com/gulvarol/surreal/blob/master/datageneration/pkl/segm_per_v_overlap.pkl
Don't forget to cite their paper if you use it.

**Comment by darkhorrow** [comment]
Thanks! I think I do understand now. Thank you for the help!
