### ISSUE TITLE
3DPW数据预处理细节

### ISSUE THREAD

**Issue by FishWoWater** [Arthur151/ROMP#51]
您好！
我在 [3DPW比赛网站](https://competitions.codalab.org/competitions/24938#phases)上找到的两个 track都是不允许用 2D pose对图片进行crop的，但是看到您这边说 follow的 VIBE [数据预处理](https://github.com/mkocabas/VIBE/blob/master/lib/data_utils/threedpw_utils.py)都是用的 官方提供的2D pose得到 bbox的，这样是不是就少了一个tracking的误差? 还是在比赛之外大家评测的时候就是给定了对应关系? 
感谢!

**Comment by Arthur151** [comment]
您可以看一些[评测](https://github.com/Arthur151/ROMP/blob/master/docs/evaluation.md)部分。
我们采用了两套评测protocol。一套是3DPW challenge的，另一套是之前方法(VIBE,SPIN,HMR等)评测采用的范式。
ROMP作为一个bottom-up方法一直是整张图输入的，没有ｃｒｏｐ过。可以看一下/跑一下我们的评测代码确认。
我们这里求bbox只是用于将输出结果和ground truth匹配，不然没法评测。至于其他方法，他们有自己的pipeline，有的可能是top-down的，您应该有判断，这里就不评价了。

**Comment by FishWoWater** [comment]
感谢!

**Comment by FishWoWater** [comment]
@Arthur151 抱歉,再打扰一下! 请问可以提供一下您这边划分的3DPW-OC, 3DPW-PC, 3DPW-NC子数据集或者划分方式/代码吗

**Comment by Arthur151** [comment]
PW3D_PCsubset = {'courtyard_basketball_00':[200,280], 'courtyard_captureSelfies_00':[500,600],\
                'courtyard_dancing_00':[60,370],  'courtyard_dancing_01':[60,270], 'courtyard_hug_00':[100,500], 'downtown_bus_00':[1620,1900]}


PW3D_OCsubset = ['courtyard_backpack','courtyard_basketball','courtyard_bodyScannerMotions','courtyard_box','courtyard_golf','courtyard_jacket',\
'courtyard_laceShoe','downtown_stairs','flat_guitar','flat_packBags','outdoors_climbing','outdoors_crosscountry','outdoors_fencing','outdoors_freestyle',\
'outdoors_golf','outdoors_parcours','outdoors_slalom']

NC是其余的

**Comment by xthan** [comment]
> 您可以看一些[评测](https://github.com/Arthur151/ROMP/blob/master/docs/evaluation.md)部分。 我们采用了两套评测protocol。一套是3DPW challenge的，另一套是之前方法(VIBE,SPIN,HMR等)评测采用的范式。 ROMP作为一个one-stage bottom-up方法一直是整张图输入的，没有ｃｒｏｐ过。可以看一下/跑一下我们的评测代码确认。 我们这里求bbox只是用于将输出结果和ground truth匹配，不然没法评测。 我们的目前的方法没有加tracking功能，所以只能评测with association那个track。不评测tracking性能。 至于其他方法，他们有自己的pipeline，有的可能是top-down的，您应该有判断，这里就不评价了。

你好，如果在一张图中，ROMP没有检测出人或者检测多了一个人，找不到和ground truth匹配的时候，要怎么计算评测指标呢？

**Comment by Arthur151** [comment]
你可以参见[这里](https://github.com/Arthur151/ROMP/blob/992544341d9469c30de884403a3fc7b977974aa8/romp/lib/evaluation/collect_3DPW_results.py#L118),我们给miss的填充了0姿态的三维人体网格。

3DPW不评测检测性能，因为确实图中有些人是没有3D标注的。多出来的估计不会被评测。
