### ISSUE TITLE
About exporting to meshlab

### ISSUE THREAD

**Issue by NoLookDefense** [Arthur151/ROMP#56]
Hello. Will the code support exporting the mesh to the "meshlab"

**Comment by Arthur151** [comment]
Currently, ROMP already exports the mesh in obj format, which could be imported to meshlab. 
Is there any other thing you need?

**Comment by NoLookDefense** [comment]
> Currently, ROMP already exports the mesh in obj format, which could be imported to meshlab.
> Is there any other thing you need?

Oh, thank you. May I know that which code I should run to obtain the .obj file? I can only see the document about exporting to fbx

**Comment by Arthur151** [comment]
[Configuration of saving mesh](https://github.com/Arthur151/ROMP/blob/master/docs/config_guide.md#save_mesh)
Better to run in [single image mode](https://github.com/Arthur151/ROMP#internet-images)

**Comment by NoLookDefense** [comment]
Thank you, I obtain the .obj file successfully.
BTW, I wonder when the training code will be released?

**Comment by Arthur151** [comment]
The paper is under submission. The training code will be released when... I will update this issue.
Thanks for your attension.

**Comment by NoLookDefense** [comment]
Thank you for your great work! Have a nice day

**Comment by MarkZuruck** [comment]
> [Configuration of saving mesh](https://github.com/Arthur151/ROMP/blob/master/docs/config_guide.md#save_mesh) Better to run in [single image mode](https://github.com/Arthur151/ROMP#internet-images)

how to save the mesh please ? I changed save_mesh to True and nothing is saving, how romp will even know if im changing a file in the config folder? Any help or explanation would be so much appreciated

**Comment by MarkZuruck** [comment]
@NoLookDefense @Arthur151

**Comment by MarkZuruck** [comment]
simple romp I guess, pip install --upgrade simple-romp.

Then, how to extract them to an obj file from the npz one ?

**Comment by Arthur151** [comment]
Here is the function to save the vertices to a mesh obj file

https://github.com/Arthur151/ROMP/blob/b108da9e9fe96282d8235a1051a7030d335d9869/romp/lib/utils/util.py#L206
the mesh vertices are saved in npz file.
The faces is the face_tensor of 
https://github.com/Arthur151/ROMP/blob/b108da9e9fe96282d8235a1051a7030d335d9869/simple_romp/romp/smpl.py#L45
You can get the face via torch.load(smpl_model_path)['f']
