### ISSUE TITLE
How to generate bounding boxes?

### ISSUE THREAD

**Issue by LandryBulls** [Arthur151/ROMP#59]
Hello - this is excellent work! I understand that the bbox-free method is one thing that allows ROMP to perform so well - but for my purposes I am needing to generate 2D body bounding boxes to cross-reference with 2D locations of faces in image space. My plan was to use the `batch_orth_proj` function from the `projection` script to generate bboxes in image space from the 2D keypoints, but I am unsure where to insert this function and what it's inputs should be as the latest commit no longer contains the `_calc_smplx_params` function that used to be in `base.py` (as mentioned in #15 ). Could you clarify where I can use this function to ultimately generate 2D keypoint detections in image space as part of the final `.npz` output?

**Comment by Arthur151** [comment]
Thanks for your interests in ROMP. 
I just merge a pull request from the other contributor and deal with some conflicts. 
I will add the code of generating 2D keypoint detections in image space later tody. I will update this issue then.

**Comment by Arthur151** [comment]
@LandryBulls ,Hi Landry Bulls, 
I have uploaded a new commit to project the 3D pose back to 2D joint coordinates on original image. See [here](https://github.com/Arthur151/ROMP/blob/78a4f44591abd342816cdb31f27364bec1ab98ea/src/lib/utils/projection.py#L25).  
 In output zip, its key is 'pj2d_org'.
Enjoy your day.
Best

**Comment by LandryBulls** [comment]
Wow - thanks for the very quick response! It is much appreciated.
