### ISSUE TITLE
Questions about 3DPW-PC, 3DPW-OC dataset 

### ISSUE THREAD

**Issue by frankjappa95** [Arthur151/ROMP#60]
First of all, thank you for this wonderful task that your team have made :) 

I wonder how the 3DPW-PC, OC data can be acquired, as there's no information about them in 3DPW homepage. 

Thanks a lot! :)

**Comment by Arthur151** [comment]
3DPW-PC and 3DPW-OC are just the subsets of the 3DPW dataset. 
3DPW-OC is described in the SubMat of Object-Occluded Human Shape and Pose Estimation From a Single Color Image.
PW3D_OCsubset = ['courtyard_backpack','courtyard_basketball','courtyard_bodyScannerMotions','courtyard_box','courtyard_golf','courtyard_jacket',\
'courtyard_laceShoe','downtown_stairs','flat_guitar','flat_packBags','outdoors_climbing','outdoors_crosscountry','outdoors_fencing','outdoors_freestyle',\
'outdoors_golf','outdoors_parcours','outdoors_slalom']

PW3D_PCsubset = {'courtyard_basketball_00':[200,280], 'courtyard_captureSelfies_00':[500,600],\
                'courtyard_dancing_00':[60,370],  'courtyard_dancing_01':[60,270], 'courtyard_hug_00':[100,500], 'downtown_bus_00':[1620,1900]}

**Comment by frankjappa95** [comment]
Thank you for the explanation :)
