### ISSUE TITLE
Why is this happening

### ISSUE THREAD

**Issue by zhanghongyong123456** [Arthur151/ROMP#66]
when i run  python core/test.py --gpu=0 --configs_yml=configs/single_image.yml  in windows，
when i run，give me No J_regressor_h36m.npy file error ，so i find this ，
I'm not sure if this file is correct，Can you give me a link
![image](https://user-images.githubusercontent.com/48466610/128112794-831afdd4-7c45-4c07-afae-1681c21e06e8.png)

![image](https://user-images.githubusercontent.com/48466610/128112117-889b666a-a1e4-4c10-b2e9-befa5244a871.png)

**Comment by Arthur151** [comment]
Could you please put the original printed log on this issue?

**Comment by zhanghongyong123456** [comment]
> Could you please put the original printed log on this issue?

![image](https://user-images.githubusercontent.com/48466610/128113470-814d3e0d-b937-466f-aba4-9eb3f88b1579.png)

**Comment by zhanghongyong123456** [comment]
> Could you please put the original printed log on this issue?
I'm sorry, I copied the wrong file, when I used the right model（ROMP_data.zip）, I got the information, I checked my result, it was the same, why is that
![image](https://user-images.githubusercontent.com/48466610/128115223-93a1b540-9c6b-4117-a7a3-d6c21a804228.png)

**Comment by Arthur151** [comment]
The log has pointed out the problem! You didn't download our model.
Warning: root model ../trained_model/ROMP_hrnet32.pkl not exists!
Please properly set the path of the in configs/single_image.yml,
gmodel_path: path to your downloaded model

**Comment by zhanghongyong123456** [comment]
> The log has pointed out the problem! You didn't download our model.
> Warning: root model ../trained_model/ROMP_hrnet32.pkl not exists!
> Please properly set the path of the in configs/single_image.yml,
> gmodel_path: path to your downloaded model

ok，I'm really sorry. I found the problem. Thank you very much for your reply，It's working normally now，
Thank you again for a great project
