### ISSUE TITLE
Fine-tune on AGORA dataset

### ISSUE THREAD

**Issue by leeskyed** [Arthur151/ROMP#68]
Hi 请问后续有打算在训练数据上加入AGORA数据吗？感觉和你的任务也非常的匹配，同时也可以去做的augmentation来获得更多的多人数据。

**Comment by Arthur151** [comment]
如果您关注ＡＧＯＲＡ数据集的话，在AGORA评测网站上，我已经上传了ＲＯＭＰ fine-tunned后的性能了。可以看到较明显的优势。

**Comment by leeskyed** [comment]
这块的fine-tunned model会打算开源吗老哥
