### ISSUE TITLE
关于SMPL输入姿势参数维度问题

### ISSUE THREAD

**Issue by qihangran** [Arthur151/ROMP#69]
作者，你好。
在3dpw数据的leaderboard上刷到您的作品。拜读后，有一个疑惑：

论文里的输出SMPL parameter map的姿势参数Θ维度是6X22，原始SMPL模型是3X24,轴角表示； 24->22没什么问题。但是这个维度6，需要怎么输入进去SMPL模型呢，需要进行转换成轴角表示吗？ 另外这维度6的含义是？    希望作者能指导下

**Comment by Arthur151** [comment]
非常感谢您对ＲＯＭＰ感兴趣，很好的问题。
我们采用的是之前ＣＶＰＲ一篇工作提出的６Ｄ表征形式，文章中有相关阐述。
关于６Ｄ转３Ｄ的代码，[在这里](https://github.com/Arthur151/ROMP/blob/0f896212bdc464f0ed09f6cf263c1212639e542c/src/lib/utils/rot_6D.py#L5)

**Comment by qihangran** [comment]
谢谢啦， 我对旋转矩阵这块基础知识还不够了解，后面熟悉后也许会更能理解相关工作。
但还是想提前请问您一下，用6D表征，是因为它在表征旋转这块本身比其他表征法更好一些，还是因为6D表征比轴角表示对于神经网络更好学习一点？

**Comment by Arthur151** [comment]
您如果感兴趣的话，可以看一下提出该6D表征的文章：
On the continuity of rotation representations in neural networks
蛮有趣的文章，ROMP采用该表征，怎么说呢，就还挺好用。

**Comment by qihangran** [comment]
好的，谢谢~

**Comment by Tina-Husky** [comment]
I have a question. Why two hand joints are dropped, and for what reason?
我有一个问题，为什么要舍弃掉两个两只手的关节点？是出于什么样的考虑呢？

**Comment by Arthur151** [comment]
因为那两个点不同于其他关节点（关节旋转角），那么两个点对应的值是控制手势的，三个数表示一种手势，有独立的手势姿态空间。我们这里不估计手势，所以就去掉了。
Get Outlook for Android

**Comment by Tina-Husky** [comment]
好的，谢谢及时的解答
