### ISSUE TITLE
axis-angle

### ISSUE THREAD

**Issue by JACKYLUO1991** [Arthur151/ROMP#71]
感谢您的开源...有个问题想向您请教，axis-angle形式是否能转换成欧拉角以实现在Unity中逐帧驱动人物呢？

**Comment by JACKYLUO1991** [comment]
> 感谢您的开源...有个问题想向您请教，axis-angle形式是否能转换成欧拉角以实现在Unity中逐帧驱动人物呢？

貌似这里的axis-angle与传统定义不同

**Comment by Arthur151** [comment]
可以的，我们开源的代码中有可以自由转换关节角表征形式的[代码](https://github.com/Arthur151/ROMP/blob/0f896212bdc464f0ed09f6cf263c1212639e542c/src/lib/utils/util.py#L426).
调用格式为：
poses_euler = [transform_rot_representation(rot, input_type='vec',out_type='euler') for rot in poses.reshape(-1,3)]

**Comment by JACKYLUO1991** [comment]
@Arthur151 感谢您，我马上尝试一下...

**Comment by JACKYLUO1991** [comment]
再次打扰，我将旋转向量转为四元数以驱动类人物，然而在点位绑定无误的情况下，左右驱动呈镜像关系，请问是左右手坐标系问题吗？该如何解决呢？

**Comment by Arthur151** [comment]
意思是左右反了么？还是左右动作相同？
如果左右反了，就把关节点的顺序映射一下就好了，从左右映射到右左。

**Comment by JACKYLUO1991** [comment]
![63987715aeba5d6b0496419386d4db2](https://user-images.githubusercontent.com/21237742/132327807-a9476e0c-b6cc-4924-96e0-f1e19a7899e9.jpg)
实际效果是这样的，点位绑定反复检查过了应该没啥问题；另外，向后转身的方向是一致的，但是就是左右呈镜像关系...

**Comment by JACKYLUO1991** [comment]
@Arthur151 我是将smpl 24点轴角式表达，转为四元数驱动的

**Comment by Arthur151** [comment]
那就是关节点的顺序搞错了，左右弄反了。
[这里](https://github.com/Arthur151/ROMP/blob/0f896212bdc464f0ed09f6cf263c1212639e542c/src/lib/constants.py#L248)提供了ｓｍｐｌ关节点顺序左右互换的映射矩阵

**Comment by JACKYLUO1991** [comment]
@Arthur151 您好，我反复检查了点位的绑定和输出的index，发现并没有问题。我现在很迷惑，左右旋转方向是反的，但是转身的方向是对的...
