### ISSUE TITLE
部分数据集无法下载。

### ISSUE THREAD

**Issue by sunwenzhang1996** [Arthur151/ROMP#74]
您好，很感谢您分享您的工作。
我在下载数据集的时候发现谷歌网盘提示“此文件已超出下载配额，无法下载”。更换了网盘账号也是一样。不知道是不是数据集下载量太多了被谷歌限制了。
请问您那边还可以通过别的渠道分享一下数据集吗？

**Comment by Arthur151** [comment]
您可以将右键要下载的文件，然后保存到您自己的google网盘，就可以不受限制下载了。

**Comment by sunwenzhang1996** [comment]
好的好的，现在又可以下载了。谢谢！
