### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by zhLawliet** [Arthur151/ROMP#76]
你好，这里有两个疑惑
1 为啥crowdpose 里面是h36m_image.z03
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/17424385/134764694-a2a34171-e0ee-4160-b57e-75c9a3075b60.png">

2  提供的h36m的数据https://drive.google.com/drive/folders/1kNC5ptE3f95p1WdDIpWQyEx7KS-ILCp5
    解压的时候有问题：unzip h36m_image.zip
    报错
<img width="672" alt="image" src="https://user-images.githubusercontent.com/17424385/134764853-7b75d1d7-c17d-476c-9aed-c3531dfa5ff5.png">

**Comment by Arthur151** [comment]
多谢bug report！
问题1中提到的多余的文件已删除。
关于问题2，请用我们提供的解压缩脚本：h36m下载文件夹中的merge_splits_and_unzip.sh
cat h36m_image.z* > h36m_image_all.zip
unzip h36m_image_all.zip

**Comment by zhLawliet** [comment]
嗯，谢谢，忘记把h36m_image.zip放进去了
