### ISSUE TITLE
Benchmark Evaluation

### ISSUE THREAD

**Issue by zhLawliet** [Arthur151/ROMP#77]
你好，执行Benchmark Evaluation的代码的时候，输出的数值和git上不一样，差异很大，不知道你这边有没有确认这版代码：
cd ROMP
CUDA_VISIBLE_DEVICES=0 python romp/lib/evaluation/collect_3DPW_results.py --configs_yml=configs/eval_3dpw_challenge.yml
我这边执行的结果：
![image](https://user-images.githubusercontent.com/17424385/134797439-b79120c0-22cd-410d-b81f-087a5b177070.png)

我自己进行了一下排查：
代码模型的加载正确性验证：试了一下这版代码的下面两个执行脚本，效果是OK的。
sh scripts/image.sh
sh scripts/video.sh

未公布训练代码之前的 commit 7400b34d1d69112625a2165c78b5c754943651c0
Benchmark Evaluation，数值也是ok的。但是当前这个 commit 248660608d2de85d635122a1bb75ef4988b9947b的执行结果
不对，不知道哪里是不是有问题。

**Comment by Arthur151** [comment]
是的，最新版的评测代码的第一个评测确实有问题。目前还没腾出手来排查原因，但因为不想因为这个导致代码开源继续拖延，所以就开源了。后面会排查这个原因的。

**Comment by zhLawliet** [comment]
好的，谢谢
