### ISSUE TITLE
RuntimeError: NCCL Error 2: unhandled system error

### ISSUE THREAD

**Issue by zhLawliet** [Arthur151/ROMP#80]
CUDA_VISIBLE_DEVICES=0,1 python -u -m romp.predict.image --configs_yml='configs/image.yml'
你好，运行**多个**GPU的时候，在执行到outputs = self.net_forward(meta_data, cfg=self.demo_cfg)的时候报错
RuntimeError: NCCL Error 2: unhandled system error。
网上没有找到合适的解答，不知道你碰到过没。

**Comment by Arthur151** [comment]
抱歉，我是直接在conda 的 bash环境里运行的，没用过docker。貌似是docker多卡运行的bug吧

**Comment by zhLawliet** [comment]
好的，谢谢，我再看看
