### ISSUE TITLE
exporting to fbx error

### ISSUE THREAD

**Issue by Koushik0901** [Arthur151/ROMP#84]
Hi there, when I tried exporting the npz file to fbx a weird error occurred...

***KeyError: 'bpy_prop_collection[key]: key "f_avg_Pelvis" not found'***
***Error: Python script failed, check the message in the system console***

**Comment by Arthur151** [comment]
Please make sure that you have downloaded the SMPL_m_unityDoubleBlends_lbs_10_scale5_207_v1.0.0.fbx from the official website. The bug is obvious. It reports that the joint name mismatching. You can directly check the name of your fbx in Blender.

**Comment by Koushik0901** [comment]
Yeah, I have already downloaded  SMPL_f_unityDoubleBlends_lbs_10_scale5_207_v1.0.0.fbx and  SMPL_m_unityDoubleBlends_lbs_10_scale5_207_v1.0.0.fbx and yet I get this bug

**Comment by Arthur151** [comment]
Sorry for the unpleasant bugs. I have tested the code again. I can't re-implement your bugs. 
[This](https://github.com/Arthur151/ROMP/releases/download/v1.1/SMPL_f_unityDoubleBlends_lbs_10_scale5_207_v1.0.0.zip) is the fbx I used. Hope it can help you.

**Comment by Koushik0901** [comment]
Thanks!
