### ISSUE TITLE
Training on data subset

### ISSUE THREAD

**Issue by BenBausch** [Arthur151/ROMP#85]
Hello, I am preparing to write my master thesis about unsupervised pre-training/ training networks for human pose estimation. Since I currently only have limited GPU resources available and I want to get some intuitions if my idea could improve the performance, i have the following questions:

- Has ROMP used the imagenet pre-trained weights for the backbone?
- Is it possible to easily train on only a subset of the data, is the their a script to get the parsed annotations for the data subsets ?
- Did you try using other pre-trained weights (MOCO, DINO, ...) for the resent50 ?

thanks in advance!

**Comment by Arthur151** [comment]
Good questions!
1. ROMP used the pre-trained weights of backbone (HRNet-32/ResNet-50) that has been trained on 2D pose datasets (e.g. MS COCO, MPII). This also answer your third question.
2. I haven't tried to train ROMP only on a subset of the data. To get the parsed annotations, please refer to [this doc](https://github.com/Arthur151/ROMP/blob/master/docs/dataset.md)
