### ISSUE TITLE
about camera parameters

### ISSUE THREAD

**Issue by qihangran** [Arthur151/ROMP#86]
作者您好，
想请教下两个问题，
①文章中估计的相机参数是[s,tx,ty]，这个和文章hmr中的[s,tx,ty]是同一含义吗？ 看实现好像并不是一样的；hmr中有这样的疑问和我的类似[https://github.com/akanazawa/hmr/issues/142](url)
②可以直接估计[tx,ty,tz]来达到[s,tx,ty]同样效果吗？

**Comment by Arthur151** [comment]
大致是一样的，都是采用的弱透视投影相机。用三维平移代替的话，要采用透视投影相机才行，目前看没有明显提升，因为一般数据集没有此类标注。

**Comment by qihangran** [comment]
谢谢。
还有点模糊请教您，你说数据集没有此类标注，但是像您之前说的，相机参数训练是不需要ground truth的参数，是通过smpl投影到二维中与二维关键点比较来训练的，因此我理解与数据集标注没关系吧？那直接估计三维平移[tx, ty, tz]，然后通过 f*x/z 来获得图像坐标系下的x, 是不是理论上也可以呢？

**Comment by Arthur151** [comment]
不只是理论上，实际上也确实是可以的，我试过。
