### ISSUE TITLE
Question about the body center shift

### ISSUE THREAD

**Issue by jhkim0759** [Arthur151/ROMP#91]
Hi, 

I'm studying about your wonderful method in your paper.

But I got two case of questions about the body center shift.

First, what happen if there is person who have a same position with shifted body center.  

Second, how does the model know the body center was shifted or not.

Thank you.

**Comment by Arthur151** [comment]
Good questions!
1. Please pay attension to the details of the CAR. We don't directly shift the center once we detect collided centers. What the real first step is calculating the repulsion force for all centers. Then the second step is to calculate the join force at each center. What you concerned is the center that is affected by multiple surrounding centers. The join force will give the right place this kind of center should move.
2. We use the shifted center as the ground truth center location to supervise the Center heatmap. It doesn't matter wether the model know the body center was shifted. What matters are the supervision signal tells the model to predict the center like the shifted one.

**Comment by jhkim0759** [comment]
Thank you for your reply

Can I ask one more question?

When Parameter Sampling process, Body Center will be used to sample the parameter.
If model don't know the Center is shifted or not, how can it find correct center

**Comment by Arthur151** [comment]
Sorry, I don't think there is a thing called the 'correct center', CAR is just proposed to help the model to learn the better one in crowded scene. The key is that it can be learned by model and helpful. Why should the model must know the center is shifted?

**Comment by jhkim0759** [comment]
When you put a mesh value into an image, don't you need to know exactly where the center of the mesh is?

without knowing the center is shifted, I think model might put the mesh value at wrong place.

**Comment by Arthur151** [comment]
The experiments show that model knows where to put the mesh on the image with/without CAR. Detection and localization is two different task in ROMP.

**Comment by jhkim0759** [comment]
Oh, CAR is not for localization! Now I understand. 
I thought body center works for localization in Parameter sampling

Thanks a MILLION!

**Comment by Arthur151** [comment]
At my service. Nice dicussion.

**Comment by Arthur151** [comment]
@jhkim0759  Just to be clear, we estimate the body center via Body Center heatmap for detection and parameter sampling. For localization (scale and tx, ty in image), we estimate the Camera map, which is a part of Parameter map. 
Thanks for your interets!

**Comment by jhkim0759** [comment]
I’m really grateful for your help.
