### ISSUE TITLE
_calc_param_loss

### ISSUE THREAD

**Issue by HuiliCui** [Arthur151/ROMP#93]
![HDWPA@74JH{}AMLL4~AY~76](https://user-images.githubusercontent.com/62087070/139805475-e837a1c4-df6a-4c63-b2f5-622dd7638fb4.png)
您好，想问计算shape loss的时候为什么需要smpl_shape_masks.sum()>1而不是大于0呢，还有就是行114为什么要取反呢

**Comment by Arthur151** [comment]
哈哈，这个>1是偷懒，之前的pytorch版本如果只有一个会减少维度，为了避免维度减少，就>1了。
114行取反是指的没有smpl的shape参数的数据，就直接监督输出的L2正则化。

**Comment by HuiliCui** [comment]
但是如果数据含有shape参数也会执行114行，将会得到空值，导致计算的shape loss为nan呀

**Comment by Arthur151** [comment]
说得对，改过来了~非常感谢！
