### ISSUE TITLE
About 3DOH Evaluation 

### ISSUE THREAD

**Issue by qihangran** [Arthur151/ROMP#95]
作者你好， 请教一下，文章中你评估3DOH50K的PA-MPJPE时，是利用它的哪一个标注？
是类似SPIN的3DPW预处理方式，从SMPL标签里生成的3D 关键点， 还是直接利用它提供的3D 关键点作为gt？
我之所以有这个疑问是因为3DOH提供的3D关键点是相机坐标系下，但是每张图像给出了相机内参，这样跟我们训练时预设的5000焦距不同，这样的话是不是没法直接利用它提供的3D关键点标注，还是说需要做一些转换？

谢谢~

**Comment by Arthur151** [comment]
我们也注意到了这个问题，确实没法直接用它提供的3D关键点标注，需要变换一下尺度，不过我们也没法确定我们变换的尺度是不是准确的，所以在最终版本就取消了这部分的评测。

**Comment by qihangran** [comment]
真的谢谢，解答了疑惑

**Comment by zhLawliet** [comment]
@Arthur151 你好，请问下3DOH50K提供的smpl系数可以直接使用吗？我使用作者提供的代码https://gitee.com/seuvcl/CVPR2020-OOH/blob/master/utils/smpl_torch_batch.py 以及其提供的相机外参和内参可以得到其对应的smpl_joints_2d，但是把他提供的pose和shape倒入到 标准的SMPL代码from smplx import SMPL as _SMPL，发现最终无法得到对应的smpl_joints_2d。所以想确认一下，训练的时候是不是只能使用他的smpl_joints_2d标签，至于poses和betas以及smpl_joints_3d没法使用？

**Comment by Arthur151** [comment]
@zhLawliet 
Thanks for letting me know this. I think the main reason is that they introduce the scale factor
https://gitee.com/seuvcl/CVPR2020-OOH/blob/master/utils/smpl_torch_batch.py#L247
In standard SMPL, there is no scale factor, which would affact the shape.

**Comment by zhLawliet** [comment]
@Arthur151  嗯，那我理解就只能使用他的smpl_joints_2d标签了，当作2d数据集使用了？

**Comment by Arthur151** [comment]
把它出来的shape、vertices、kp3ds乘以它这个scale参数就可以正常使用了

**Comment by zhLawliet** [comment]
@Arthur151 谢谢，不太理解你的意思，我再描述一下我的疑惑：3DOH50K提供了的smpl系数（pose和shaep以及trans）以及相机外参和内参以及独特的scale参数。

当我把他的pose和shape以及trans导入到标准SMPL推理代码，可以得到
第一步
output = smpl(betas=shape[:, :], body_pose=pose[:,3:], global_orient=pose[:, :3], transl=trans[:, :])
verts = output.vertices.numpy()[0]
j3d = output.joints.numpy()[0]

第二步：对得到j3d进行 旋转以及投影
    intri = np.insert(intrinsic,3,values=0.,axis=1)
    temp_joint = np.insert(j3d, 3, values=1.,axis=1).transpose((1,0))
    out_point = np.dot(extrinsic, temp_joint) # 对应smpl_joints_3d
    dis = out_point[2]
    out_point = (np.dot(intri, out_point) / dis)[:-1].astype(np.int32)
    out_point = out_point.transpose(1,0) # [[0,1,2,3,4,5,6,7,8,9,12,13,14,15,16,17,18,19,20,21]]
    out_point = np.concatenate([out_point, np.ones([out_point.shape[0], 1])], 1)
    return out_point

发现结果不对：按照你说的将“把它出来的shape、vertices、kp3ds乘以它这个scale参数”，不太理解这里的它指的是什么，或者说这个scale 参数是乘以到第一步得到的j3d 还是乘以到第二步得到的out_point，但是我都试过，发现都没法正常投影。

所以还是觉得是不是只能使用他的pose和提供的smpl_joints_2d？

**Comment by Arthur151** [comment]
第一步得到的j3ds, verts。我记得好像是一个固定的数，貌似是7，具体不记得了。

**Comment by zhLawliet** [comment]
好的，谢谢
