### ISSUE TITLE
not enough human3.6m data

### ISSUE THREAD

**Issue by zhaishengfu** [Arthur151/ROMP#96]
Hello, great projects!
I downloaded the human3.6m dataset you supplied in google drive, but I find the image is not enough(original human3.6m website said it has 3milliion data, but your image only have 417774 images). So I guess you extract original video with less framerate ?

**Comment by Arthur151** [comment]
Yes, we downsample every 5 frames from the video. Because we find the redundant video frames are just unnecessary burden for the network. 
The code of extracting frames is presented at [here](https://github.com/Arthur151/ROMP/blob/master/romp/lib/dataset/preprocess/h36m_extract_frames.py)
