### ISSUE TITLE
How is the multi-person tracking information stored?

### ISSUE THREAD

**Issue by LandryBulls** [Arthur151/ROMP#98]
I'd like to know which body detected in each frame corresponds to which individual's track. When make_tracking=True and save_dict=True, should the results carry this track information?

**Comment by Arthur151** [comment]
Please see [here](https://github.com/Arthur151/ROMP/blob/992544341d9469c30de884403a3fc7b977974aa8/romp/predict/video.py#L161), we save the tracked results to an individual npz.
